package com.company.aiqa.generated;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.testng.Assert;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;

/**
 * Automated API tests for commit 3836dee9b71220800f7c019c8f865f7f9784d47a.
 * Generated by ai-qa-platform from that commit's manual test cases.
 */
public class AutomationTest_3836dee9b71220800f7c019c8f865f7f9784d47a {

    // Holds ids of merchants created during the suite, for cleanup only.
    private final java.util.List<String> createdMerchantIds = new java.util.ArrayList<>();

    @BeforeClass
    public void setup() {
        RestAssured.baseURI = System.getProperty("baseUri", "http://169.58.37.242:8007/mms");
    }

    @AfterClass
    public void cleanup() {
        // No DELETE for merchants in the endpoint list - no-op cleanup.
    }

    private String createMerchant(String legalName, String city) {
        String suffix = String.valueOf(System.currentTimeMillis());
        String body = """
                        {
                          "legalName": "%s",
                          "tradeName": "Trade_%s",
                          "registrationNo": "CR-%s",
                          "taxId": "TAX-%s",
                          "merchantCategoryCode": "5411",
                          "businessType": "CORPORATION",
                          "contactEmail": "m%s@example.com",
                          "contactPhone": "+966500000000",
                          "website": "https://example.com",
                          "address": "123 Test Street",
                          "city": "%s",
                          "state": "TestState",
                          "postalCode": "11564",
                          "country": "SA",
              "userId": %d
            }
            """.formatted(legalName, suffix, suffix, suffix, suffix, city == null ? "" : city, System.currentTimeMillis() % 100_000);
        Response resp = given().contentType(ContentType.JSON).body(body).when().post("/api/v1/merchants").then().statusCode(anyOf(is(200), is(201))).extract().response();
        String id = resp.path("data.id");
        Assert.assertNotNull(id, "Precondition failed: create merchant returned no id. Body: " + resp.asString());
        createdMerchantIds.add(id);
        return id;
    }

    private Response generateQr(String merchantId) {
        String body = """
            {
              "merchantId": "%s",
              "qrType": "STATIC"
            }
            """.formatted(merchantId);
        return given().contentType(ContentType.JSON).body(body).when().post("/api/v1/qr-codes").then().statusCode(anyOf(is(200), is(201))).extract().response();
    }

    // TC-001 - Merchant name exactly at 25-character limit is included in full in Tag 59
    @Test
    public void merchantNameAt25CharsIncludedInFull() {
        // exactly 25 chars
        String legalName = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        String merchantId = createMerchant(legalName, "Riyadh");
        Response qrResp = generateQr(merchantId);
        String qrData = qrResp.path("data.qrData");
        Assert.assertNotNull(qrData, "qrData was missing in response: " + qrResp.asString());
        Assert.assertTrue(qrData.contains(legalName), "Expected full 25-char merchant name in qrData. Body: " + qrResp.asString());
    }

    // TC-002 - Merchant name exceeding 25 characters is truncated to exactly 25 in Tag 59
    @Test
    public void merchantNameExceeding25CharsTruncatedTo25() {
        // 52 chars
        String longName = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
        String expectedPrefix = longName.substring(0, 25);
        String merchantId = createMerchant(longName, "Riyadh");
        Response qrResp = generateQr(merchantId);
        String qrData = qrResp.path("data.qrData");
        Assert.assertNotNull(qrData, "qrData was missing in response: " + qrResp.asString());
        Assert.assertTrue(qrData.contains(expectedPrefix), "Expected first 25 chars of merchant name in qrData. Body: " + qrResp.asString());
    }

    // TC-003 - Merchant city exactly at 15-character limit is included in full in Tag 60
    @Test
    public void merchantCityAt15CharsIncludedInFull() {
        // exactly 15 chars
        String city = "RiyadhCityName";
        String merchantId = createMerchant("Some Merchant", city);
        Response qrResp = generateQr(merchantId);
        String qrData = qrResp.path("data.qrData");
        Assert.assertNotNull(qrData, "qrData was missing in response: " + qrResp.asString());
        Assert.assertTrue(qrData.contains(city), "Expected full 15-char city in qrData. Body: " + qrResp.asString());
    }

    // TC-004 - Merchant city exceeding 15 characters is truncated to exactly 15 in Tag 60
    @Test
    public void merchantCityExceeding15CharsTruncatedTo15() {
        // 20 chars
        String city = "RiyadhCityNameExtra";
        String expectedPrefix = city.substring(0, 15);
        String merchantId = createMerchant("Some Merchant", city);
        Response qrResp = generateQr(merchantId);
        String qrData = qrResp.path("data.qrData");
        Assert.assertNotNull(qrData, "qrData was missing in response: " + qrResp.asString());
        Assert.assertTrue(qrData.contains(expectedPrefix), "Expected first 15 chars of city in qrData. Body: " + qrResp.asString());
    }

    // TC-005 - Null merchant city defaults to 'Riyadh' in Tag 60
    @Test
    public void nullMerchantCityDefaultsToRiyadh() {
        String suffix = String.valueOf(System.currentTimeMillis());
        // Build merchant WITHOUT city field set, then blank it.
        String body = """
                        {
                          "legalName": "NoCity Merchant",
                          "tradeName": "NoCity_%s",
                          "registrationNo": "CR-NC-%s",
                          "taxId": "TAX-NC-%s",
                          "merchantCategoryCode": "5411",
                          "businessType": "CORPORATION",
                          "contactEmail": "nc%s@example.com",
                          "contactPhone": "+966500000001",
                          "address": "456 Test Street",
                          "country": "SA",
              "userId": %d
            }
            """.formatted(suffix, suffix, suffix, suffix, System.currentTimeMillis() % 100_000);
        Response resp = given().contentType(ContentType.JSON).body(body).when().post("/api/v1/merchants").then().statusCode(anyOf(is(200), is(201))).extract().response();
        String merchantId = resp.path("data.id");
        Assert.assertNotNull(merchantId, "Precondition failed: create merchant returned no id. Body: " + resp.asString());
        createdMerchantIds.add(merchantId);
        Response qrResp = generateQr(merchantId);
        String qrData = qrResp.path("data.qrData");
        Assert.assertNotNull(qrData, "qrData was missing in response: " + qrResp.asString());
        Assert.assertTrue(qrData.contains("Riyadh"), "Expected default city 'Riyadh' in qrData. Body: " + qrResp.asString());
    }

    @AfterClass
    public void tearDown() {
        RestAssured.reset();
    }

    private String createMerchant2(String country, String mcc) {
        String merchantBody = """
                        {
                          "legalName": "Test Merchant",
                          "tradeName": "Test Store",
                          "registrationNo": "CR-%d",
                          "taxId": "TAX-%d",
                          "merchantCategoryCode": %s,
                          "businessType": "CORPORATION",
                          "contactEmail": "test%d@example.com",
                          "contactPhone": "+966501234567",
                          "address": "123 Test St",
                          "city": "Riyadh",
                          "state": "Riyadh Province",
                          "postalCode": "11564",
                          "country": %s,
              "userId": %d
            }
            """.formatted(System.currentTimeMillis(), System.currentTimeMillis(), mcc != null ? "\"" + mcc + "\"" : "null", System.currentTimeMillis(), country != null ? "\"" + country + "\"" : "null", System.currentTimeMillis() % 100_000);
        Response createResponse = given().contentType(ContentType.JSON).body(merchantBody).when().post("/api/v1/merchants").then().statusCode(anyOf(is(200), is(201))).extract().response();
        String merchantId = createResponse.path("data.id");
        Assert.assertNotNull(merchantId, "Precondition failed: no merchant id returned");
        return merchantId;
    }

    private String createSettlementAccount(String merchantId, String currency) {
        String accountBody = """
            {
              "accountName": "Test Account",
              "bankName": "Test Bank",
              "bankCode": "TEST",
              "branchCode": "001",
              "accountNumber": "1234567890",
              "iban": "SA0380000000608010167519",
              "currency": %s,
              "primary": true
            }
            """.formatted(currency != null ? "\"" + currency + "\"" : "null");
        Response accountResponse = given().contentType(ContentType.JSON).body(accountBody).when().post("/api/v1/merchants/{merchantId}/settlement-accounts", merchantId).then().statusCode(anyOf(is(200), is(201))).extract().response();
        return accountResponse.path("data.id");
    }

    private String generateQrCode(String merchantId) {
        String qrBody = """
            {
              "merchantId": "%s",
              "qrType": "STATIC"
            }
            """.formatted(merchantId);
        Response qrResponse = given().contentType(ContentType.JSON).body(qrBody).when().post("/api/v1/qr-codes").then().statusCode(anyOf(is(200), is(201))).extract().response();
        String qrData = qrResponse.path("data.qrData");
        Assert.assertNotNull(qrData, "QR data should not be null");
        return qrData;
    }

    private String extractTagValue(String qrData, String tag) {
        int index = qrData.indexOf(tag);
        if (index == -1)
            return null;
        int length = Integer.parseInt(qrData.substring(index + 2, index + 4));
        return qrData.substring(index + 4, index + 4 + length);
    }

    @Test
    public void nullCountryCodeDefaultsToSA() {
        String merchantId = createMerchant2(null, null);
        String qrData = generateQrCode(merchantId);
        String tag58 = extractTagValue(qrData, "58");
        Assert.assertEquals(tag58, "SA", "Tag 58 should default to SA");
    }

    @Test
    public void nullMCCDefaultsTo0000() {
        String merchantId = createMerchant2(null, null);
        String qrData = generateQrCode(merchantId);
        String tag52 = extractTagValue(qrData, "52");
        Assert.assertEquals(tag52, "0000", "Tag 52 should default to 0000");
    }

    @Test
    public void nullCurrencyDefaultsToSAR() {
        String merchantId = createMerchant2(null, null);
        String qrData = generateQrCode(merchantId);
        String tag53 = extractTagValue(qrData, "53");
        Assert.assertEquals(tag53, "682", "Tag 53 should default to 682 (SAR)");
    }

    @Test
    public void unrecognizedCurrencyDefaultsToSAR() {
        String merchantId = createMerchant2(null, null);
        createSettlementAccount(merchantId, "\"XYZ\"");
        String qrData = generateQrCode(merchantId);
        String tag53 = extractTagValue(qrData, "53");
        Assert.assertEquals(tag53, "682", "Tag 53 should default to 682 (SAR) for unrecognized currency");
    }

    @Test
    public void staticQRTypeUsesPIM11() {
        String merchantId = createMerchant2("\"SA\"", "\"5411\"");
        String qrData = generateQrCode(merchantId);
        String tag01 = extractTagValue(qrData, "01");
        Assert.assertEquals(tag01, "11", "Tag 01 should be 11 for static QR type");
    }

    private String merchantId;

    @Test
    public void TC_011_DynamicQrTypeUsesPointOfInitiationMethod12() {
        // Precondition: Create a merchant for QR code generation
        String createMerchantBody = """
                        {
                          "legalName": "Test Merchant for QR",
                          "tradeName": "QR Test Store",
                          "registrationNo": "CR-%d",
                          "taxId": "TAX-%d",
                          "merchantCategoryCode": "5411",
                          "businessType": "CORPORATION",
                          "contactEmail": "qrtest%d@example.com",
                          "contactPhone": "+966501234567",
                          "website": "https://www.qrtest.com",
                          "address": "Test Address",
                          "city": "Riyadh",
                          "state": "Riyadh Province",
                          "postalCode": "11564",
                          "country": "SA",
              "userId": %d
            }
            """.formatted(System.currentTimeMillis(), System.currentTimeMillis(), System.currentTimeMillis(), System.currentTimeMillis() % 100_000);
        Response merchantResponse = given().contentType(ContentType.JSON).body(createMerchantBody).when().post("/api/v1/merchants").then().statusCode(anyOf(is(200), is(201))).extract().response();
        merchantId = merchantResponse.path("data.id");
        Assert.assertNotNull(merchantId, "Precondition failed: no merchant id returned");
        // Test: Generate QR code with DYNAMIC type
        String qrCodeBody = """
            {
              "merchantId": "%s",
              "qrType": "DYNAMIC"
            }
            """.formatted(merchantId);
        String qrData = given().contentType(ContentType.JSON).body(qrCodeBody).when().post("/api/v1/qr-codes").then().statusCode(200).extract().path("data.qrData");
        Assert.assertNotNull(qrData, "QR data should not be null");
        Assert.assertTrue(qrData.contains("01"), "QR data should contain Tag 01");
        Assert.assertTrue(qrData.contains("12"), "QR data should contain Point of Initiation Method '12' for dynamic QR");
    }

    @Test
    public void TC_012_TlvLengthFieldZeroPaddedForSingleDigitLengths() {
        // Precondition: Create a merchant with short country code
        String createMerchantBody = """
                        {
                          "legalName": "Test Merchant for TLV Length",
                          "tradeName": "TLV Test Store",
                          "registrationNo": "CR-%d",
                          "taxId": "TAX-%d",
                          "merchantCategoryCode": "5411",
                          "businessType": "CORPORATION",
                          "contactEmail": "tlvtest%d@example.com",
                          "contactPhone": "+966501234568",
                          "website": "https://www.tlvtest.com",
                          "address": "Test Address",
                          "city": "Riyadh",
                          "state": "Riyadh Province",
                          "postalCode": "11564",
                          "country": "SA",
              "userId": %d
            }
            """.formatted(System.currentTimeMillis(), System.currentTimeMillis(), System.currentTimeMillis(), System.currentTimeMillis() % 100_000);
        Response merchantResponse = given().contentType(ContentType.JSON).body(createMerchantBody).when().post("/api/v1/merchants").then().statusCode(anyOf(is(200), is(201))).extract().response();
        String merchantId = merchantResponse.path("data.id");
        Assert.assertNotNull(merchantId, "Precondition failed: no merchant id returned");
        // Test: Generate QR code with STATIC type
        String qrCodeBody = """
            {
              "merchantId": "%s",
              "qrType": "STATIC"
            }
            """.formatted(merchantId);
        String qrData = given().contentType(ContentType.JSON).body(qrCodeBody).when().post("/api/v1/qr-codes").then().statusCode(200).extract().path("data.qrData");
        Assert.assertNotNull(qrData, "QR data should not be null");
        Assert.assertTrue(qrData.contains("58"), "QR data should contain Tag 58 (Country Code)");
        Assert.assertTrue(qrData.contains("02SA"), "QR data should contain Tag 58 with zero-padded length '02' followed by 'SA'");
    }

    @AfterClass
    public void cleanup2() {
        if (merchantId != null) {
            given().when().delete("/api/v1/merchants/{id}", merchantId);
        }
    }

    @Test
    public // TC-002 - Merchant name exceeding 25 characters is truncated to exactly 25 in Tag 59
    void merchantNameExceeding25CharactersTruncatedInTag59() {
        long ts = System.currentTimeMillis();
        // 52-character legal name
        String longName = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
        // Precondition: create a merchant with a name longer than 25 characters
        String merchantBody = """
                        {
                          "legalName": "%s",
                          "tradeName": "TradeName_%d",
                          "registrationNo": "REG-%d",
                          "taxId": "TAX-%d",
                          "merchantCategoryCode": "5411",
                          "businessType": "CORPORATION",
                          "contactEmail": "contact_%d@example.com",
                          "contactPhone": "+966501234567",
                          "website": "https://www.example.com",
                          "address": "123 Test Road",
                          "city": "Riyadh",
                          "state": "Riyadh Province",
                          "postalCode": "11564",
                          "country": "SA",
              "userId": %d
            }
            """.formatted(longName, ts, ts, ts, ts, System.currentTimeMillis() % 100_000);
        Response merchantResp = given().contentType(ContentType.JSON).body(merchantBody).when().post("/api/v1/merchants").then().statusCode(anyOf(is(200), is(201))).extract().response();
        Object idObj = merchantResp.path("data.id");
        if (idObj == null) {
            idObj = merchantResp.path("id");
        }
        Assert.assertNotNull(idObj, "Precondition failed: no merchant id returned. Body: " + merchantResp.asString());
        merchantId = idObj.toString();
        // Generate a STATIC QR code for this merchant
        String qrBody = """
            {
              "merchantId": "%s",
              "qrType": "STATIC"
            }
            """.formatted(merchantId);
        Response qrResp = given().contentType(ContentType.JSON).body(qrBody).when().post("/api/v1/qr-codes").then().statusCode(anyOf(is(200), is(201))).extract().response();
        String qrData = qrResp.path("data.qrData");
        Assert.assertNotNull(qrData, "Expected qrData in response. Body: " + qrResp.asString());
        // Expected: first 25 characters of the merchant name
        String expectedTruncated = longName.substring(0, 25);
        Assert.assertTrue(qrData.contains(expectedTruncated), "Expected qrData to contain truncated name '" + expectedTruncated + "'. qrData: " + qrData);
    }

    @AfterClass
    public void cleanup3() {
        if (merchantId != null) {
            given().when().delete("/api/v1/merchants/{id}", merchantId);
        }
    }

    @AfterClass
    public void cleanup4() {
        // No DELETE available in the endpoint list for QR codes.
    }

    /**
     * TC-004: Merchant city exceeding 15 characters is truncated to exactly 15 in Tag 60.
     * Precondition: A merchant must exist with a city longer than 15 characters.
     * The create merchant endpoint does not document an explicit "city" bound beyond what the
     * UpdateMerchantRequest shows (no documented maxLength), so we set it to exactly the 20-char
     * value the case uses and verify the QR's Tag 60 truncates to 15.
     */
    @Test
    public void merchantCityExceeding15CharactersIsTruncatedTo15InTag60() {
        long ts = System.currentTimeMillis();
        // Precondition: create a merchant with a 20-character city name.
        String merchantBody = """
                        {
                          "legalName": "TC004 Legal %d",
                          "tradeName": "TC004 Trade %d",
                          "registrationNo": "CR-TC004-%d",
                          "taxId": "TAX-TC004-%d",
                          "merchantCategoryCode": "5411",
                          "businessType": "CORPORATION",
                          "contactEmail": "tc004_%d@example.com",
                          "contactPhone": "+966501234001",
                          "city": "RiyadhCityNameExtra",
                          "country": "SA",
              "userId": %d
            }
            """.formatted(ts, ts, ts, ts, ts, System.currentTimeMillis() % 100_000);
        Response merchantResp = given().contentType(ContentType.JSON).body(merchantBody).when().post("/api/v1/merchants").then().statusCode(anyOf(is(200), is(201))).extract().response();
        String merchantId = merchantResp.path("data.id") != null ? merchantResp.path("data.id") : merchantResp.path("id");
        Assert.assertNotNull(merchantId, "Precondition failed: create merchant returned no id. Body: " + merchantResp.asString());
        // The case's own assertion: generate a QR and inspect qrData.
        String qrBody = """
            {
              "merchantId": "%s",
              "qrType": "STATIC"
            }
            """.formatted(merchantId);
        Response qrResp = given().contentType(ContentType.JSON).body(qrBody).when().post("/api/v1/qr-codes").then().statusCode(anyOf(is(200), is(201))).extract().response();
        String qrData = qrResp.path("data.qrData");
        Assert.assertNotNull(qrData, "qrData missing in response: " + qrResp.asString());
        // Tag 60 in EMV QR is encoded as "60" + length(2 digits) + value.
        // Find Tag 60 and extract its value; the truncated city should be the first 15 chars.
        // "RiyadhCityName" - 15 chars
        String expectedTruncated = "RiyadhCityNameE".substring(0, 15);
        Assert.assertTrue(qrData.contains(expectedTruncated), "Expected Tag 60 to contain truncated city '" + expectedTruncated + "'. qrData: " + qrData);
        // Verify it does NOT include the 16th character from the original city.
        Assert.assertFalse(qrData.contains("RiyadhCityNameEx"), "qrData should not contain the un-truncated city. qrData: " + qrData);
    }

    /**
     * TC-005: Null merchant city defaults to 'Riyadh' in Tag 60.
     * Precondition: a merchant must exist with no city set.
     * The CreateMerchantRequest has city as a non-required field, so omitting it
     * (or sending an empty string) should leave the merchant with a null/blank city.
     */
    @Test
    public void nullMerchantCityDefaultsToRiyadhInTag60() {
        long ts = System.currentTimeMillis();
        // Precondition: create a merchant with no city.
        String merchantBody = """
                        {
                          "legalName": "TC005 Legal %d",
                          "tradeName": "TC005 Trade %d",
                          "registrationNo": "CR-TC005-%d",
                          "taxId": "TAX-TC005-%d",
                          "merchantCategoryCode": "5411",
                          "businessType": "CORPORATION",
                          "contactEmail": "tc005_%d@example.com",
                          "contactPhone": "+966501234002",
                          "country": "SA",
              "userId": %d
            }
            """.formatted(ts, ts, ts, ts, ts, System.currentTimeMillis() % 100_000);
        Response merchantResp = given().contentType(ContentType.JSON).body(merchantBody).when().post("/api/v1/merchants").then().statusCode(anyOf(is(200), is(201))).extract().response();
        String merchantId = merchantResp.path("data.id") != null ? merchantResp.path("data.id") : merchantResp.path("id");
        Assert.assertNotNull(merchantId, "Precondition failed: create merchant returned no id. Body: " + merchantResp.asString());
        // The case's own assertion: generate a QR and verify Tag 60 default 'Riyadh'.
        String qrBody = """
            {
              "merchantId": "%s",
              "qrType": "STATIC"
            }
            """.formatted(merchantId);
        Response qrResp = given().contentType(ContentType.JSON).body(qrBody).when().post("/api/v1/qr-codes").then().statusCode(anyOf(is(200), is(201))).extract().response();
        String qrData = qrResp.path("data.qrData");
        Assert.assertNotNull(qrData, "qrData missing in response: " + qrResp.asString());
        Assert.assertTrue(qrData.contains("Riyadh"), "Expected Tag 60 to contain default 'Riyadh'. qrData: " + qrData);
    }

    // TC-006 - Null country code defaults to 'SA' in Tag 58
    @Test
    public void nullCountryCodeDefaultsToSAInTag58() {
        // Precondition: create a merchant with no country code specified (null/omitted)
        long ts = System.currentTimeMillis();
        String createMerchantBody = """
                        {
                          "legalName": "Null Country Merchant %d",
                          "tradeName": "NC Trade %d",
                          "registrationNo": "CR-NULL-%d",
                          "taxId": "TAX-NULL-%d",
                          "merchantCategoryCode": "5411",
                          "businessType": "CORPORATION",
                          "contactEmail": "nullcountry%d@example.com",
                          "contactPhone": "+966500000001",
                          "address": "123 Test Street",
                          "city": "Riyadh",
                          "state": "Riyadh Province",
                          "postalCode": "11564",
              "userId": %d
            }
            """.formatted(ts, ts, ts, ts, ts, System.currentTimeMillis() % 100_000);
        Response merchantResp = given().contentType(ContentType.JSON).body(createMerchantBody).when().post("/api/v1/merchants").then().statusCode(anyOf(is(200), is(201))).extract().response();
        merchantId = merchantResp.path("data.id");
        Assert.assertNotNull(merchantId, "Precondition failed: merchant create returned no id. Body: " + merchantResp.asString());
        // Verify the persisted merchant has no country code (per preconditions)
        String persistedCountry = merchantResp.path("data.country");
        Assert.assertTrue(persistedCountry == null || persistedCountry.isEmpty(), "Precondition failed: expected null/empty country, got: " + persistedCountry);
        // The actual assertion: POST /api/v1/qr-codes and observe qrData contains Tag 58 with 'SA'
        String qrBody = """
            {
              "merchantId": "%s",
              "qrType": "STATIC"
            }
            """.formatted(merchantId);
        Response qrResp = given().contentType(ContentType.JSON).body(qrBody).when().post("/api/v1/qr-codes").then().statusCode(anyOf(is(200), is(201))).extract().response();
        String qrData = qrResp.path("data.qrData");
        Assert.assertNotNull(qrData, "qrData missing from response. Body: " + qrResp.asString());
        // EMV Tag 58 is "Country Code" (2 chars). In TLV, tag '58' (hex 3538) followed by length 02 and the 2-char value.
        // Look for Tag 58 (encoded in ASCII as "58") with length "02" and value "SA".
        Assert.assertTrue(qrData.contains("5802SA"), "Expected Tag 58 to contain 'SA' as default country code. qrData: " + qrData);
    }

    @AfterClass
    public void tearDown2() {
        // No DELETE endpoint for merchants in the listed operations - skip cleanup
    }

    // TC-007
    @Test
    public void nullMccDefaultsToZeroZeroZeroZeroInTag52() {
        // Precondition: create a merchant with no merchant category code (null MCC)
        String merchantBody = """
                        {
                          "legalName": "Test Merchant %d",
                          "tradeName": "Test Store %d",
                          "registrationNo": "CR-%d",
                          "businessType": "CORPORATION",
              "userId": %d
            }
            """.formatted(System.currentTimeMillis(), System.currentTimeMillis(), System.currentTimeMillis(), System.currentTimeMillis() % 100_000);
        String merchantId = given().contentType(ContentType.JSON).body(merchantBody).when().post("/api/v1/merchants").then().statusCode(anyOf(is(200), is(201))).extract().path("data.id");
        Assert.assertNotNull(merchantId, "Precondition failed: no merchant id returned");
        // Generate a QR code for the merchant with null MCC
        String qrBody = """
            {
              "merchantId": "%s",
              "qrType": "STATIC"
            }
            """.formatted(merchantId);
        given().contentType(ContentType.JSON).body(qrBody).when().post("/api/v1/qr-codes").then().statusCode(anyOf(is(200), is(201))).body("data.qrData", containsString("0000"));
    }

    @AfterClass
    public void tearDown3() {
        // No DELETE endpoints exist for merchants or QR codes in the provided endpoint list;
        // nothing to clean up.
    }

    // TC-001 - Merchant name exactly at 25-character limit is included in full in Tag 59
    @Test
    public void merchantNameExactly25CharactersInTag59() {
        // exactly 25 chars
        String merchantName = "ABCDEFGHIJKLMNOPQRSTUVWXY";
        String createMerchantBody = """
                        {
                          "legalName": "%s",
                          "tradeName": "Test Trade",
                          "registrationNo": "CR-%d",
                          "businessType": "CORPORATION",
                          "city": "Riyadh",
              "userId": %d
            }
            """.formatted(merchantName, System.currentTimeMillis(), System.currentTimeMillis() % 100_000);
        Response merchantResponse = given().contentType(ContentType.JSON).body(createMerchantBody).when().post("/api/v1/merchants").then().statusCode(anyOf(is(200), is(201))).extract().response();
        String merchantId = merchantResponse.path("data.id") != null ? merchantResponse.path("data.id") : merchantResponse.path("id");
        Assert.assertNotNull(merchantId, "Precondition failed: Merchant ID is null");
        String generateQrBody = """
            {
              "merchantId": "%s",
              "qrType": "STATIC"
            }
            """.formatted(merchantId);
        given().contentType(ContentType.JSON).body(generateQrBody).when().post("/api/v1/qr-codes").then().statusCode(anyOf(is(200), is(201))).body("data.qrData", containsString(merchantName));
    }

    // TC-002 - Merchant name exceeding 25 characters is truncated to exactly 25 in Tag 59
    @Test
    public void merchantNameExceeding25CharactersTruncatedInTag592() {
        // 52 chars
        String merchantName = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
        String expectedTruncated = merchantName.substring(0, 25);
        String createMerchantBody = """
                        {
                          "legalName": "%s",
                          "tradeName": "Test Trade",
                          "registrationNo": "CR-%d",
                          "businessType": "CORPORATION",
                          "city": "Riyadh",
              "userId": %d
            }
            """.formatted(merchantName, System.currentTimeMillis(), System.currentTimeMillis() % 100_000);
        Response merchantResponse = given().contentType(ContentType.JSON).body(createMerchantBody).when().post("/api/v1/merchants").then().statusCode(anyOf(is(200), is(201))).extract().response();
        String merchantId = merchantResponse.path("data.id") != null ? merchantResponse.path("data.id") : merchantResponse.path("id");
        Assert.assertNotNull(merchantId, "Precondition failed: Merchant ID is null");
        String generateQrBody = """
            {
              "merchantId": "%s",
              "qrType": "STATIC"
            }
            """.formatted(merchantId);
        given().contentType(ContentType.JSON).body(generateQrBody).when().post("/api/v1/qr-codes").then().statusCode(anyOf(is(200), is(201))).body("data.qrData", containsString(expectedTruncated));
    }

    // TC-003 - Merchant city exactly at 15-character limit is included in full in Tag 60
    @Test
    public void merchantCityExactly15CharactersInTag60() {
        // exactly 15 chars
        String cityName = "RiyadhCityName";
        String createMerchantBody = """
                        {
                          "legalName": "Valid Legal Name",
                          "tradeName": "Test Trade",
                          "registrationNo": "CR-%d",
                          "businessType": "CORPORATION",
                          "city": "%s",
              "userId": %d
            }
            """.formatted(System.currentTimeMillis(), cityName, System.currentTimeMillis() % 100_000);
        Response merchantResponse = given().contentType(ContentType.JSON).body(createMerchantBody).when().post("/api/v1/merchants").then().statusCode(anyOf(is(200), is(201))).extract().response();
        String merchantId = merchantResponse.path("data.id") != null ? merchantResponse.path("data.id") : merchantResponse.path("id");
        Assert.assertNotNull(merchantId, "Precondition failed: Merchant ID is null");
        String generateQrBody = """
            {
              "merchantId": "%s",
              "qrType": "STATIC"
            }
            """.formatted(merchantId);
        given().contentType(ContentType.JSON).body(generateQrBody).when().post("/api/v1/qr-codes").then().statusCode(anyOf(is(200), is(201))).body("data.qrData", containsString(cityName));
    }

    // TC-004 - Merchant city exceeding 15 characters is truncated to exactly 15 in Tag 60
    @Test
    public void merchantCityExceeding15CharactersTruncatedInTag60() {
        // 20 chars
        String cityName = "RiyadhCityNameExtra";
        String expectedTruncated = cityName.substring(0, 15);
        String createMerchantBody = """
                        {
                          "legalName": "Valid Legal Name",
                          "tradeName": "Test Trade",
                          "registrationNo": "CR-%d",
                          "businessType": "CORPORATION",
                          "city": "%s",
              "userId": %d
            }
            """.formatted(System.currentTimeMillis(), cityName, System.currentTimeMillis() % 100_000);
        Response merchantResponse = given().contentType(ContentType.JSON).body(createMerchantBody).when().post("/api/v1/merchants").then().statusCode(anyOf(is(200), is(201))).extract().response();
        String merchantId = merchantResponse.path("data.id") != null ? merchantResponse.path("data.id") : merchantResponse.path("id");
        Assert.assertNotNull(merchantId, "Precondition failed: Merchant ID is null");
        String generateQrBody = """
            {
              "merchantId": "%s",
              "qrType": "STATIC"
            }
            """.formatted(merchantId);
        given().contentType(ContentType.JSON).body(generateQrBody).when().post("/api/v1/qr-codes").then().statusCode(anyOf(is(200), is(201))).body("data.qrData", containsString(expectedTruncated));
    }

    // TC-005 - Null merchant city defaults to 'Riyadh' in Tag 60
    @Test
    public void nullMerchantCityDefaultsToRiyadhInTag602() {
        String createMerchantBody = """
                        {
                          "legalName": "Valid Legal Name",
                          "tradeName": "Test Trade",
                          "registrationNo": "CR-%d",
                          "businessType": "CORPORATION",
              "userId": %d
            }
            """.formatted(System.currentTimeMillis(), System.currentTimeMillis() % 100_000);
        Response merchantResponse = given().contentType(ContentType.JSON).body(createMerchantBody).when().post("/api/v1/merchants").then().statusCode(anyOf(is(200), is(201))).extract().response();
        String merchantId = merchantResponse.path("data.id") != null ? merchantResponse.path("data.id") : merchantResponse.path("id");
        Assert.assertNotNull(merchantId, "Precondition failed: Merchant ID is null");
        String generateQrBody = """
            {
              "merchantId": "%s",
              "qrType": "STATIC"
            }
            """.formatted(merchantId);
        given().contentType(ContentType.JSON).body(generateQrBody).when().post("/api/v1/qr-codes").then().statusCode(anyOf(is(200), is(201))).body("data.qrData", containsString("Riyadh"));
    }

    // TC-006
    @Test
    public void testNullCountryCodeDefaultsToSA() {
        long timestamp = System.currentTimeMillis();
        String createMerchantPayload = """
                        {
                          "legalName": "Null Country Merchant LLC",
                          "tradeName": "Null Country Store",
                          "registrationNo": "CR-%d",
                          "businessType": "CORPORATION",
              "userId": %d
            }
            """.formatted(timestamp, System.currentTimeMillis() % 100_000);
        Response merchantResp = given().contentType(ContentType.JSON).body(createMerchantPayload).when().post("/api/v1/merchants").then().statusCode(anyOf(is(200), is(201))).extract().response();
        String merchantId = merchantResp.path("data.id") != null ? merchantResp.path("data.id") : merchantResp.path("id");
        Assert.assertNotNull(merchantId, "Precondition failed: Merchant creation failed");
        String generateQrPayload = """
            {
              "merchantId": "%s",
              "qrType": "STATIC"
            }
            """.formatted(merchantId);
        given().contentType(ContentType.JSON).body(generateQrPayload).when().post("/api/v1/qr-codes").then().statusCode(anyOf(is(200), is(201))).body("data.qrData", containsString("SA"));
    }

    // TC-008
    @Test
    public void testNullCurrencyDefaultsToSAR682() {
        long timestamp = System.currentTimeMillis();
        String createMerchantPayload = """
                        {
                          "legalName": "Null Currency Merchant LLC",
                          "tradeName": "Null Currency Store",
                          "registrationNo": "CR-%d",
                          "businessType": "CORPORATION",
              "userId": %d
            }
            """.formatted(timestamp, System.currentTimeMillis() % 100_000);
        Response merchantResp = given().contentType(ContentType.JSON).body(createMerchantPayload).when().post("/api/v1/merchants").then().statusCode(anyOf(is(200), is(201))).extract().response();
        String merchantId = merchantResp.path("data.id") != null ? merchantResp.path("data.id") : merchantResp.path("id");
        Assert.assertNotNull(merchantId, "Precondition failed: Merchant creation failed");
        String generateQrPayload = """
            {
              "merchantId": "%s",
              "qrType": "STATIC"
            }
            """.formatted(merchantId);
        given().contentType(ContentType.JSON).body(generateQrPayload).when().post("/api/v1/qr-codes").then().statusCode(anyOf(is(200), is(201))).body("data.qrData", containsString("682"));
    }

    // TC-009
    @Test
    public void testUnrecognizedCurrencyCodeDefaultsToSAR682() {
        long timestamp = System.currentTimeMillis();
        String createMerchantPayload = """
                        {
                          "legalName": "Unrecognized Currency Merchant LLC",
                          "tradeName": "Unrecognized Currency Store",
                          "registrationNo": "CR-%d",
                          "businessType": "CORPORATION",
              "userId": %d
            }
            """.formatted(timestamp, System.currentTimeMillis() % 100_000);
        Response merchantResp = given().contentType(ContentType.JSON).body(createMerchantPayload).when().post("/api/v1/merchants").then().statusCode(anyOf(is(200), is(201))).extract().response();
        String merchantId = merchantResp.path("data.id") != null ? merchantResp.path("data.id") : merchantResp.path("id");
        Assert.assertNotNull(merchantId, "Precondition failed: Merchant creation failed");
        String generateQrPayload = """
            {
              "merchantId": "%s",
              "qrType": "STATIC"
            }
            """.formatted(merchantId);
        given().contentType(ContentType.JSON).body(generateQrPayload).when().post("/api/v1/qr-codes").then().statusCode(anyOf(is(200), is(201))).body("data.qrData", containsString("682"));
    }

    // TC-010
    @Test
    public void testStaticQrTypeUsesPointOfInitiationMethod11() {
        long timestamp = System.currentTimeMillis();
        String createMerchantPayload = """
                        {
                          "legalName": "Static QR Merchant LLC",
                          "tradeName": "Static QR Store",
                          "registrationNo": "CR-%d",
                          "businessType": "CORPORATION",
              "userId": %d
            }
            """.formatted(timestamp, System.currentTimeMillis() % 100_000);
        Response merchantResp = given().contentType(ContentType.JSON).body(createMerchantPayload).when().post("/api/v1/merchants").then().statusCode(anyOf(is(200), is(201))).extract().response();
        String merchantId = merchantResp.path("data.id") != null ? merchantResp.path("data.id") : merchantResp.path("id");
        Assert.assertNotNull(merchantId, "Precondition failed: Merchant creation failed");
        String generateQrPayload = """
            {
              "merchantId": "%s",
              "qrType": "STATIC"
            }
            """.formatted(merchantId);
        given().contentType(ContentType.JSON).body(generateQrPayload).when().post("/api/v1/qr-codes").then().statusCode(anyOf(is(200), is(201))).body("data.qrType", equalTo("STATIC")).body("data.qrData", containsString("11"));
    }

    // TC-011
    @Test
    public void testDynamicQrTypeUsesPointOfInitiationMethod12() {
        long timestamp = System.currentTimeMillis();
        String createMerchantPayload = """
                        {
                          "legalName": "Dynamic QR Merchant LLC",
                          "tradeName": "Dynamic QR Store",
                          "registrationNo": "CR-%d",
                          "businessType": "CORPORATION",
              "userId": %d
            }
            """.formatted(timestamp, System.currentTimeMillis() % 100_000);
        Response merchantResp = given().contentType(ContentType.JSON).body(createMerchantPayload).when().post("/api/v1/merchants").then().statusCode(anyOf(is(200), is(201))).extract().response();
        String merchantId = merchantResp.path("data.id") != null ? merchantResp.path("data.id") : merchantResp.path("id");
        Assert.assertNotNull(merchantId, "Precondition failed: Merchant creation failed");
        String generateQrPayload = """
            {
              "merchantId": "%s",
              "qrType": "DYNAMIC"
            }
            """.formatted(merchantId);
        given().contentType(ContentType.JSON).body(generateQrPayload).when().post("/api/v1/qr-codes").then().statusCode(anyOf(is(200), is(201))).body("data.qrType", equalTo("DYNAMIC")).body("data.qrData", containsString("12"));
    }

    private String createMerchant3(String legalName, String country) {
        long timestamp = System.currentTimeMillis();
        String body = """
                        {
                          "legalName": "%s",
                          "tradeName": "Trade_%d",
                          "registrationNo": "CR-%d",
                          "businessType": "CORPORATION",
                          "country": "%s",
              "userId": %d
            }
            """.formatted(legalName, timestamp, timestamp, country, System.currentTimeMillis() % 100_000);
        Response response = given().contentType(ContentType.JSON).body(body).when().post("/api/v1/merchants").then().statusCode(anyOf(is(200), is(201))).extract().response();
        String id = response.path("data.id") != null ? response.path("data.id") : response.path("id");
        Assert.assertNotNull(id, "Precondition failed: Merchant creation failed to return ID");
        return id;
    }

    // TC-012
    @Test
    public void tlvLengthFieldIsZeroPaddedTo2DigitsForSingleDigitLengths() {
        String merchantId = createMerchant3("Test Merchant", "SA");
        String qrRequestBody = """
            {
              "merchantId": "%s",
              "qrType": "STATIC"
            }
            """.formatted(merchantId);
        given().contentType(ContentType.JSON).body(qrRequestBody).when().post("/api/v1/qr-codes").then().statusCode(anyOf(is(200), is(201))).body("data.qrData", containsString("5802SA"));
    }

    // TC-013
    @Test
    public void crc16ChecksumIsAppendedAsTag63With4CharacterHexValue() {
        String merchantId = createMerchant3("Test Merchant", "SA");
        String qrRequestBody = """
            {
              "merchantId": "%s",
              "qrType": "STATIC"
            }
            """.formatted(merchantId);
        given().contentType(ContentType.JSON).body(qrRequestBody).when().post("/api/v1/qr-codes").then().statusCode(anyOf(is(200), is(201))).body("data.qrData", matchesPattern(".*6304[0-9A-F]{4}$"));
    }

    // TC-014
    @Test
    public void multiByteUtf8CharactersInMerchantNameAreCountedByBytesNotCharactersForTruncation() {
        String legalName = "商户名称测试";
        String merchantId = createMerchant3(legalName, "SA");
        String qrRequestBody = """
            {
              "merchantId": "%s",
              "qrType": "STATIC"
            }
            """.formatted(merchantId);
        given().contentType(ContentType.JSON).body(qrRequestBody).when().post("/api/v1/qr-codes").then().statusCode(anyOf(is(200), is(201))).body("data.qrData", containsString("5918" + legalName));
    }

    // TC-015
    @Test
    public void multiByteUtf8MerchantNameExceeding25BytesIsTruncatedByByteCountInTag59() {
        String legalName = "商户名称测试商户名称测试商";
        String merchantId = createMerchant3(legalName, "SA");
        String qrRequestBody = """
            {
              "merchantId": "%s",
              "qrType": "STATIC"
            }
            """.formatted(merchantId);
        Response response = given().contentType(ContentType.JSON).body(qrRequestBody).when().post("/api/v1/qr-codes").then().statusCode(anyOf(is(200), is(201))).extract().response();
        String qrData = response.path("data.qrData");
        Assert.assertNotNull(qrData, "qrData should not be null");
        Assert.assertTrue(qrData.contains("59"), "qrData should contain Tag 59");
        int tag59Index = qrData.indexOf("59");
        String lengthStr = qrData.substring(tag59Index + 2, tag59Index + 4);
        int byteLength = Integer.parseInt(lengthStr);
        Assert.assertTrue(byteLength <= 25, "Tag 59 length in bytes should be at most 25, but was: " + byteLength);
    }

}
