package com.company.aiqa.generated;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;
import static org.testng.Assert.*;

/**
 * Automated API tests for commit cba2550d420e29f8bf6ee586e4e8c8fdddcc4128.
 * Generated by ai-qa-platform from that commit's manual test cases.
 */
public class AutomationTest_cba2550d420e29f8bf6ee586e4e8c8fdddcc4128 {

    @BeforeClass
    public void setup() {
        RestAssured.baseURI = System.getProperty("baseUri", "http://169.58.37.242:8007/mms");
    }

    /**
     * Test Case ID: TC-001
     * Generate a Bangla QR code with all required fields and minimal optional fields
     */
    @Test
    public void generateBanglaQrWithRequiredFields() {
        String requestBody = """
            {
              "qrVersion": "01",
              "format": "01",
              "method": "11",
              "merchantCategoryCode": "5411",
              "merchantId": "MERCHANT12345",
              "merchantPan": "1234567890123456",
              "merchantAccountNo": "1234567890",
              "merchantName": "Test Merchant",
              "merchantCity": "Dhaka",
              "merchantCountryCode": "BD",
              "trxCurrencyCode": "050",
              "terminalId": "TERM12345678",
              "acquirerInstitutionType": "BANK",
              "acquirerId": "ACQ123"
            }
            """;
        given().contentType(ContentType.JSON).body(requestBody).when().post("/generate-bangla-qr").then().statusCode(200).body("qrData", not(emptyString())).body("signature", not(emptyString())).body("crc", not(emptyString())).body("crc", hasLength(4));
    }

    /**
     * Test Case ID: TC-002
     * Generate a Bangla QR code with all optional fields populated
     */
    @Test
    public void generateBanglaQrWithAllOptionalFields() {
        String requestBody = """
            {
              "qrVersion": "01",
              "format": "01",
              "method": "11",
              "accountType": "PERSONAL",
              "merchantCategoryCode": "5411",
              "merchantId": "MERCHANT12345",
              "merchantPan": "1234567890123456",
              "merchantAccountNo": "1234567890",
              "merchantName": "Test Merchant",
              "merchantCity": "Dhaka",
              "merchantCountryCode": "BD",
              "trxCurrencyCode": "050",
              "notificationMobileNo": "8801712345678",
              "terminalId": "TERM12345678",
              "purposeOfTrx": "Bill Payment",
              "acquirerInstitutionType": "BANK",
              "acquirerId": "ACQ123",
              "merchantLogo": "logo_base64_string"
            }
            """;
        given().contentType(ContentType.JSON).body(requestBody).when().post("/generate-bangla-qr").then().statusCode(200).body("qrData", not(emptyString())).body("signature", not(emptyString())).body("crc", not(emptyString())).body("crc", hasLength(4));
    }

    /**
     * Test Case ID: TC-003
     * Generate a Bangla QR code with optional fields left empty
     */
    @Test
    public void generateBanglaQrWithOptionalFieldsEmpty() {
        String requestBody = """
            {
              "qrVersion": "01",
              "format": "01",
              "method": "11",
              "merchantCategoryCode": "5411",
              "merchantId": "MERCHANT12345",
              "merchantPan": "1234567890123456",
              "merchantAccountNo": "1234567890",
              "merchantName": "Test Merchant",
              "merchantCity": "Dhaka",
              "merchantCountryCode": "BD",
              "trxCurrencyCode": "050",
              "terminalId": "TERM12345678",
              "acquirerInstitutionType": "BANK",
              "acquirerId": "ACQ123"
            }
            """;
        given().contentType(ContentType.JSON).body(requestBody).when().post("/generate-bangla-qr").then().statusCode(200).body("qrData", not(emptyString())).body("signature", not(emptyString())).body("crc", not(emptyString())).body("crc", hasLength(4));
    }

    /**
     * Test Case ID: TC-004
     * Generate Bangla QR with merchant name exactly 99 bytes (maximum allowed length)
     */
    @Test
    public void generateBanglaQrWithMerchantNameMaxLength() {
        String requestBody = """
            {
              "qrVersion": "01",
              "format": "01",
              "method": "11",
              "accountType": "00",
              "merchantCategoryCode": "4111",
              "merchantId": "MERCHANT123",
              "merchantPan": "1234567890123456",
              "merchantAccountNo": "ACCT1234567890",
              "merchantName": "ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJ",
              "merchantCity": "DHAKA",
              "merchantCountryCode": "BD",
              "trxCurrencyCode": "050",
              "notificationMobileNo": "8801712345678",
              "terminalId": "TERM12345678",
              "purposeOfTrx": "00",
              "acquirerInstitutionType": "01",
              "acquirerId": "ACQ1234567890"
            }
            """;
        given().contentType(ContentType.JSON).body(requestBody).when().post("/generate-bangla-qr").then().statusCode(200).body("qrData", not(emptyString())).body("signature", not(emptyString())).body("crc", not(emptyString())).body("crc", hasLength(4));
    }

    /**
     * Test Case ID: TC-005
     * Generate Bangla QR with merchant name 100 bytes (one byte over maximum allowed length)
     */
    @Test
    public void generateBanglaQrWithMerchantNameOverMaxLength() {
        String requestBody = """
            {
              "qrVersion": "01",
              "format": "01",
              "method": "11",
              "accountType": "00",
              "merchantCategoryCode": "4111",
              "merchantId": "MERCHANT123",
              "merchantPan": "1234567890123456",
              "merchantAccountNo": "ACCT1234567890",
              "merchantName": "ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJK",
              "merchantCity": "DHAKA",
              "merchantCountryCode": "BD",
              "trxCurrencyCode": "050",
              "notificationMobileNo": "8801712345678",
              "terminalId": "TERM12345678",
              "purposeOfTrx": "00",
              "acquirerInstitutionType": "01",
              "acquirerId": "ACQ1234567890"
            }
            """;
        given().contentType(ContentType.JSON).body(requestBody).when().post("/generate-bangla-qr").then().statusCode(400).body("message", containsString("EMV QR data element length cannot exceed 99 bytes"));
    }

    /**
     * Test Case ID: TC-006
     * Generate Bangla QR with empty merchant name (minimum length boundary)
     */
    @Test
    public void generateBanglaQrWithEmptyMerchantName() {
        String requestBody = """
            {
              "qrVersion": "01",
              "format": "01",
              "method": "11",
              "accountType": "00",
              "merchantCategoryCode": "4111",
              "merchantId": "MERCHANT123",
              "merchantPan": "1234567890123456",
              "merchantAccountNo": "ACCT1234567890",
              "merchantName": "",
              "merchantCity": "DHAKA",
              "merchantCountryCode": "BD",
              "trxCurrencyCode": "050",
              "notificationMobileNo": "8801712345678",
              "terminalId": "TERM12345678",
              "purposeOfTrx": "00",
              "acquirerInstitutionType": "01",
              "acquirerId": "ACQ1234567890"
            }
            """;
        given().contentType(ContentType.JSON).body(requestBody).when().post("/generate-bangla-qr").then().statusCode(400).body("message", containsString("merchantName must not be blank"));
    }

    /**
     * Test Case ID: TC-007
     * Generate Bangla QR with signature length exactly matching configured signatureLength (maximum allowed)
     * Note: This test assumes the system is configured with qr.bangla.signatureLength=64
     */
    @Test
    public void generateBanglaQrWithExactSignatureLength() {
        String requestBody = """
            {
              "qrVersion": "01",
              "format": "01",
              "method": "11",
              "accountType": "00",
              "merchantCategoryCode": "4111",
              "merchantId": "MERCHANT123",
              "merchantPan": "1234567890123456",
              "merchantAccountNo": "ACCT1234567890",
              "merchantName": "Test Merchant",
              "merchantCity": "DHAKA",
              "merchantCountryCode": "BD",
              "trxCurrencyCode": "050",
              "notificationMobileNo": "8801712345678",
              "terminalId": "TERM12345678",
              "purposeOfTrx": "00",
              "acquirerInstitutionType": "01",
              "acquirerId": "ACQ1234567890"
            }
            """;
        given().contentType(ContentType.JSON).body(requestBody).when().post("/generate-bangla-qr").then().statusCode(200).body("signature", notNullValue()).body("signature.length()", equalTo(64)).body("qrData", notNullValue()).body("crc", notNullValue());
    }

    /**
     * Test Case ID: TC-008
     * Generate Bangla QR with signature length less than configured signatureLength (invalid boundary)
     * Note: This test assumes the system is configured with qr.bangla.signatureLength=65
     */
    @Test
    public void generateBanglaQrWithInvalidSignatureLength() {
        String requestBody = """
            {
              "qrVersion": "01",
              "format": "01",
              "method": "11",
              "accountType": "00",
              "merchantCategoryCode": "4111",
              "merchantId": "MERCHANT123",
              "merchantPan": "1234567890123456",
              "merchantAccountNo": "ACCT1234567890",
              "merchantName": "Test Merchant",
              "merchantCity": "DHAKA",
              "merchantCountryCode": "BD",
              "trxCurrencyCode": "050",
              "notificationMobileNo": "8801712345678",
              "terminalId": "TERM12345678",
              "purposeOfTrx": "00",
              "acquirerInstitutionType": "01",
              "acquirerId": "ACQ1234567890"
            }
            """;
        given().contentType(ContentType.JSON).body(requestBody).when().post("/generate-bangla-qr").then().statusCode(500).body("message", containsString("generated signature length is less than the configured length"));
    }

    /**
     * Test Case ID: TC-009
     * Generate Bangla QR with notificationMobileNo exactly 1 character (minimum non-empty length for optional field)
     */
    @Test
    public void generateBanglaQrWithMinNotificationMobileNo() {
        String requestBody = """
            {
              "qrVersion": "01",
              "format": "01",
              "method": "11",
              "accountType": "00",
              "merchantCategoryCode": "4111",
              "merchantId": "MERCHANT123",
              "merchantPan": "1234567890123456",
              "merchantAccountNo": "ACCT1234567890",
              "merchantName": "Test Merchant",
              "merchantCity": "DHAKA",
              "merchantCountryCode": "BD",
              "trxCurrencyCode": "050",
              "notificationMobileNo": "1",
              "terminalId": "TERM12345678",
              "purposeOfTrx": "00",
              "acquirerInstitutionType": "01",
              "acquirerId": "ACQ1234567890"
            }
            """;
        given().contentType(ContentType.JSON).body(requestBody).when().post("/generate-bangla-qr").then().statusCode(200).body("qrData", notNullValue()).body("signature", notNullValue()).body("crc", notNullValue());
    }

    /**
     * Test Case ID: TC-010
     * Generate Bangla QR with notificationMobileNo as empty string (boundary for optional field)
     */
    @Test
    public void generateBanglaQrWithEmptyNotificationMobileNo() {
        String requestBody = """
            {
              "qrVersion": "01",
              "format": "01",
              "method": "11",
              "accountType": "00",
              "merchantCategoryCode": "4111",
              "merchantId": "MERCHANT123",
              "merchantPan": "1234567890123456",
              "merchantAccountNo": "ACCT1234567890",
              "merchantName": "Test Merchant",
              "merchantCity": "DHAKA",
              "merchantCountryCode": "BD",
              "trxCurrencyCode": "050",
              "notificationMobileNo": "",
              "terminalId": "TERM12345678",
              "purposeOfTrx": "00",
              "acquirerInstitutionType": "01",
              "acquirerId": "ACQ1234567890"
            }
            """;
        given().contentType(ContentType.JSON).body(requestBody).when().post("/generate-bangla-qr").then().statusCode(200).body("qrData", notNullValue()).body("signature", notNullValue()).body("crc", notNullValue());
    }

    /**
     * Test Case ID: TC-011
     * Generate Bangla QR with purposeOfTrx exactly 1 character (minimum non-empty length for optional field)
     */
    @Test
    public void generateBanglaQrWithPurposeOfTrxOneCharacter() {
        String requestBody = """
            {
              "qrVersion": "01",
              "format": "01",
              "method": "11",
              "accountType": "00",
              "merchantCategoryCode": "4111",
              "merchantId": "MERCHANT123",
              "merchantPan": "1234567890123456",
              "merchantAccountNo": "ACCT1234567890",
              "merchantName": "Test Merchant",
              "merchantCity": "DHAKA",
              "merchantCountryCode": "BD",
              "trxCurrencyCode": "050",
              "notificationMobileNo": "8801712345678",
              "terminalId": "TERM12345678",
              "purposeOfTrx": "1",
              "acquirerInstitutionType": "01",
              "acquirerId": "ACQ1234567890"
            }
            """;
        given().contentType(ContentType.JSON).body(requestBody).when().post("/generate-bangla-qr").then().statusCode(200).body("qrData", notNullValue()).body("signature", notNullValue()).body("crc", notNullValue());
    }

    /**
     * Test Case ID: TC-012
     * Generate Bangla QR with purposeOfTrx as empty string (boundary for optional field)
     */
    @Test
    public void generateBanglaQrWithPurposeOfTrxEmptyString() {
        String requestBody = """
            {
              "qrVersion": "01",
              "format": "01",
              "method": "11",
              "accountType": "00",
              "merchantCategoryCode": "4111",
              "merchantId": "MERCHANT123",
              "merchantPan": "1234567890123456",
              "merchantAccountNo": "ACCT1234567890",
              "merchantName": "Test Merchant",
              "merchantCity": "DHAKA",
              "merchantCountryCode": "BD",
              "trxCurrencyCode": "050",
              "notificationMobileNo": "8801712345678",
              "terminalId": "TERM12345678",
              "purposeOfTrx": "",
              "acquirerInstitutionType": "01",
              "acquirerId": "ACQ1234567890"
            }
            """;
        given().contentType(ContentType.JSON).body(requestBody).when().post("/generate-bangla-qr").then().statusCode(200).body("qrData", notNullValue()).body("signature", notNullValue()).body("crc", notNullValue());
    }

    /**
     * Test Case ID: TC-013
     * Generate Bangla QR with qrVersion exactly 1 character (minimum non-empty length)
     */
    @Test
    public void generateBanglaQrWithQrVersionOneCharacter() {
        String requestBody = """
            {
              "qrVersion": "1",
              "format": "01",
              "method": "11",
              "accountType": "00",
              "merchantCategoryCode": "4111",
              "merchantId": "MERCHANT123",
              "merchantPan": "1234567890123456",
              "merchantAccountNo": "ACCT1234567890",
              "merchantName": "Test Merchant",
              "merchantCity": "DHAKA",
              "merchantCountryCode": "BD",
              "trxCurrencyCode": "050",
              "notificationMobileNo": "8801712345678",
              "terminalId": "TERM12345678",
              "purposeOfTrx": "00",
              "acquirerInstitutionType": "01",
              "acquirerId": "ACQ1234567890"
            }
            """;
        given().contentType(ContentType.JSON).body(requestBody).when().post("/generate-bangla-qr").then().statusCode(200).body("qrData", notNullValue()).body("signature", notNullValue()).body("crc", notNullValue());
    }

    /**
     * Test Case ID: TC-014
     * Generate Bangla QR with qrVersion as empty string (invalid boundary)
     */
    @Test
    public void generateBanglaQrWithQrVersionEmptyString() {
        String requestBody = """
            {
              "qrVersion": "",
              "format": "01",
              "method": "11",
              "accountType": "00",
              "merchantCategoryCode": "4111",
              "merchantId": "MERCHANT123",
              "merchantPan": "1234567890123456",
              "merchantAccountNo": "ACCT1234567890",
              "merchantName": "Test Merchant",
              "merchantCity": "DHAKA",
              "merchantCountryCode": "BD",
              "trxCurrencyCode": "050",
              "notificationMobileNo": "8801712345678",
              "terminalId": "TERM12345678",
              "purposeOfTrx": "00",
              "acquirerInstitutionType": "01",
              "acquirerId": "ACQ1234567890"
            }
            """;
        given().contentType(ContentType.JSON).body(requestBody).when().post("/generate-bangla-qr").then().statusCode(400).body("message", containsString("qrVersion must not be blank"));
    }

    /**
     * Test Case ID: TC-015
     * Verify that the generated QR signature is derived from a secure HMAC-SHA256 process and matches the expected length
     */
    @Test
    public void verifyGeneratedQrSignatureSecurity() {
        String requestBody = """
            {
              "qrVersion": "01",
              "format": "01",
              "method": "11",
              "accountType": "01",
              "merchantCategoryCode": "4111",
              "merchantId": "MERCHANT123",
              "merchantPan": "1234567890123456",
              "merchantAccountNo": "ACC123456789",
              "merchantName": "Test Merchant",
              "merchantCity": "Dhaka",
              "merchantCountryCode": "BD",
              "trxCurrencyCode": "050",
              "notificationMobileNo": "8801712345678",
              "terminalId": "TERM12345678",
              "purposeOfTrx": "Test Payment",
              "acquirerInstitutionType": "01",
              "acquirerId": "ACQ12345678",
              "merchantLogo": "logo123"
            }
            """;
        given().contentType(ContentType.JSON).body(requestBody).when().post("/generate-bangla-qr").then().statusCode(200).body("signature", notNullValue()).body("signature", // Assuming signatureLength=8 as per preconditions
        hasLength(8)).body("crc", notNullValue()).body("crc", // 4-character hex string
        matchesPattern("^[0-9A-Fa-f]{4}$"));
    }

    /**
     * Test Case ID: TC-016
     * Verify that altering any field in the request changes the generated signature.
     */
    @Test
    public void verifySignatureChangesOnInputTampering() {
        String originalBody = """
            {
              "qrVersion": "01",
              "format": "01",
              "method": "11",
              "merchantCategoryCode": "4111",
              "merchantId": "MERCHANT123",
              "merchantPan": "1234567890123456",
              "merchantAccountNo": "ACC123456789",
              "merchantName": "Test Merchant",
              "merchantCity": "Dhaka",
              "merchantCountryCode": "BD",
              "trxCurrencyCode": "050",
              "terminalId": "TERM12345678",
              "acquirerInstitutionType": "01",
              "acquirerId": "ACQ12345678"
            }
            """;
        String modifiedBody = """
            {
              "qrVersion": "01",
              "format": "01",
              "method": "11",
              "merchantCategoryCode": "4111",
              "merchantId": "MERCHANT123",
              "merchantPan": "1234567890123456",
              "merchantAccountNo": "ACC123456789",
              "merchantName": "Tampered Merchant",
              "merchantCity": "Dhaka",
              "merchantCountryCode": "BD",
              "trxCurrencyCode": "050",
              "terminalId": "TERM12345678",
              "acquirerInstitutionType": "01",
              "acquirerId": "ACQ12345678"
            }
            """;
        // Get original signature
        String originalSignature = given().contentType(ContentType.JSON).body(originalBody).when().post("/generate-bangla-qr").then().statusCode(200).extract().path("signature");
        // Get modified signature
        String modifiedSignature = given().contentType(ContentType.JSON).body(modifiedBody).when().post("/generate-bangla-qr").then().statusCode(200).extract().path("signature");
        // Assert signatures are different
        assertNotEquals(originalSignature, modifiedSignature, "Signature should change when input is tampered");
    }

    /**
     * Test Case ID: TC-017
     * Verify that the signing key and GUID are never exposed in the response.
     */
    @Test
    public void verifySensitiveDataNotExposedInResponse() {
        String requestBody = """
            {
              "qrVersion": "01",
              "format": "01",
              "method": "11",
              "merchantCategoryCode": "4111",
              "merchantId": "MERCHANT123",
              "merchantPan": "1234567890123456",
              "merchantAccountNo": "ACC123456789",
              "merchantName": "Test Merchant",
              "merchantCity": "Dhaka",
              "merchantCountryCode": "BD",
              "trxCurrencyCode": "050",
              "terminalId": "TERM12345678",
              "acquirerInstitutionType": "01",
              "acquirerId": "ACQ12345678"
            }
            """;
        given().contentType(ContentType.JSON).body(requestBody).when().post("/generate-bangla-qr").then().statusCode(200).body("qrData", not(containsString("secret123"))).body("qrData", not(containsString("GUID12345"))).body("signature", not(containsString("secret123"))).body("signature", not(containsString("GUID12345"))).body("crc", not(containsString("secret123"))).body("crc", not(containsString("GUID12345")));
    }

    /**
     * Test Case ID: TC-018
     * Verify that the system rejects signature generation if signature length exceeds HMAC-SHA256 output length.
     */
    @Test
    public void verifyRejectionOnExcessiveSignatureLength() {
        String requestBody = """
            {
              "qrVersion": "01",
              "format": "01",
              "method": "11",
              "merchantCategoryCode": "4111",
              "merchantId": "MERCHANT123",
              "merchantPan": "1234567890123456",
              "merchantAccountNo": "ACC123456789",
              "merchantName": "Test Merchant",
              "merchantCity": "Dhaka",
              "merchantCountryCode": "BD",
              "trxCurrencyCode": "050",
              "terminalId": "TERM12345678",
              "acquirerInstitutionType": "01",
              "acquirerId": "ACQ12345678"
            }
            """;
        given().contentType(ContentType.JSON).body(requestBody).when().post("/generate-bangla-qr").then().statusCode(500);
    }

    /**
     * Test Case ID: TC-019
     * Verify that special characters in merchant fields do not break QR encoding.
     */
    @Test
    public void verifySpecialCharactersHandledInQrData() {
        String requestBody = """
            {
              "qrVersion": "01",
              "format": "01",
              "method": "11",
              "merchantCategoryCode": "4111",
              "merchantId": "MERCHANT123",
              "merchantPan": "1234567890123456",
              "merchantAccountNo": "ACC123456789",
              "merchantName": "Test<Merchant>",
              "merchantCity": "Dhaka; rm -rf",
              "merchantCountryCode": "BD",
              "trxCurrencyCode": "050",
              "terminalId": "TERM12345678",
              "acquirerInstitutionType": "01",
              "acquirerId": "ACQ12345678"
            }
            """;
        given().contentType(ContentType.JSON).body(requestBody).when().post("/generate-bangla-qr").then().statusCode(200).body("qrData", not(containsString("<script>"))).body("qrData", not(containsString("rm -rf"))).body("qrData", allOf(containsString("Test&lt;Merchant&gt;"), containsString("Dhaka; rm -rf")));
    }

}
