package com.company.aiqa.generated;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.testng.Assert;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;

/**
 * Automated API tests for commit a0cfc89d02f124dcfd07aaf75bb3d8a707dd1c62.
 * Generated by ai-qa-platform from that commit's manual test cases.
 */
public class AutomationTest_a0cfc89d02f124dcfd07aaf75bb3d8a707dd1c62 {

    @BeforeClass
    public void setup() {
        RestAssured.baseURI = System.getProperty("baseUri", "http://169.58.37.242:8007/mms");
    }

    // TC-005 - Standard-length mobile number reveals only the last 4 digits
    @Test
    public void standardLengthMobileNumberRevealsOnlyLastFourDigits() {
        String requestBody = """
            {
              "storeName": "ABC Store - Dhaka Branch",
              "storeLocation": "123 - Store address",
              "notificationMobileNumber": "01712345678"
            }
            """;
        given().contentType(ContentType.JSON).header("X-Auth-Subject", "12345").body(requestBody).when().post("/api/v1/onboarding").then().statusCode(anyOf(is(200), is(201)));
    }

    // TC-006 - Null mobile number passed to the masker does not throw
    @Test
    public void nullMobileNumberPassedToMaskerDoesNotThrow() {
        String requestBody = """
            {
              "storeName": "ABC Store - Dhaka Branch",
              "storeLocation": "123 - Store address"
            }
            """;
        given().contentType(ContentType.JSON).header("X-Auth-Subject", "12345").body(requestBody).when().post("/api/v1/onboarding").then().statusCode(anyOf(is(200), is(201)));
    }

    // TC-012
    @Test
    public void submitKycInformationSuccessfully() {
        long timestamp = System.currentTimeMillis();
        String requestBody = """
            {
              "storeName": "Store_%d",
              "storeLocation": "123 Main Street, Dhaka",
              "notificationMobileNumber": "01670636253"
            }
            """.formatted(timestamp);
        given().contentType(ContentType.JSON).header("X-Auth-Subject", "12345").header("auth-subject", "12345").body(requestBody).when().post("/api/v1/onboarding").then().statusCode(anyOf(is(200), is(201))).body("success", equalTo(true)).body("data.kycStatus", notNullValue());
    }

    // TC-015
    @Test
    public void whenKycRegistrationFailsDuringMerchantOnboardingProcessHandlesFailure() {
        String requestBody = """
            {
              "storeName": "Test Store %d",
              "storeLocation": "Dhaka",
              "notificationMobileNumber": "9999999999"
            }
            """.formatted(System.currentTimeMillis());
        Response response = given().header("X-Auth-Subject", "12345").contentType(ContentType.JSON).body(requestBody).when().post("/api/v1/onboarding");
        int statusCode = response.getStatusCode();
        if (statusCode >= 200 && statusCode < 300) {
            response.then().body("data.kycStatus", anyOf(equalTo("REJECTED"), equalTo("INCOMPLETE"), equalTo("FAILED")));
        } else {
            Assert.assertTrue(statusCode >= 400 && statusCode < 500, "Expected 2xx with failed KYC status or 4xx status. Got status: " + statusCode);
        }
    }

}
