package com.company.aiqa.generated;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.testng.Assert;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;

/**
 * Automated API tests for commit 26ade1c7ec9d874767476da6d3e83813352f611a.
 * Generated by ai-qa-platform from that commit's manual test cases.
 */
public class AutomationTest_26ade1c7ec9d874767476da6d3e83813352f611a {

    @BeforeClass
    public void setup() {
        RestAssured.baseURI = System.getProperty("baseUri", "http://169.58.37.242:8007/mms");
    }

    // Test Case ID: a1e801d-TC-001
    @Test
    public void createNewOrderWithWholeNumberPrice() {
        String requestBody = """
            {
              "customerName": "Alice Johnson",
              "productName": "Monitor",
              "quantity": 3,
              "price": 250
            }
            """;
        given().contentType(ContentType.JSON).body(requestBody).when().post("/orders").then().statusCode(200).body("id", notNullValue()).body("customerName", equalTo("Alice Johnson")).body("productName", equalTo("Monitor")).body("quantity", equalTo(3)).body("price", equalTo(250));
    }

    // Test Case ID: a1e801d-TC-003
    @Test
    public void updateExistingOrderWithWholeNumberPrice() {
        String createBody = """
            {
              "customerName": "John Doe",
              "productName": "Laptop",
              "quantity": 1,
              "price": 999
            }
            """;
        // Precondition: create the order to update
        Integer orderId = given().contentType(ContentType.JSON).body(createBody).when().post("/orders").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        String updateBody = """
            {
              "customerName": "John Doe",
              "productName": "Laptop",
              "quantity": 1,
              "price": 850
            }
            """;
        given().contentType(ContentType.JSON).body(updateBody).when().put("/orders/{id}", orderId).then().statusCode(200).body("id", equalTo(orderId)).body("customerName", equalTo("John Doe")).body("productName", equalTo("Laptop")).body("quantity", equalTo(1)).body("price", equalTo(850));
    }

    // Test Case ID: TC-001
    @Test
    public void retrieveDetailsOfOrderWithWholeNumberPrice() {
        String createBody = """
            {
              "customerName": "Alice Johnson",
              "productName": "Monitor",
              "quantity": 3,
              "price": 250
            }
            """;
        // Precondition: create the order to retrieve
        Integer orderId = given().contentType(ContentType.JSON).body(createBody).when().post("/orders").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        given().when().get("/orders/{id}", orderId).then().statusCode(200).body("id", equalTo(orderId)).body("customerName", equalTo("Alice Johnson")).body("productName", equalTo("Monitor")).body("quantity", equalTo(3)).body("price", equalTo(250));
    }

    // Test Case ID: TC-002
    @Test
    public void createOrderWithDecimalPrice() {
        String requestBody = """
            {
              "customerName": "John Doe",
              "productName": "Laptop",
              "quantity": 1,
              "price": 19.99
            }
            """;
        String body = given().contentType(ContentType.JSON).body(requestBody).when().post("/orders").then().statusCode(anyOf(is(400), is(422))).extract().asString();
        Assert.assertTrue(body.toLowerCase().contains("price"), "Expected the error to mention the offending field. Body was: " + body);
    }

    // Test Case ID: TC-003
    @Test
    public void createOrderWithWholeLookingDecimalPrice() {
        String requestBody = """
            {
              "customerName": "Jane Smith",
              "productName": "Monitor",
              "quantity": 2,
              "price": 20.0
            }
            """;
        String body = given().contentType(ContentType.JSON).body(requestBody).when().post("/orders").then().statusCode(anyOf(is(400), is(422))).extract().asString();
        Assert.assertTrue(body.toLowerCase().contains("price"), "Expected the error to mention the offending field. Body was: " + body);
    }

    // TC-004 - Create order with price as a numeric string (e.g., '50')
    @Test
    public void createOrderWithPriceAsNumericString() {
        String requestBody = """
            {
              "customerName": "Alice Brown",
              "productName": "Keyboard",
              "quantity": 3,
              "price": "50"
            }
            """;
        given().contentType(ContentType.JSON).body(requestBody).when().post("/orders").then().statusCode(anyOf(is(400), is(422)));
    }

    // TC-005 - Update order with price as a decimal number (e.g., 99.99)
    @Test
    public void updateOrderWithPriceAsDecimalNumber() {
        // Precondition: create an order to update
        String createBody = """
            {
              "customerName": "John Doe",
              "productName": "Laptop",
              "quantity": 1,
              "price": 100
            }
            """;
        Integer orderId = given().contentType(ContentType.JSON).body(createBody).when().post("/orders").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Test case: update with decimal price
        String updateBody = """
            {
              "customerName": "John Doe",
              "productName": "Laptop",
              "quantity": 1,
              "price": 99.99
            }
            """;
        given().contentType(ContentType.JSON).body(updateBody).when().put("/orders/{id}", orderId).then().statusCode(anyOf(is(400), is(422)));
    }

    // TC-006 - Update order with price as a whole-looking decimal (e.g., 100.0)
    @Test
    public void updateOrderWithPriceAsWholeLookingDecimal() {
        // Precondition: create an order to update
        String createBody = """
            {
              "customerName": "Jane Smith",
              "productName": "Monitor",
              "quantity": 2,
              "price": 200
            }
            """;
        Integer orderId = given().contentType(ContentType.JSON).body(createBody).when().post("/orders").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Test case: update with whole-looking decimal price
        String updateBody = """
            {
              "customerName": "Jane Smith",
              "productName": "Monitor",
              "quantity": 2,
              "price": 100.0
            }
            """;
        given().contentType(ContentType.JSON).body(updateBody).when().put("/orders/{id}", orderId).then().statusCode(anyOf(is(400), is(422)));
    }

    // TC-007 - Update order with price as a numeric string (e.g., '75')
    @Test
    public void updateOrderWithPriceAsNumericString() {
        // Precondition: create an order to update
        String createBody = """
            {
              "customerName": "Alice Brown",
              "productName": "Keyboard",
              "quantity": 3,
              "price": 75
            }
            """;
        Integer orderId = given().contentType(ContentType.JSON).body(createBody).when().post("/orders").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Test case: update with numeric string price
        String updateBody = """
            {
              "customerName": "Alice Brown",
              "productName": "Keyboard",
              "quantity": 3,
              "price": "75"
            }
            """;
        given().contentType(ContentType.JSON).body(updateBody).when().put("/orders/{id}", orderId).then().statusCode(anyOf(is(400), is(422)));
    }

    // a1e801d-TC-010 - Create order with price as a negative number (updated validation)
    @Test
    public void createOrderWithPriceAsNegativeNumber() {
        String requestBody = """
            {
              "customerName": "John Doe",
              "productName": "Laptop",
              "quantity": 1,
              "price": -50
            }
            """;
        given().contentType(ContentType.JSON).body(requestBody).when().post("/orders").then().statusCode(anyOf(is(400), is(422)));
    }

    // Test Case ID: a1e801d-TC-019
    @Test
    public void createOrderWithMinimumAllowedIntegerPrice() {
        String requestBody = """
            {
              "customerName": "John Doe",
              "productName": "Widget",
              "quantity": 1,
              "price": 0
            }
            """;
        given().contentType(ContentType.JSON).body(requestBody).when().post("/orders").then().statusCode(200).body("customerName", equalTo("John Doe")).body("productName", equalTo("Widget")).body("quantity", equalTo(1)).body("price", equalTo(0));
    }

    // Test Case ID: a1e801d-TC-020
    @Test
    public void createOrderWithNegativeIntegerPrice() {
        String requestBody = """
            {
              "customerName": "John Doe",
              "productName": "Widget",
              "quantity": 1,
              "price": -1
            }
            """;
        given().contentType(ContentType.JSON).body(requestBody).when().post("/orders").then().statusCode(anyOf(is(400), is(422)));
    }

    // Test Case ID: TC-008
    @Test
    public void createOrderWithMaximumAllowedIntegerPrice() {
        String requestBody = """
            {
              "customerName": "John Doe",
              "productName": "Widget",
              "quantity": 1,
              "price": 2147483647
            }
            """;
        given().contentType(ContentType.JSON).body(requestBody).when().post("/orders").then().statusCode(200).body("customerName", equalTo("John Doe")).body("productName", equalTo("Widget")).body("quantity", equalTo(1)).body("price", equalTo(2147483647));
    }

    // Test Case ID: TC-009
    @Test
    public void createOrderWithPriceOneAboveMaximumInteger() {
        String requestBody = """
            {
              "customerName": "John Doe",
              "productName": "Widget",
              "quantity": 1,
              "price": 2147483648
            }
            """;
        given().contentType(ContentType.JSON).body(requestBody).when().post("/orders").then().statusCode(anyOf(is(400), is(422)));
    }

    // Test Case ID: a1e801d-TC-025
    @Test
    public void updateOrderWithMinimumAllowedIntegerPrice() {
        String createBody = """
            {
              "customerName": "John Doe_%d",
              "productName": "Widget",
              "quantity": 1,
              "price": 100
            }
            """.formatted(System.currentTimeMillis());
        Integer orderId = given().contentType(ContentType.JSON).body(createBody).when().post("/orders").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        String updateBody = """
            {
              "customerName": "John Doe_%d",
              "productName": "Widget",
              "quantity": 1,
              "price": 0
            }
            """.formatted(System.currentTimeMillis());
        given().contentType(ContentType.JSON).body(updateBody).when().put("/orders/{id}", orderId).then().statusCode(200).body("id", equalTo(orderId)).body("price", equalTo(0));
    }

    // TC-026 - Update order with negative integer price (-1) - boundary below minimum
    @Test
    public void updateOrderWithNegativePrice() {
        String createBody = """
            {
              "customerName": "John Doe_%d",
              "productName": "Widget",
              "quantity": 1,
              "price": 100
            }
            """.formatted(System.currentTimeMillis());
        // Precondition: create an order
        Integer orderId = given().contentType(ContentType.JSON).body(createBody).when().post("/orders").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        String updateBody = """
            {
              "customerName": "John Doe_%d",
              "productName": "Widget",
              "quantity": 1,
              "price": -1
            }
            """.formatted(System.currentTimeMillis());
        // Test case: update with negative price
        given().contentType(ContentType.JSON).body(updateBody).when().put("/orders/{id}", orderId).then().statusCode(anyOf(is(400), is(422)));
    }

    // TC-010 - Update order with maximum allowed integer price (2147483647)
    @Test
    public void updateOrderWithMaxIntegerPrice() {
        String createBody = """
            {
              "customerName": "John Doe_%d",
              "productName": "Widget",
              "quantity": 1,
              "price": 100
            }
            """.formatted(System.currentTimeMillis());
        // Precondition: create an order
        Integer orderId = given().contentType(ContentType.JSON).body(createBody).when().post("/orders").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        String updateBody = """
            {
              "customerName": "John Doe_%d",
              "productName": "Widget",
              "quantity": 1,
              "price": 2147483647
            }
            """.formatted(System.currentTimeMillis());
        // Test case: update with max integer price
        given().contentType(ContentType.JSON).body(updateBody).when().put("/orders/{id}", orderId).then().statusCode(200).body("price", equalTo(2147483647));
    }

    // TC-011 - Update order with price one above maximum integer (2147483648) - boundary overflow
    @Test
    public void updateOrderWithPriceAboveMaxInteger() {
        String createBody = """
            {
              "customerName": "John Doe_%d",
              "productName": "Widget",
              "quantity": 1,
              "price": 100
            }
            """.formatted(System.currentTimeMillis());
        // Precondition: create an order
        Integer orderId = given().contentType(ContentType.JSON).body(createBody).when().post("/orders").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        String updateBody = """
            {
              "customerName": "John Doe_%d",
              "productName": "Widget",
              "quantity": 1,
              "price": 2147483648
            }
            """.formatted(System.currentTimeMillis());
        // Test case: update with price above max integer
        given().contentType(ContentType.JSON).body(updateBody).when().put("/orders/{id}", orderId).then().statusCode(anyOf(is(400), is(422)));
    }

    // TC-012 - Create order with fractional price (1.99) - type boundary
    @Test
    public void createOrderWithFractionalPrice() {
        String requestBody = """
            {
              "customerName": "John Doe_%d",
              "productName": "Widget",
              "quantity": 1,
              "price": 1.99
            }
            """.formatted(System.currentTimeMillis());
        // Test case: create with fractional price
        given().contentType(ContentType.JSON).body(requestBody).when().post("/orders").then().statusCode(anyOf(is(400), is(422)));
    }

    // TC-013 - Update order with fractional price (1.99) - type boundary
    @Test
    public void updateOrderWithFractionalPrice() {
        String createBody = """
            {
              "customerName": "John Doe_%d",
              "productName": "Widget",
              "quantity": 1,
              "price": 100
            }
            """.formatted(System.currentTimeMillis());
        // Precondition: create an order
        Integer orderId = given().contentType(ContentType.JSON).body(createBody).when().post("/orders").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        String updateBody = """
            {
              "customerName": "John Doe_%d",
              "productName": "Widget",
              "quantity": 1,
              "price": 1.99
            }
            """.formatted(System.currentTimeMillis());
        // Test case: update with fractional price
        given().contentType(ContentType.JSON).body(updateBody).when().put("/orders/{id}", orderId).then().statusCode(anyOf(is(400), is(422)));
    }

}
