package com.company.aiqa.generated;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import org.hamcrest.Matchers;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;

/**
 * Automated API tests for commit 3d221c040c6a1cf6f1875500947c22b239d13ab7.
 * Generated by ai-qa-platform from that commit's manual test cases.
 */
public class AutomationTest_3d221c040c6a1cf6f1875500947c22b239d13ab7 {

    @BeforeClass
    public void setup() {
        RestAssured.baseURI = System.getProperty("baseUri", "http://localhost:8080");
    }

    /**
     * TC-002 - Attempt to access API endpoints with a server URL containing invalid characters
     */
    @Test
    public void attemptAccessWithInvalidServerUrl() {
        given().baseUri("https://no-q.club/<script>").when().get("/api/areas").then().statusCode(400).body(containsString("malformed"));
    }

    /**
     * TC-003 - Attempt to access API endpoints with a server URL that is excessively long
     */
    @Test
    public void attemptAccessWithExcessivelyLongServerUrl() {
        String longUrl = "https://no-q.club" + "a".repeat(2000);
        given().baseUri(longUrl).when().get("/api/areas").then().statusCode(400).body(containsString("too long"));
    }

    /**
     * 810dfc9-TC-018 - Verify Swagger UI access from the newly configured domain (no-q.club) without authentication
     * OMITTED: This test involves UI interaction (browser navigation) and cannot be automated via HTTP.
     */
    /**
     * 810dfc9-TC-019 - Verify OpenAPI JSON specification access from the newly configured domain (no-q.club) without authentication
     */
    @Test
    public void verifyOpenApiJsonAccessWithoutAuthentication() {
        given().baseUri("https://no-q.club").when().get("/v3/api-docs").then().statusCode(200).body("servers.url", hasItem("https://no-q.club")).body("info.title", not(containsString("legacy")));
    }

    /**
     * Test Case ID: TC-005
     * Verify OpenAPI JSON specification access from the previously allowed domain (no-q:8080) is now blocked
     */
    @Test
    public void verifyLegacyOpenApiJsonAccessBlocked() {
        given().header("Origin", "http://no-q:8080").when().get("/v3/api-docs").then().statusCode(anyOf(is(403), is(400))).header("Access-Control-Allow-Origin", nullValue());
    }

    /**
     * Test Case ID: 810dfc9-TC-029
     * Verify that OpenAPI/Swagger UI documentation is accessible only from the updated allowed origin (https://no-q.club)
     */
    @Test
    public void verifyOpenApiAccessAllowedFromUpdatedOrigin() {
        given().header("Origin", "https://no-q.club").when().get("/v3/api-docs").then().statusCode(200).header("Access-Control-Allow-Origin", "https://no-q.club");
    }

    @Test
    public void verifyOpenApiAccessBlockedFromDisallowedOrigin() {
        given().header("Origin", "https://malicious-site.com").when().get("/v3/api-docs").then().statusCode(anyOf(is(403), is(400))).header("Access-Control-Allow-Origin", nullValue());
    }

    /**
     * Test Case ID: TC-006
     * Verify that OpenAPI/Swagger UI documentation is not accessible from arbitrary origins
     */
    @Test
    public void verifyOpenApiAccessBlockedFromArbitraryOrigin() {
        given().header("Origin", "https://test-site.com").when().get("/v3/api-docs").then().statusCode(anyOf(is(403), is(400))).header("Access-Control-Allow-Origin", nullValue());
    }

}
