package com.company.aiqa.generated;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.testng.Assert;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;

/**
 * Automated API tests for commit mms.
 * Generated by ai-qa-platform from that commit's manual test cases.
 */
public class AutomationTest_mms {

    @BeforeClass
    public void setup() {
        RestAssured.baseURI = System.getProperty("baseUri", "http://169.58.37.242:8007/mms");
    }

    // 3836dee-TC-001 - Create a new payment capability type successfully
    @Test
    public void createNewPaymentCapabilityTypeSuccessfully() {
        long timestamp = System.currentTimeMillis();
        String capabilityCode = "ONLINE_PAYMENT_" + timestamp;
        if (capabilityCode.length() > 50) {
            capabilityCode = capabilityCode.substring(0, 50);
        }
        String requestBody = """
            {
              "capabilityCode": "%s",
              "name": "Online Payment",
              "description": "Accept payments via online channels"
            }
            """.formatted(capabilityCode);
        given().contentType(ContentType.JSON).body(requestBody).when().post("/api/v1/capabilities").then().statusCode(201).body("success", equalTo(true)).body("data.id", notNullValue()).body("data.capabilityCode", equalTo(capabilityCode)).body("data.name", equalTo("Online Payment")).body("data.active", equalTo(true));
    }

    // 3836dee-TC-002 - Create a valid category-level flat fee configuration with default currency
    @Test
    public void createCategoryLevelFlatFeeConfigurationWithDefaultCurrency() {
        String requestBody = """
            {
              "merchantCategoryCode": "5411",
              "capabilityCode": "ONLINE_PAYMENT",
              "feeType": "FLAT",
              "flatAmount": 5.00,
              "effectiveFrom": "2026-01-01"
            }
            """;
        Response response = given().contentType(ContentType.JSON).body(requestBody).when().post("/api/v1/fees").then().statusCode(201).body("success", equalTo(true)).body("data.id", notNullValue()).body("data.merchantCategoryCode", equalTo("5411")).body("data.capabilityCode", equalTo("ONLINE_PAYMENT")).body("data.feeType", equalTo("FLAT")).extract().response();
        Number flatAmount = response.path("data.flatAmount");
        Assert.assertNotNull(flatAmount, "flatAmount should not be null");
        Assert.assertEquals(flatAmount.doubleValue(), 5.00, 0.001);
    }

    // 3836dee-TC-003 - Add a pricing tier to an existing fee configuration
    @Test
    public void addPricingTierToExistingFeeConfiguration() {
        // Precondition: Create a tiered fee configuration first
        String createFeeBody = """
            {
              "merchantCategoryCode": "5411",
              "capabilityCode": "ONLINE_PAYMENT",
              "feeType": "TIERED",
              "effectiveFrom": "2026-01-01"
            }
            """;
        String feeId = given().contentType(ContentType.JSON).body(createFeeBody).when().post("/api/v1/fees").then().statusCode(201).extract().path("data.id");
        Assert.assertNotNull(feeId, "Precondition failed: Fee configuration creation returned null ID");
        String addTierBody = """
            {
              "tierFrom": 0.00,
              "tierTo": 1000.00,
              "rate": 2.50,
              "flatAmount": 0.00
            }
            """;
        Response tierResponse = given().contentType(ContentType.JSON).body(addTierBody).when().post("/api/v1/fees/{id}/tiers", feeId).then().statusCode(201).body("success", equalTo(true)).body("data.id", notNullValue()).extract().response();
        Number tierFrom = tierResponse.path("data.tierFrom");
        Number tierTo = tierResponse.path("data.tierTo");
        Number rate = tierResponse.path("data.rate");
        Assert.assertNotNull(tierFrom, "tierFrom should not be null");
        Assert.assertEquals(tierFrom.doubleValue(), 0.00, 0.001);
        Assert.assertNotNull(tierTo, "tierTo should not be null");
        Assert.assertEquals(tierTo.doubleValue(), 1000.00, 0.001);
        Assert.assertNotNull(rate, "rate should not be null");
        Assert.assertEquals(rate.doubleValue(), 2.50, 0.001);
    }

    // 3836dee-TC-004 - Assign a payment capability to an existing merchant
    @Test
    public void assignPaymentCapabilityToExistingMerchant() {
        // Precondition 1: Create a merchant
        long timestamp = System.currentTimeMillis();
        String merchantBody = """
                        {
                          "legalName": "Merchant Cap Test LLC",
                          "tradeName": "Merchant Cap Store",
                          "registrationNo": "CR-%d",
                          "businessType": "CORPORATION",
              "userId": %d
            }
            """.formatted(timestamp, System.currentTimeMillis() % 100_000);
        String merchantId = given().contentType(ContentType.JSON).body(merchantBody).when().post("/api/v1/merchants").then().statusCode(201).extract().path("data.id");
        Assert.assertNotNull(merchantId, "Precondition failed: Merchant creation returned null ID");
        // Precondition 2: Create a payment capability
        String capabilityCode = "CAP_ASSIGN_" + (timestamp % 100000);
        String capabilityBody = """
            {
              "capabilityCode": "%s",
              "name": "Test Capability Assignment",
              "description": "Capability for assignment test"
            }
            """.formatted(capabilityCode);
        String capabilityId = given().contentType(ContentType.JSON).body(capabilityBody).when().post("/api/v1/capabilities").then().statusCode(201).extract().path("data.id");
        Assert.assertNotNull(capabilityId, "Precondition failed: Capability creation returned null ID");
        // Action: Assign capability to merchant
        String assignBody = """
            {
              "capabilityId": "%s"
            }
            """.formatted(capabilityId);
        given().contentType(ContentType.JSON).body(assignBody).when().post("/api/v1/merchants/{merchantId}/capabilities", merchantId).then().statusCode(201).body("success", equalTo(true)).body("data.id", notNullValue()).body("data.merchantId", equalTo(merchantId)).body("data.capabilityId", equalTo(capabilityId)).body("data.status", equalTo("ACTIVE"));
    }

    // 3836dee-TC-005 - Successfully onboard a new merchant with standard business details
    @Test
    public void successfullyOnboardNewMerchantWithStandardBusinessDetails() {
        long timestamp = System.currentTimeMillis();
        String registrationNo = "CR-" + timestamp;
        String requestBody = """
                        {
                          "legalName": "Apex Retail LLC",
                          "tradeName": "Apex Store",
                          "registrationNo": "%s",
                          "taxId": "TAX-1122334455",
                          "merchantCategoryCode": "5411",
                          "businessType": "CORPORATION",
                          "contactEmail": "info@apexstore.com",
                          "contactPhone": "+966500000001",
                          "website": "https://www.apexstore.com",
                          "address": "789 King Fahd Road",
                          "city": "Riyadh",
                          "state": "Riyadh Province",
                          "postalCode": "12211",
                          "country": "SA",
              "userId": %d
            }
            """.formatted(registrationNo, System.currentTimeMillis() % 100_000);
        given().contentType(ContentType.JSON).body(requestBody).when().post("/api/v1/merchants").then().statusCode(201).body("success", equalTo(true)).body("data.id", notNullValue()).body("data.merchantCode", notNullValue()).body("data.legalName", equalTo("Apex Retail LLC")).body("data.tradeName", equalTo("Apex Store")).body("data.registrationNo", equalTo(registrationNo)).body("data.status", equalTo("PENDING"));
    }

    // 3836dee-TC-006
    @Test
    public void approveNewlyOnboardedPendingMerchant() {
        long timestamp = System.currentTimeMillis();
        String createMerchantBody = """
                        {
                          "legalName": "Approval Test Merchant LLC",
                          "tradeName": "Approval Test Store",
                          "registrationNo": "CR-%d",
                          "taxId": "TAX-%d",
                          "merchantCategoryCode": "5411",
                          "businessType": "CORPORATION",
                          "contactEmail": "app%d@example.com",
                          "contactPhone": "+966501234567",
                          "website": "https://www.example.com",
                          "address": "123 King Fahd Road",
                          "city": "Riyadh",
                          "state": "Riyadh Province",
                          "postalCode": "11564",
                          "country": "SA",
              "userId": %d
            }
            """.formatted(timestamp, timestamp, timestamp, System.currentTimeMillis() % 100_000);
        Response createResp = given().contentType(ContentType.JSON).body(createMerchantBody).when().post("/api/v1/merchants").then().statusCode(anyOf(is(200), is(201))).extract().response();
        String merchantId = createResp.path("data.id") != null ? createResp.path("data.id") : createResp.path("id");
        Assert.assertNotNull(merchantId, "Precondition failed: merchant creation returned no id");
        given().contentType(ContentType.JSON).when().post("/api/v1/merchants/{id}/approve", merchantId).then().statusCode(200).body("data.status", equalTo("APPROVED")).body("data.approvedAt", notNullValue());
    }

    // 3836dee-TC-007
    @Test
    public void generateStaticEmvQrCodeForActiveMerchant() {
        long timestamp = System.currentTimeMillis();
        String createMerchantBody = """
                        {
                          "legalName": "QR Merchant LLC",
                          "tradeName": "QR Store",
                          "registrationNo": "CR-QR-%d",
                          "businessType": "CORPORATION",
                          "contactEmail": "qr%d@example.com",
                          "country": "SA",
              "userId": %d
            }
            """.formatted(timestamp, timestamp, System.currentTimeMillis() % 100_000);
        Response merchantResp = given().contentType(ContentType.JSON).body(createMerchantBody).when().post("/api/v1/merchants").then().statusCode(anyOf(is(200), is(201))).extract().response();
        String merchantId = merchantResp.path("data.id") != null ? merchantResp.path("data.id") : merchantResp.path("id");
        Assert.assertNotNull(merchantId, "Precondition failed: merchant creation returned no id");
        String generateQrBody = """
            {
              "merchantId": "%s",
              "qrType": "STATIC"
            }
            """.formatted(merchantId);
        given().contentType(ContentType.JSON).body(generateQrBody).when().post("/api/v1/qr-codes").then().statusCode(201).body("data.id", notNullValue()).body("data.status", equalTo("ACTIVE")).body("data.qrData", not(emptyOrNullString()));
    }

    // 3836dee-TC-008
    @Test
    public void createNewStoreUnderExistingMerchant() {
        long timestamp = System.currentTimeMillis();
        String createMerchantBody = """
                        {
                          "legalName": "Store Owner LLC",
                          "tradeName": "Store Merchant",
                          "registrationNo": "CR-STR-%d",
                          "businessType": "LLC",
                          "contactEmail": "store%d@example.com",
                          "country": "SA",
              "userId": %d
            }
            """.formatted(timestamp, timestamp, System.currentTimeMillis() % 100_000);
        Response merchantResp = given().contentType(ContentType.JSON).body(createMerchantBody).when().post("/api/v1/merchants").then().statusCode(anyOf(is(200), is(201))).extract().response();
        String merchantId = merchantResp.path("data.id") != null ? merchantResp.path("data.id") : merchantResp.path("id");
        Assert.assertNotNull(merchantId, "Precondition failed: merchant creation returned no id");
        String createStoreBody = """
            {
              "name": "ABC Store - Riyadh Mall",
              "contactPhone": "+966501234567",
              "contactEmail": "riyadh.mall@abcstore.com",
              "address": "Riyadh Mall, Level 2, Shop 201",
              "city": "Riyadh",
              "state": "Riyadh Province",
              "postalCode": "11564",
              "country": "SA",
              "latitude": 24.7136,
              "longitude": 46.6753
            }
            """;
        given().contentType(ContentType.JSON).body(createStoreBody).when().post("/api/v1/merchants/{merchantId}/stores", merchantId).then().statusCode(201).body("success", equalTo(true)).body("message", equalTo("Store created")).body("data.storeCode", not(emptyOrNullString())).body("data.status", equalTo("ACTIVE"));
    }

    // 3836dee-TC-009
    @Test
    public void addNewPrimarySettlementBankAccountToMerchant() {
        long timestamp = System.currentTimeMillis();
        String createMerchantBody = """
                        {
                          "legalName": "Settlement Merchant LLC",
                          "tradeName": "Settlement Store",
                          "registrationNo": "CR-SET-%d",
                          "businessType": "CORPORATION",
                          "contactEmail": "settle%d@example.com",
                          "country": "SA",
              "userId": %d
            }
            """.formatted(timestamp, timestamp, System.currentTimeMillis() % 100_000);
        Response merchantResp = given().contentType(ContentType.JSON).body(createMerchantBody).when().post("/api/v1/merchants").then().statusCode(anyOf(is(200), is(201))).extract().response();
        String merchantId = merchantResp.path("data.id") != null ? merchantResp.path("data.id") : merchantResp.path("id");
        Assert.assertNotNull(merchantId, "Precondition failed: merchant creation returned no id");
        String createAccountBody = """
            {
              "accountName": "ABC Trading Company LLC",
              "bankName": "Al Rajhi Bank",
              "bankCode": "RJHI",
              "branchCode": "001",
              "accountNumber": "1234567890",
              "iban": "SA0380000000608010167519",
              "currency": "SAR",
              "primary": true
            }
            """;
        given().contentType(ContentType.JSON).body(createAccountBody).when().post("/api/v1/merchants/{merchantId}/settlement-accounts", merchantId).then().statusCode(201).body("success", equalTo(true)).body("message", equalTo("Settlement account created")).body("data.primary", equalTo(true)).body("data.status", equalTo("PENDING_VERIFICATION"));
    }

    // 3836dee-TC-010
    @Test
    public void registerNewPosTerminalForExistingStoreAndMerchant() {
        long timestamp = System.currentTimeMillis();
        String createMerchantBody = """
                        {
                          "legalName": "Terminal Merchant LLC",
                          "tradeName": "Terminal Store",
                          "registrationNo": "CR-TERM-%d",
                          "businessType": "CORPORATION",
                          "contactEmail": "term%d@example.com",
                          "country": "SA",
              "userId": %d
            }
            """.formatted(timestamp, timestamp, System.currentTimeMillis() % 100_000);
        Response merchantResp = given().contentType(ContentType.JSON).body(createMerchantBody).when().post("/api/v1/merchants").then().statusCode(anyOf(is(200), is(201))).extract().response();
        String merchantId = merchantResp.path("data.id") != null ? merchantResp.path("data.id") : merchantResp.path("id");
        Assert.assertNotNull(merchantId, "Precondition failed: merchant creation returned no id");
        String createStoreBody = """
            {
              "name": "Store For Terminal",
              "city": "Riyadh",
              "country": "SA"
            }
            """;
        Response storeResp = given().contentType(ContentType.JSON).body(createStoreBody).when().post("/api/v1/merchants/{merchantId}/stores", merchantId).then().statusCode(anyOf(is(200), is(201))).extract().response();
        String storeId = storeResp.path("data.id") != null ? storeResp.path("data.id") : storeResp.path("id");
        Assert.assertNotNull(storeId, "Precondition failed: store creation returned no id");
        String createTerminalBody = """
            {
              "merchantId": "%s",
              "storeId": "%s",
              "serialNumber": "SN-ABC12345",
              "model": "A920 Pro",
              "manufacturer": "PAX Technology"
            }
            """.formatted(merchantId, storeId);
        given().contentType(ContentType.JSON).body(createTerminalBody).when().post("/api/v1/terminals").then().statusCode(201).body("success", equalTo(true)).body("message", equalTo("Terminal registered")).body("data.terminalTid", not(emptyOrNullString())).body("data.status", equalTo("INACTIVE"));
    }

    // 3836dee-TC-011
    @Test
    public void designateExistingSettlementAccountAsPrimaryAccount() {
        long timestamp = System.currentTimeMillis();
        String createMerchantPayload = """
                        {
                          "legalName": "Primary Account Merchant %d",
                          "tradeName": "Primary Store %d",
                          "registrationNo": "CR-%d",
                          "businessType": "CORPORATION",
              "userId": %d
            }
            """.formatted(timestamp, timestamp, timestamp, System.currentTimeMillis() % 100_000);
        Response merchantResp = given().contentType(ContentType.JSON).body(createMerchantPayload).when().post("/api/v1/merchants").then().statusCode(anyOf(is(200), is(201))).extract().response();
        String merchantId = merchantResp.path("data.id") != null ? merchantResp.path("data.id") : merchantResp.path("id");
        Assert.assertNotNull(merchantId, "Precondition failed: Merchant creation failed to return ID");
        String createAccountPayload = """
            {
              "accountName": "Trading Account",
              "bankName": "Test Bank",
              "bankCode": "TSTB",
              "branchCode": "001",
              "accountNumber": "ACC%d",
              "iban": "SA0380000000608010167519",
              "currency": "SAR",
              "primary": false
            }
            """.formatted(timestamp);
        Response accountResp = given().contentType(ContentType.JSON).body(createAccountPayload).when().post("/api/v1/merchants/{merchantId}/settlement-accounts", merchantId).then().statusCode(anyOf(is(200), is(201))).extract().response();
        String accountId = accountResp.path("data.id") != null ? accountResp.path("data.id") : accountResp.path("id");
        Assert.assertNotNull(accountId, "Precondition failed: Settlement Account creation failed to return ID");
        given().when().patch("/api/v1/settlement-accounts/{id}/set-primary", accountId).then().statusCode(200).body("success", equalTo(true)).body("message", equalTo("Set as primary")).body("data.primary", equalTo(true));
    }

    // 3836dee-TC-012
    @Test
    public void rejectFeeConfigurationCreationWhenCapabilityCodeIsMissing() {
        String payload = """
                        {
                          "merchantId": "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11",
                          "feeType": "PERCENTAGE",
                          "percentageRate": 2.50,
                          "effectiveFrom": "2023-01-01",
              "capabilityCode": "ONLINE_PAYMENT"
            }
            """;
        given().contentType(ContentType.JSON).body(payload).when().post("/api/v1/fees").then().statusCode(400);
    }

    // 3836dee-TC-013
    @Test
    public void rejectFeeConfigurationCreationWhenFeeTypeIsMissing() {
        String requestBody = """
                        {
                          "capabilityCode": "ONLINE_PAYMENT",
                          "percentageRate": 2.50,
                          "effectiveFrom": "2023-01-01",
              "feeType": "FLAT"
            }
            """;
        given().contentType(ContentType.JSON).body(requestBody).when().post("/api/v1/fees").then().statusCode(400);
    }

    // 3836dee-TC-014
    @Test
    public void rejectFeeConfigurationCreationWhenEffectiveFromDateIsMissing() {
        String requestBody = """
                        {
                          "capabilityCode": "ONLINE_PAYMENT",
                          "feeType": "PERCENTAGE",
                          "percentageRate": 2.50,
              "effectiveFrom": "generated-effectiveFrom"
            }
            """;
        given().contentType(ContentType.JSON).body(requestBody).when().post("/api/v1/fees").then().statusCode(400);
    }

    // 3836dee-TC-015
    @Test
    public void rejectAddingAFeeTierWhenTierBoundsAreMissing() {
        // Precondition: Create a valid fee configuration first to obtain a real fee ID
        String createFeeBody = """
            {
              "capabilityCode": "ONLINE_PAYMENT",
              "feeType": "TIERED",
              "effectiveFrom": "2023-01-01"
            }
            """;
        Response createResponse = given().contentType(ContentType.JSON).body(createFeeBody).when().post("/api/v1/fees").then().statusCode(anyOf(is(200), is(201))).extract().response();
        String feeId = createResponse.path("data.id") != null ? createResponse.path("data.id") : createResponse.path("id");
        Assert.assertNotNull(feeId, "Precondition failed: Fee configuration creation returned no ID");
        String addTierBody = """
                        {
                          "rate": 2.50,
              "tierFrom": 0.0,
              "tierTo": 1000.0
            }
            """;
        given().contentType(ContentType.JSON).body(addTierBody).when().post("/api/v1/fees/{id}/tiers", feeId).then().statusCode(400);
    }

    // 3836dee-TC-016
    @Test
    public void rejectCreationOfPaymentCapabilityWithCodeExceedingMaxLength() {
        String requestBody = """
            {
              "capabilityCode": "THIS_CAPABILITY_CODE_IS_WAY_TOO_LONG_AND_EXCEEDS_FIFTY_CHARACTERS_LIMIT",
              "name": "Invalid Capability"
            }
            """;
        given().contentType(ContentType.JSON).body(requestBody).when().post("/api/v1/capabilities").then().statusCode(400);
    }

    // 3836dee-TC-017
    @Test
    public void rejectAssigningCapabilityToMerchantWhenRequestBodyIsMissingCapabilityId() {
        long timestamp = System.currentTimeMillis();
        String merchantPayload = """
                        {
                          "legalName": "Capability Test Merchant LLC",
                          "tradeName": "Capability Store",
                          "registrationNo": "CR-%d",
                          "businessType": "CORPORATION",
              "userId": %d
            }
            """.formatted(timestamp, System.currentTimeMillis() % 100_000);
        Response createResponse = given().contentType(ContentType.JSON).body(merchantPayload).when().post("/api/v1/merchants").then().statusCode(anyOf(is(200), is(201))).extract().response();
        String merchantId = createResponse.path("data.id") != null ? createResponse.path("data.id") : createResponse.path("id");
        Assert.assertNotNull(merchantId, "Precondition failed: Merchant creation did not return ID");
        String emptyPayload = """
            {
              "capabilityId": "generated-capabilityId"
            }
            """;
        given().contentType(ContentType.JSON).body(emptyPayload).when().post("/api/v1/merchants/{merchantId}/capabilities", merchantId).then().statusCode(400);
    }

    // 3836dee-TC-018
    @Test
    public void rejectMerchantOnboardingWhenRegistrationNumberAlreadyExists() {
        String registrationNo = "CR-" + System.currentTimeMillis();
        String merchantPayload = """
                        {
                          "legalName": "Duplicate Reg Merchant LLC",
                          "tradeName": "Duplicate Reg Store",
                          "registrationNo": "%s",
                          "businessType": "CORPORATION",
                          "contactEmail": "duplicate@merchant.com",
              "userId": %d
            }
            """.formatted(registrationNo, System.currentTimeMillis() % 100_000);
        given().contentType(ContentType.JSON).body(merchantPayload).when().post("/api/v1/merchants").then().statusCode(anyOf(is(200), is(201)));
        given().contentType(ContentType.JSON).body(merchantPayload).when().post("/api/v1/merchants").then().statusCode(anyOf(is(400), is(409)));
    }

    // 3836dee-TC-019
    @Test
    public void rejectMerchantOnboardingWhenRequiredFieldsAreMissing() {
        String invalidPayload = """
                        {
                          "contactEmail": "invalid@merchant.com",
                          "country": "SA",
              "userId": 1234,
              "legalName": "ABC Trading Company LLC",
              "tradeName": "ABC Store",
              "registrationNo": "CR-1234567890",
              "businessType": "PRA"
            }
            """;
        given().contentType(ContentType.JSON).body(invalidPayload).when().post("/api/v1/merchants").then().statusCode(400);
    }

    // 3836dee-TC-020
    @Test
    public void rejectMerchantOnboardingWhenMerchantCategoryCodeExceedsAllowedLength() {
        long timestamp = System.currentTimeMillis();
        String invalidPayload = """
                        {
                          "legalName": "Invalid MCC Merchant LLC",
                          "tradeName": "Invalid MCC Store",
                          "registrationNo": "CR-%d",
                          "merchantCategoryCode": "54111",
                          "businessType": "LLC",
              "userId": %d
            }
            """.formatted(timestamp, System.currentTimeMillis() % 100_000);
        given().contentType(ContentType.JSON).body(invalidPayload).when().post("/api/v1/merchants").then().statusCode(400);
    }

    // 3836dee-TC-021
    @Test
    public void rejectDocumentUploadForNonExistentMerchant() {
        String nonExistentMerchantId = "a1b2c3d4-0000-0000-0000-000000000000";
        given().queryParam("documentType", "BUSINESS_LICENSE").multiPart("file", "sample.pdf", "dummy content".getBytes()).when().post("/api/v1/merchants/{merchantId}/documents", nonExistentMerchantId).then().statusCode(404);
    }

    // 3836dee-TC-022
    @Test
    public void rejectDocumentDeletionWhenDocumentIdBelongsToDifferentMerchant() {
        // 1. Create Merchant A
        String merchantABody = """
                        {
                          "legalName": "Merchant A LLC",
                          "tradeName": "Merchant A",
                          "registrationNo": "CR-%d",
                          "businessType": "CORPORATION",
              "userId": %d
            }
            """.formatted(System.currentTimeMillis(), System.currentTimeMillis() % 100_000);
        Response merchantAResp = given().contentType(ContentType.JSON).body(merchantABody).when().post("/api/v1/merchants").then().statusCode(anyOf(is(200), is(201))).extract().response();
        String merchantAId = merchantAResp.path("data.id") != null ? merchantAResp.path("data.id") : merchantAResp.path("id");
        Assert.assertNotNull(merchantAId, "Precondition failed: Merchant A created without ID");
        // 2. Create Merchant B
        String merchantBBody = """
                        {
                          "legalName": "Merchant B LLC",
                          "tradeName": "Merchant B",
                          "registrationNo": "CR-%d",
                          "businessType": "CORPORATION",
              "userId": %d
            }
            """.formatted(System.currentTimeMillis() + 1, System.currentTimeMillis() % 100_000);
        Response merchantBResp = given().contentType(ContentType.JSON).body(merchantBBody).when().post("/api/v1/merchants").then().statusCode(anyOf(is(200), is(201))).extract().response();
        String merchantBId = merchantBResp.path("data.id") != null ? merchantBResp.path("data.id") : merchantBResp.path("id");
        Assert.assertNotNull(merchantBId, "Precondition failed: Merchant B created without ID");
        // 3. Upload Document for Merchant B
        Response docBResp = given().queryParam("documentType", "BUSINESS_LICENSE").multiPart("file", "docB.pdf", "merchant b file content".getBytes()).when().post("/api/v1/merchants/{merchantId}/documents", merchantBId).then().statusCode(anyOf(is(200), is(201))).extract().response();
        String docBId = docBResp.path("data.id") != null ? docBResp.path("data.id") : docBResp.path("id");
        Assert.assertNotNull(docBId, "Precondition failed: Document B created without ID");
        // 4. Attempt to delete Merchant B's document using Merchant A's ID
        given().when().delete("/api/v1/merchants/{merchantId}/documents/{documentId}", merchantAId, docBId).then().statusCode(404);
    }

    // 3836dee-TC-023
    @Test
    public void rejectQrCodeGenerationWhenRequestBodyIsMissingMandatoryFields() {
        String requestBody = """
                        {
                          "storeId": "00000000-0000-0000-0000-000000000001",
              "merchantId": "generated-merchantId",
              "qrType": "STATIC"
            }
            """;
        given().contentType(ContentType.JSON).body(requestBody).when().post("/api/v1/qr-codes").then().statusCode(anyOf(is(400), is(422)));
    }

    // 3836dee-TC-024
    @Test
    public void rejectTerminalRegistrationWhenSerialNumberIsAlreadyRegistered() {
        long timestamp = System.currentTimeMillis();
        String createMerchantBody = """
                        {
                          "legalName": "Merchant %d",
                          "tradeName": "Trade %d",
                          "registrationNo": "REG-%d",
                          "businessType": "CORPORATION",
              "userId": %d
            }
            """.formatted(timestamp, timestamp, timestamp, System.currentTimeMillis() % 100_000);
        Response merchantResp = given().contentType(ContentType.JSON).body(createMerchantBody).when().post("/api/v1/merchants").then().statusCode(anyOf(is(200), is(201))).extract().response();
        String merchantId = merchantResp.path("data.id") != null ? merchantResp.path("data.id") : merchantResp.path("id");
        Assert.assertNotNull(merchantId, "Precondition failed: Merchant ID creation returned null");
        String createStoreBody = """
            {
              "name": "Store %d"
            }
            """.formatted(timestamp);
        Response storeResp = given().contentType(ContentType.JSON).body(createStoreBody).when().post("/api/v1/merchants/{merchantId}/stores", merchantId).then().statusCode(anyOf(is(200), is(201))).extract().response();
        String storeId = storeResp.path("data.id") != null ? storeResp.path("data.id") : storeResp.path("id");
        Assert.assertNotNull(storeId, "Precondition failed: Store ID creation returned null");
        String duplicateSerial = "SN-DUP-" + timestamp;
        String firstTerminalBody = """
            {
              "merchantId": "%s",
              "storeId": "%s",
              "serialNumber": "%s",
              "model": "A920 Pro",
              "manufacturer": "PAX Technology"
            }
            """.formatted(merchantId, storeId, duplicateSerial);
        given().contentType(ContentType.JSON).body(firstTerminalBody).when().post("/api/v1/terminals").then().statusCode(anyOf(is(200), is(201)));
        given().contentType(ContentType.JSON).body(firstTerminalBody).when().post("/api/v1/terminals").then().statusCode(anyOf(is(400), is(409)));
    }

    // 3836dee-TC-025
    @Test
    public void rejectTerminalRegistrationWhenMandatoryStoreIdOrMerchantIdIsMissing() {
        long timestamp = System.currentTimeMillis();
        String requestBody = """
                        {
                          "merchantId": "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11",
                          "serialNumber": "SN-UNIQUE-%d",
                          "model": "A920 Pro",
              "storeId": "%s"
            }
            """.formatted(timestamp, "gen-" + System.currentTimeMillis());
        given().contentType(ContentType.JSON).body(requestBody).when().post("/api/v1/terminals").then().statusCode(anyOf(is(400), is(422)));
    }

}
