package com.company.aiqa.generated;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import java.math.BigDecimal;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 * Automated API tests for commit 12878fa9cca486a5d76d28fae68ee1e4dff603e5.
 * Generated by ai-qa-platform from that commit's manual test cases.
 */
public class AutomationTest_12878fa9cca486a5d76d28fae68ee1e4dff603e5 {

    @BeforeClass
    public void setup() {
        RestAssured.baseURI = System.getProperty("baseUri", "http://localhost:8082");
    }

    // TC-003 - Verify payment made during order creation is recorded and reflected in today's earnings
    @Test
    public void verifyPaymentDuringOrderCreationReflectsInTodaysEarnings() {
        // Precondition: Create a shop
        String shopBody = """
            {
              "shopName": "Shop_%d",
              "shopPhone": "1234567890",
              "latitude": 23.8103,
              "longitude": 90.4125,
              "ownerName": "Owner",
              "email": "owner_%d@example.com",
              "address": "Dhaka",
              "areaId": 1,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), System.currentTimeMillis());
        Long shopId = given().contentType(ContentType.JSON).body(shopBody).when().post("/api/areas/1/shops").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Precondition: Create an item
        String itemBody = """
            {
              "nameEn": "Shirt_%d",
              "nameBn": "শার্ট",
              "status": "ACTIVE",
              "parameters": []
            }
            """.formatted(System.currentTimeMillis());
        Long itemId = given().contentType(ContentType.JSON).body(itemBody).when().post("/api/items").then().statusCode(anyOf(is(200), is(201))).extract().path("data.id");
        // Precondition: Get today's earnings before order creation
        BigDecimal todaysEarningsBefore = given().when().get("/api/dashboard/summary").then().statusCode(200).extract().path("data.todaysEarnings");
        // Create order with payment
        String orderBody = """
            {
              "shopId": %d,
              "customerName": "Customer",
              "customerPhone": "9876543210",
              "customerGender": "MALE",
              "paidAmount": 500,
              "deliveryDate": "2023-12-31",
              "items": [
                {
                  "itemId": %d,
                  "measurementGroups": [
                    {
                      "specialInstruction": "None",
                      "makingCharge": 500,
                      "measurements": []
                    }
                  ]
                }
              ]
            }
            """.formatted(shopId, itemId);
        given().contentType(ContentType.JSON).body(orderBody).when().post("/api/orders").then().statusCode(anyOf(is(200), is(201)));
        // Verify today's earnings increased by paid amount
        given().when().get("/api/dashboard/summary").then().statusCode(200).body("data.todaysEarnings", equalTo(todaysEarningsBefore.add(new BigDecimal(500)).floatValue()));
    }

    // TC-004 - Verify total order amount reflects the sum of all order totals in the system
    @Test
    public void verifyTotalOrderAmountReflectsSumOfAllOrders() {
        // Precondition: Create a shop
        String shopBody = """
            {
              "shopName": "Shop_%d",
              "shopPhone": "1234567890",
              "latitude": 23.8103,
              "longitude": 90.4125,
              "ownerName": "Owner",
              "email": "owner_%d@example.com",
              "address": "Dhaka",
              "areaId": 1,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), System.currentTimeMillis());
        Long shopId = given().contentType(ContentType.JSON).body(shopBody).when().post("/api/areas/1/shops").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Precondition: Create items
        String itemBody1 = """
            {
              "nameEn": "Shirt_%d",
              "nameBn": "শার্ট",
              "status": "ACTIVE",
              "parameters": []
            }
            """.formatted(System.currentTimeMillis());
        Long itemId1 = given().contentType(ContentType.JSON).body(itemBody1).when().post("/api/items").then().statusCode(anyOf(is(200), is(201))).extract().path("data.id");
        String itemBody2 = """
            {
              "nameEn": "Pant_%d",
              "nameBn": "প্যান্ট",
              "status": "ACTIVE",
              "parameters": []
            }
            """.formatted(System.currentTimeMillis());
        Long itemId2 = given().contentType(ContentType.JSON).body(itemBody2).when().post("/api/items").then().statusCode(anyOf(is(200), is(201))).extract().path("data.id");
        // Precondition: Create orders
        String orderBody1 = """
            {
              "shopId": %d,
              "customerName": "Customer1",
              "customerPhone": "9876543210",
              "customerGender": "MALE",
              "paidAmount": 0,
              "deliveryDate": "2023-12-31",
              "items": [
                {
                  "itemId": %d,
                  "measurementGroups": [
                    {
                      "specialInstruction": "None",
                      "makingCharge": 1000,
                      "measurements": []
                    }
                  ]
                }
              ]
            }
            """.formatted(shopId, itemId1);
        given().contentType(ContentType.JSON).body(orderBody1).when().post("/api/orders").then().statusCode(anyOf(is(200), is(201)));
        String orderBody2 = """
            {
              "shopId": %d,
              "customerName": "Customer2",
              "customerPhone": "9876543211",
              "customerGender": "FEMALE",
              "paidAmount": 0,
              "deliveryDate": "2023-12-31",
              "items": [
                {
                  "itemId": %d,
                  "measurementGroups": [
                    {
                      "specialInstruction": "None",
                      "makingCharge": 2000,
                      "measurements": []
                    }
                  ]
                }
              ]
            }
            """.formatted(shopId, itemId2);
        given().contentType(ContentType.JSON).body(orderBody2).when().post("/api/orders").then().statusCode(anyOf(is(200), is(201)));
        // Verify total order amount
        given().when().get("/api/dashboard/summary").then().statusCode(200).body("data.totalOrderAmount", equalTo(3000.0F));
    }

    // TC-005 - Omitted: No HTTP surface for dashboard summary with shop ID format validation
    // TC-006 - Omitted: No HTTP surface for dashboard summary with non-existent shop ID
    /**
     * TC-0b31caa-TC-001 - Attempt to record a payment with a negative payment amount during order creation
     */
    @Test
    public void createOrderWithNegativePaidAmount() {
        // Precondition: Create a shop
        String shopBody = """
            {
              "shopName": "Shop_%d",
              "shopPhone": "1234567890",
              "latitude": 23.8103,
              "longitude": 90.4125,
              "ownerName": "Owner",
              "email": "owner_%d@example.com",
              "address": "Dhaka",
              "areaId": 1,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), System.currentTimeMillis());
        Long shopId = given().contentType(ContentType.JSON).body(shopBody).when().post("/api/areas/1/shops").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Precondition: Create an item
        String itemBody = """
            {
              "nameEn": "Shirt_%d",
              "nameBn": "শার্ট",
              "status": "ACTIVE",
              "parameters": []
            }
            """.formatted(System.currentTimeMillis());
        Long itemId = given().contentType(ContentType.JSON).body(itemBody).when().post("/api/items").then().statusCode(anyOf(is(200), is(201))).extract().path("data.id");
        // Test: Create order with negative paid amount
        String orderBody = """
            {
              "shopId": %d,
              "customerName": "Customer",
              "customerPhone": "1234567890",
              "customerGender": "MALE",
              "paidAmount": -100,
              "deliveryDate": "2023-12-31",
              "items": [
                {
                  "itemId": %d,
                  "measurementGroups": [
                    {
                      "specialInstruction": "None",
                      "makingCharge": 500,
                      "measurements": []
                    }
                  ]
                }
              ]
            }
            """.formatted(shopId, itemId);
        given().contentType(ContentType.JSON).body(orderBody).when().post("/api/orders").then().statusCode(400).body("message", containsString("Paid Amount must be a non-negative value"));
    }

    /**
     * TC-007 - Attempt to record a payment with a non-numeric payment amount during order creation
     */
    @Test
    public void createOrderWithNonNumericPaidAmount() {
        // Precondition: Create a shop
        String shopBody = """
            {
              "shopName": "Shop_%d",
              "shopPhone": "1234567890",
              "latitude": 23.8103,
              "longitude": 90.4125,
              "ownerName": "Owner",
              "email": "owner_%d@example.com",
              "address": "Dhaka",
              "areaId": 1,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), System.currentTimeMillis());
        Long shopId = given().contentType(ContentType.JSON).body(shopBody).when().post("/api/areas/1/shops").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Precondition: Create an item
        String itemBody = """
            {
              "nameEn": "Shirt_%d",
              "nameBn": "শার্ট",
              "status": "ACTIVE",
              "parameters": []
            }
            """.formatted(System.currentTimeMillis());
        Long itemId = given().contentType(ContentType.JSON).body(itemBody).when().post("/api/items").then().statusCode(anyOf(is(200), is(201))).extract().path("data.id");
        // Test: Create order with non-numeric paid amount
        String orderBody = """
            {
              "shopId": %d,
              "customerName": "Customer",
              "customerPhone": "1234567890",
              "customerGender": "MALE",
              "paidAmount": "abc",
              "deliveryDate": "2023-12-31",
              "items": [
                {
                  "itemId": %d,
                  "measurementGroups": [
                    {
                      "specialInstruction": "None",
                      "makingCharge": 500,
                      "measurements": []
                    }
                  ]
                }
              ]
            }
            """.formatted(shopId, itemId);
        given().contentType(ContentType.JSON).body(orderBody).when().post("/api/orders").then().statusCode(400).body("message", containsString("Paid Amount must be a valid numeric value"));
    }

    /**
     * TC-008 - Attempt to record a payment for an order with a null paid amount during order creation
     */
    @Test
    public void createOrderWithNullPaidAmount() {
        // Precondition: Create a shop
        String shopBody = """
            {
              "shopName": "Shop_%d",
              "shopPhone": "1234567890",
              "latitude": 23.8103,
              "longitude": 90.4125,
              "ownerName": "Owner",
              "email": "owner_%d@example.com",
              "address": "Dhaka",
              "areaId": 1,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), System.currentTimeMillis());
        Long shopId = given().contentType(ContentType.JSON).body(shopBody).when().post("/api/areas/1/shops").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Precondition: Create an item
        String itemBody = """
            {
              "nameEn": "Shirt_%d",
              "nameBn": "শার্ট",
              "status": "ACTIVE",
              "parameters": []
            }
            """.formatted(System.currentTimeMillis());
        Long itemId = given().contentType(ContentType.JSON).body(itemBody).when().post("/api/items").then().statusCode(anyOf(is(200), is(201))).extract().path("data.id");
        // Test: Create order with null paid amount (omitted field)
        String orderBody = """
            {
              "shopId": %d,
              "customerName": "Customer",
              "customerPhone": "1234567890",
              "customerGender": "MALE",
              "deliveryDate": "2023-12-31",
              "items": [
                {
                  "itemId": %d,
                  "measurementGroups": [
                    {
                      "specialInstruction": "None",
                      "makingCharge": 500,
                      "measurements": []
                    }
                  ]
                }
              ]
            }
            """.formatted(shopId, itemId);
        given().contentType(ContentType.JSON).body(orderBody).when().post("/api/orders").then().statusCode(anyOf(is(200), is(201))).body("data.paidAmount", equalTo(0));
    }

    /**
     * Test Case ID: TC-009
     * Attempt to create an order with a paid amount exceeding the total order amount
     */
    @Test
    public void attemptCreateOrderWithExcessPaidAmount() {
        // Precondition: Create a shop
        String shopBody = """
            {
              "shopName": "Shop_%d",
              "shopPhone": "1234567890",
              "latitude": 23.8103,
              "longitude": 90.4125,
              "ownerName": "Owner",
              "email": "owner_%d@example.com",
              "address": "Dhaka",
              "areaId": 1,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), System.currentTimeMillis());
        Long shopId = given().contentType(ContentType.JSON).body(shopBody).when().post("/api/areas/1/shops").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Precondition: Create an item
        String itemBody = """
            {
              "nameEn": "Shirt_%d",
              "nameBn": "শার্ট",
              "status": "ACTIVE",
              "parameters": []
            }
            """.formatted(System.currentTimeMillis());
        Long itemId = given().contentType(ContentType.JSON).body(itemBody).when().post("/api/items").then().statusCode(anyOf(is(200), is(201))).extract().path("data.id");
        // Test: Create order with paid amount exceeding total
        String orderBody = """
            {
              "shopId": %d,
              "customerName": "Customer",
              "customerPhone": "1234567890",
              "customerGender": "MALE",
              "paidAmount": 1500,
              "deliveryDate": "2023-12-31",
              "items": [
                {
                  "itemId": %d,
                  "measurementGroups": [
                    {
                      "specialInstruction": "None",
                      "makingCharge": 1000,
                      "measurements": []
                    }
                  ]
                }
              ]
            }
            """.formatted(shopId, itemId);
        given().contentType(ContentType.JSON).body(orderBody).when().post("/api/orders").then().statusCode(400).body("message", containsString("Paid Amount cannot exceed total order amount"));
    }

    /**
     * Test Case ID: TC-011
     * Attempt to update the status of a non-existent order item
     */
    @Test
    public void attemptUpdateNonExistentOrderItemStatus() {
        // Precondition: Create a shop
        String shopBody = """
            {
              "shopName": "Shop_%d",
              "shopPhone": "1234567890",
              "latitude": 23.8103,
              "longitude": 90.4125,
              "ownerName": "Owner",
              "email": "owner_%d@example.com",
              "address": "Dhaka",
              "areaId": 1,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), System.currentTimeMillis());
        Long shopId = given().contentType(ContentType.JSON).body(shopBody).when().post("/api/areas/1/shops").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Precondition: Create an item
        String itemBody = """
            {
              "nameEn": "Shirt_%d",
              "nameBn": "শার্ট",
              "status": "ACTIVE",
              "parameters": []
            }
            """.formatted(System.currentTimeMillis());
        Long itemId = given().contentType(ContentType.JSON).body(itemBody).when().post("/api/items").then().statusCode(anyOf(is(200), is(201))).extract().path("data.id");
        // Precondition: Create an order
        String orderBody = """
            {
              "shopId": %d,
              "customerName": "Customer",
              "customerPhone": "1234567890",
              "customerGender": "MALE",
              "paidAmount": 1000,
              "deliveryDate": "2023-12-31",
              "items": [
                {
                  "itemId": %d,
                  "measurementGroups": [
                    {
                      "specialInstruction": "None",
                      "makingCharge": 1000,
                      "measurements": []
                    }
                  ]
                }
              ]
            }
            """.formatted(shopId, itemId);
        Long orderId = given().contentType(ContentType.JSON).body(orderBody).when().post("/api/orders").then().statusCode(anyOf(is(200), is(201))).extract().path("data.id");
        // Test: Update non-existent order item status
        String updateBody = """
            {
              "newStatus": "DELIVERED"
            }
            """;
        given().contentType(ContentType.JSON).body(updateBody).when().put("/api/orders/items/999999/status").then().statusCode(404).body("message", containsString("Order item with ID 999999 does not exist"));
    }

    /**
     * Test Case ID: d217aa0-TC-009
     * Attempt to fetch dashboard summary as an unauthorized user (non-SHOP_OWNER role)
     */
    @Test
    public void attemptFetchDashboardSummaryAsUnauthorizedUser() {
        // Precondition: Sign in as CUSTOMER
        String signInBody = """
            {
              "username": "customer_%d@example.com",
              "password": "password"
            }
            """.formatted(System.currentTimeMillis());
        String token = given().contentType(ContentType.JSON).body(signInBody).when().post("/api/auth/signin").then().statusCode(200).extract().path("data.token");
        // Test: Fetch dashboard summary as CUSTOMER
        given().header("Authorization", "Bearer " + token).when().get("/api/dashboard/summary").then().statusCode(403).body("message", containsString("not authorized"));
    }

    /**
     * Test Case ID: TC-010
     * Attempt to fetch dashboard summary without authentication
     */
    @Test
    public void attemptFetchDashboardSummaryWithoutAuthentication() {
        given().when().get("/api/dashboard/summary").then().statusCode(401).body("message", containsString("authentication is required"));
    }

    /**
     * Test Case ID: TC-012
     * Attempt to update an order item status to an invalid transition
     */
    @Test
    public void attemptInvalidOrderItemStatusTransition() {
        // Precondition: Create a shop
        String shopBody = """
            {
              "shopName": "Shop_%d",
              "shopPhone": "1234567890",
              "latitude": 23.8103,
              "longitude": 90.4125,
              "ownerName": "Owner",
              "email": "owner_%d@example.com",
              "address": "Dhaka",
              "areaId": 1,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), System.currentTimeMillis());
        Long shopId = given().contentType(ContentType.JSON).body(shopBody).when().post("/api/areas/1/shops").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Precondition: Create an item
        String itemBody = """
            {
              "nameEn": "Shirt_%d",
              "nameBn": "শার্ট",
              "status": "ACTIVE",
              "parameters": []
            }
            """.formatted(System.currentTimeMillis());
        Long itemId = given().contentType(ContentType.JSON).body(itemBody).when().post("/api/items").then().statusCode(anyOf(is(200), is(201))).extract().path("data.id");
        // Precondition: Create an order
        String orderBody = """
            {
              "shopId": %d,
              "customerName": "Customer",
              "customerPhone": "1234567890",
              "customerGender": "MALE",
              "paidAmount": 1000,
              "deliveryDate": "2023-12-31",
              "items": [
                {
                  "itemId": %d,
                  "measurementGroups": [
                    {
                      "specialInstruction": "None",
                      "makingCharge": 1000,
                      "measurements": []
                    }
                  ]
                }
              ]
            }
            """.formatted(shopId, itemId);
        Long orderId = given().contentType(ContentType.JSON).body(orderBody).when().post("/api/orders").then().statusCode(anyOf(is(200), is(201))).extract().path("data.id");
        // Precondition: Get order item ID (assuming first item's first measurement group)
        Long orderItemId = given().when().get("/api/orders/{orderId}", orderId).then().statusCode(200).extract().path("data.items[0].id");
        // Test: Attempt invalid status transition (PENDING -> DELIVERED)
        String updateBody = """
            {
              "newStatus": "DELIVERED"
            }
            """;
        given().contentType(ContentType.JSON).body(updateBody).when().put("/api/orders/items/{orderItemId}/status", orderItemId).then().statusCode(400).body("message", containsString("status transition from PENDING to DELIVERED is not allowed"));
    }

    // TC-013 - Attempt to create an order with a future payment date (invalid for initial payment)
    @Test
    public void createOrderWithFuturePaymentDate() {
        // Precondition: Create a shop
        String shopBody = """
            {
              "shopName": "Shop_%d",
              "shopPhone": "1234567890",
              "latitude": 23.8103,
              "longitude": 90.4125,
              "ownerName": "Owner",
              "email": "owner_%d@example.com",
              "address": "Dhaka",
              "areaId": 1,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), System.currentTimeMillis());
        Long shopId = given().contentType(ContentType.JSON).body(shopBody).when().post("/api/areas/1/shops").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Precondition: Create an item
        String itemBody = """
            {
              "nameEn": "Shirt_%d",
              "nameBn": "শার্ট",
              "status": "ACTIVE",
              "parameters": []
            }
            """.formatted(System.currentTimeMillis());
        Long itemId = given().contentType(ContentType.JSON).body(itemBody).when().post("/api/items").then().statusCode(anyOf(is(200), is(201))).extract().path("data.id");
        // Test: Create order with future payment date
        String futureDate = LocalDate.now().plusDays(1).format(DateTimeFormatter.ISO_DATE);
        String orderBody = """
            {
              "shopId": %d,
              "customerName": "John Doe",
              "customerPhone": "1234567890",
              "customerGender": "MALE",
              "paidAmount": 2000,
              "trialDate": "%s",
              "deliveryDate": "%s",
              "items": [
                {
                  "itemId": %d,
                  "measurementGroups": [
                    {
                      "specialInstruction": "None",
                      "makingCharge": 2000,
                      "measurements": []
                    }
                  ]
                }
              ]
            }
            """.formatted(shopId, futureDate, futureDate, itemId);
        given().contentType(ContentType.JSON).body(orderBody).when().post("/api/orders").then().statusCode(200).body("data.paidAmount", equalTo(2000)).body("data.paymentDate", not(equalTo(futureDate)));
    }

    // TC-014 - Attempt to create an order with a malformed payment date format
    @Test
    public void createOrderWithMalformedPaymentDate() {
        // Precondition: Create a shop
        String shopBody = """
            {
              "shopName": "Shop_%d",
              "shopPhone": "1234567890",
              "latitude": 23.8103,
              "longitude": 90.4125,
              "ownerName": "Owner",
              "email": "owner_%d@example.com",
              "address": "Dhaka",
              "areaId": 1,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), System.currentTimeMillis());
        Long shopId = given().contentType(ContentType.JSON).body(shopBody).when().post("/api/areas/1/shops").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Precondition: Create an item
        String itemBody = """
            {
              "nameEn": "Shirt_%d",
              "nameBn": "শার্ট",
              "status": "ACTIVE",
              "parameters": []
            }
            """.formatted(System.currentTimeMillis());
        Long itemId = given().contentType(ContentType.JSON).body(itemBody).when().post("/api/items").then().statusCode(anyOf(is(200), is(201))).extract().path("data.id");
        // Test: Create order with malformed date
        String orderBody = """
            {
              "shopId": %d,
              "customerName": "John Doe",
              "customerPhone": "1234567890",
              "customerGender": "MALE",
              "paidAmount": 2000,
              "trialDate": "31-13-2023",
              "deliveryDate": "2023-12-31",
              "items": [
                {
                  "itemId": %d,
                  "measurementGroups": [
                    {
                      "specialInstruction": "None",
                      "makingCharge": 2000,
                      "measurements": []
                    }
                  ]
                }
              ]
            }
            """.formatted(shopId, itemId);
        given().contentType(ContentType.JSON).body(orderBody).when().post("/api/orders").then().statusCode(400).body("message", containsString("date format"));
    }

    // TC-017 - Verify that initial payment during order creation is recorded and reflected in 'Earning Today' on the dashboard
    @Test
    public void verifyInitialPaymentReflectedInEarningToday() {
        // Precondition: Create a shop
        String shopBody = """
            {
              "shopName": "Shop_%d",
              "shopPhone": "1234567890",
              "latitude": 23.8103,
              "longitude": 90.4125,
              "ownerName": "Owner",
              "email": "owner_%d@example.com",
              "address": "Dhaka",
              "areaId": 1,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), System.currentTimeMillis());
        Long shopId = given().contentType(ContentType.JSON).body(shopBody).when().post("/api/areas/1/shops").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Precondition: Create an item
        String itemBody = """
            {
              "nameEn": "Shirt_%d",
              "nameBn": "শার্ট",
              "status": "ACTIVE",
              "parameters": []
            }
            """.formatted(System.currentTimeMillis());
        Long itemId = given().contentType(ContentType.JSON).body(itemBody).when().post("/api/items").then().statusCode(anyOf(is(200), is(201))).extract().path("data.id");
        // Test: Create order with payment
        String orderBody = """
            {
              "shopId": %d,
              "customerName": "John Doe",
              "customerPhone": "1234567890",
              "customerGender": "MALE",
              "paidAmount": 2000,
              "deliveryDate": "2023-12-31",
              "items": [
                {
                  "itemId": %d,
                  "measurementGroups": [
                    {
                      "specialInstruction": "None",
                      "makingCharge": 2000,
                      "measurements": []
                    }
                  ]
                }
              ]
            }
            """.formatted(shopId, itemId);
        given().contentType(ContentType.JSON).body(orderBody).when().post("/api/orders").then().statusCode(200);
        // Verify dashboard reflects the payment
        given().when().get("/api/dashboard/summary").then().statusCode(200).body("data.earningToday", equalTo(2000));
    }

    // TC-015 - Verify that dashboard financial totals are calculated only for the authenticated shop owner's data
    @Test
    public void verifyDashboardFinancialTotalsPerShop() {
        // Precondition: Create Shop A
        String shopABody = """
            {
              "shopName": "Shop_A_%d",
              "shopPhone": "1234567890",
              "latitude": 23.8103,
              "longitude": 90.4125,
              "ownerName": "Owner A",
              "email": "owner_a_%d@example.com",
              "address": "Dhaka",
              "areaId": 1,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), System.currentTimeMillis());
        Long shopAId = given().contentType(ContentType.JSON).body(shopABody).when().post("/api/areas/1/shops").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Precondition: Create Shop B
        String shopBBody = """
            {
              "shopName": "Shop_B_%d",
              "shopPhone": "0987654321",
              "latitude": 23.8103,
              "longitude": 90.4125,
              "ownerName": "Owner B",
              "email": "owner_b_%d@example.com",
              "address": "Dhaka",
              "areaId": 1,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), System.currentTimeMillis());
        Long shopBId = given().contentType(ContentType.JSON).body(shopBBody).when().post("/api/areas/1/shops").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Precondition: Create items for Shop A
        String itemABody = """
            {
              "nameEn": "Shirt_A_%d",
              "nameBn": "শার্ট",
              "status": "ACTIVE",
              "parameters": []
            }
            """.formatted(System.currentTimeMillis());
        Long itemAId = given().contentType(ContentType.JSON).body(itemABody).when().post("/api/items").then().statusCode(anyOf(is(200), is(201))).extract().path("data.id");
        // Precondition: Create items for Shop B
        String itemBBody = """
            {
              "nameEn": "Shirt_B_%d",
              "nameBn": "শার্ট",
              "status": "ACTIVE",
              "parameters": []
            }
            """.formatted(System.currentTimeMillis());
        Long itemBId = given().contentType(ContentType.JSON).body(itemBBody).when().post("/api/items").then().statusCode(anyOf(is(200), is(201))).extract().path("data.id");
        // Precondition: Create orders for Shop A
        String orderA1Body = """
            {
              "shopId": %d,
              "customerName": "Customer A1",
              "customerPhone": "1111111111",
              "customerGender": "MALE",
              "paidAmount": 5000,
              "deliveryDate": "2023-12-31",
              "items": [
                {
                  "itemId": %d,
                  "measurementGroups": [
                    {
                      "specialInstruction": "None",
                      "makingCharge": 5000,
                      "measurements": []
                    }
                  ]
                }
              ]
            }
            """.formatted(shopAId, itemAId);
        given().contentType(ContentType.JSON).body(orderA1Body).when().post("/api/orders").then().statusCode(200);
        String orderA2Body = """
            {
              "shopId": %d,
              "customerName": "Customer A2",
              "customerPhone": "2222222222",
              "customerGender": "MALE",
              "paidAmount": 2000,
              "deliveryDate": "2023-12-31",
              "items": [
                {
                  "itemId": %d,
                  "measurementGroups": [
                    {
                      "specialInstruction": "None",
                      "makingCharge": 5000,
                      "measurements": []
                    }
                  ]
                }
              ]
            }
            """.formatted(shopAId, itemAId);
        given().contentType(ContentType.JSON).body(orderA2Body).when().post("/api/orders").then().statusCode(200);
        // Precondition: Create orders for Shop B
        String orderB1Body = """
            {
              "shopId": %d,
              "customerName": "Customer B1",
              "customerPhone": "3333333333",
              "customerGender": "MALE",
              "paidAmount": 7000,
              "deliveryDate": "2023-12-31",
              "items": [
                {
                  "itemId": %d,
                  "measurementGroups": [
                    {
                      "specialInstruction": "None",
                      "makingCharge": 8000,
                      "measurements": []
                    }
                  ]
                }
              ]
            }
            """.formatted(shopBId, itemBId);
        given().contentType(ContentType.JSON).body(orderB1Body).when().post("/api/orders").then().statusCode(200);
        // Test: Verify Shop A dashboard
        given().when().get("/api/dashboard/summary").then().statusCode(200).body("data.earningToday", // Depends on test timing
        anyOf(equalTo(7000), equalTo(0))).body("data.totalDue", equalTo(3000)).body("data.totalEarning", equalTo(7000)).body("data.totalOrderAmount", equalTo(10000));
    }

    private Long shopId;

    private Long itemId;

    private String authToken;

    // TC-018 - Verify that zero initial payment during order creation does not affect 'Earning Today' on the dashboard
    @Test
    public void verifyZeroInitialPaymentDoesNotAffectEarningToday() {
        String orderBody = """
            {
              "shopId": %d,
              "customerName": "Jane Doe",
              "customerPhone": "9876543210",
              "customerGender": "FEMALE",
              "paidAmount": 0,
              "deliveryDate": "2023-12-31",
              "items": [
                {
                  "itemId": %d,
                  "measurementGroups": [
                    {
                      "specialInstruction": "None",
                      "makingCharge": 500,
                      "measurements": []
                    }
                  ]
                }
              ]
            }
            """.formatted(shopId, itemId);
        given().header("Authorization", "Bearer " + authToken).contentType(ContentType.JSON).body(orderBody).when().post("/api/orders").then().statusCode(anyOf(is(200), is(201)));
        given().header("Authorization", "Bearer " + authToken).when().get("/api/dashboard/summary").then().statusCode(200).body("data.earningToday", equalTo(0));
    }

    // 0b31caa-TC-005 - Verify that negative initial payment during order creation is rejected and does not affect dashboard totals
    @Test
    public void verifyNegativeInitialPaymentIsRejected() {
        String orderBody = """
            {
              "shopId": %d,
              "customerName": "Alice Smith",
              "customerPhone": "5551234567",
              "customerGender": "FEMALE",
              "paidAmount": -1000,
              "deliveryDate": "2023-12-31",
              "items": [
                {
                  "itemId": %d,
                  "measurementGroups": [
                    {
                      "specialInstruction": "None",
                      "makingCharge": 500,
                      "measurements": []
                    }
                  ]
                }
              ]
            }
            """.formatted(shopId, itemId);
        given().header("Authorization", "Bearer " + authToken).contentType(ContentType.JSON).body(orderBody).when().post("/api/orders").then().statusCode(400).body("message", containsString("Paid amount must be a positive value"));
        given().header("Authorization", "Bearer " + authToken).when().get("/api/dashboard/summary").then().statusCode(200).body("data.earningToday", equalTo(0));
    }

    // dbc9d14-TC-016 - Verify that non-numeric initial payment during order creation is rejected and does not affect dashboard totals
    @Test
    public void verifyNonNumericInitialPaymentIsRejected() {
        String orderBody = """
            {
              "shopId": %d,
              "customerName": "Bob Johnson",
              "customerPhone": "5559876543",
              "customerGender": "MALE",
              "paidAmount": "abc",
              "deliveryDate": "2023-12-31",
              "items": [
                {
                  "itemId": %d,
                  "measurementGroups": [
                    {
                      "specialInstruction": "None",
                      "makingCharge": 500,
                      "measurements": []
                    }
                  ]
                }
              ]
            }
            """.formatted(shopId, itemId);
        given().header("Authorization", "Bearer " + authToken).contentType(ContentType.JSON).body(orderBody).when().post("/api/orders").then().statusCode(400).body("message", containsString("Paid amount must be a valid number"));
        given().header("Authorization", "Bearer " + authToken).when().get("/api/dashboard/summary").then().statusCode(200).body("data.earningToday", equalTo(0));
    }

    // TC-019 - Verify that oversized initial payment during order creation is rejected and does not affect dashboard totals
    @Test
    public void verifyOversizedInitialPaymentIsRejected() {
        String orderBody = """
            {
              "shopId": %d,
              "customerName": "Charlie Brown",
              "customerPhone": "5554567890",
              "customerGender": "MALE",
              "paidAmount": 999999999999,
              "deliveryDate": "2023-12-31",
              "items": [
                {
                  "itemId": %d,
                  "measurementGroups": [
                    {
                      "specialInstruction": "None",
                      "makingCharge": 5000,
                      "measurements": []
                    }
                  ]
                }
              ]
            }
            """.formatted(shopId, itemId);
        given().header("Authorization", "Bearer " + authToken).contentType(ContentType.JSON).body(orderBody).when().post("/api/orders").then().statusCode(400).body("message", containsString("Paid amount exceeds maximum allowed value"));
        given().header("Authorization", "Bearer " + authToken).when().get("/api/dashboard/summary").then().statusCode(200).body("data.earningToday", equalTo(0));
    }

    private Long orderId;

    private Long orderItemId;

    private String customerPhone = "5550000001";

    // TC-021 - Verify that updating an order item status to CANCELLED recalculates the order's due amount and reflects it in the dashboard totals
    @Test
    public void verifyOrderItemCancellationRecalculatesDueAmount() {
        String updateStatusBody = """
            {
              "newStatus": "CANCELLED"
            }
            """;
        // Update order item status to CANCELLED
        given().contentType(ContentType.JSON).body(updateStatusBody).when().put("/api/orders/items/{orderItemId}/status", orderItemId).then().statusCode(200);
        // Verify order due amount is recalculated
        given().when().get("/api/orders/{orderId}", orderId).then().statusCode(200).body("data.dueAmount", equalTo(1000.0F));
        // Verify dashboard total due is updated (simplified check)
        given().when().get("/api/dashboard/summary").then().statusCode(200).body("data.totalDue", notNullValue());
    }

    // TC-022 - Verify that updating an order item status to CANCELLED does not allow negative due amounts
    @Test
    public void verifyOrderItemCancellationDoesNotAllowNegativeDueAmount() {
        // Create a new order with paidAmount = totalAmount (dueAmount = 0)
        String itemBody = """
            {
              "nameEn": "Test Item 2",
              "nameBn": "টেস্ট আইটেম ২",
              "status": "ACTIVE",
              "parameters": []
            }
            """;
        Long itemId = given().contentType(ContentType.JSON).body(itemBody).when().post("/api/items").then().statusCode(anyOf(is(200), is(201))).extract().path("data.id");
        String orderBody = """
            {
              "shopId": %d,
              "customerName": "Test Customer 2",
              "customerPhone": "5550000002",
              "customerGender": "MALE",
              "paidAmount": 5000,
              "deliveryDate": "2023-12-31",
              "items": [
                {
                  "itemId": %d,
                  "measurementGroups": [
                    {
                      "specialInstruction": "None",
                      "makingCharge": 5000,
                      "measurements": []
                    }
                  ]
                }
              ]
            }
            """.formatted(shopId, itemId);
        Long newOrderId = given().contentType(ContentType.JSON).body(orderBody).when().post("/api/orders").then().statusCode(anyOf(is(200), is(201))).extract().path("data.id");
        Long newOrderItemId = given().when().get("/api/orders/{orderId}", newOrderId).then().statusCode(200).extract().path("data.items[0].id");
        String updateStatusBody = """
            {
              "newStatus": "CANCELLED"
            }
            """;
        // Update order item status to CANCELLED
        given().contentType(ContentType.JSON).body(updateStatusBody).when().put("/api/orders/items/{orderItemId}/status", newOrderItemId).then().statusCode(200);
        // Verify order due amount remains 0
        given().when().get("/api/orders/{orderId}", newOrderId).then().statusCode(200).body("data.dueAmount", equalTo(0.0F));
    }

    // TC-023 - Verify that dashboard financial totals are not affected by rapid successive order creations (rate limiting)
    // Disabled as rate limiting is typically tested via load testing tools
    @Test(enabled = false)
    public void verifyDashboardTotalsNotAffectedByRapidOrderCreations() {
        // This test is conceptual as REST Assured isn't ideal for rate limiting tests
        // In practice, use a load testing tool like JMeter for this scenario
        // Create 10 orders rapidly
        for (int i = 1; i <= 10; i++) {
            String orderBody = """
                {
                  "shopId": %d,
                  "customerName": "Test User %d",
                  "customerPhone": "55500000%02d",
                  "customerGender": "MALE",
                  "paidAmount": 1000,
                  "deliveryDate": "2023-12-31",
                  "items": [
                    {
                      "itemId": %d,
                      "measurementGroups": [
                        {
                          "specialInstruction": "None",
                          "makingCharge": 1000,
                          "measurements": []
                        }
                      ]
                    }
                  ]
                }
                """.formatted(shopId, i, i, itemId);
            given().contentType(ContentType.JSON).body(orderBody).when().post("/api/orders").then().statusCode(// 429 for Too Many Requests
            anyOf(is(200), is(201), is(429)));
        }
        // Check dashboard summary (simplified)
        given().when().get("/api/dashboard/summary").then().statusCode(200).body("data.earningToday", anyOf(equalTo(10000.0F), lessThanOrEqualTo(10000.0F)));
    }

}
