package com.company.aiqa.generated;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;

/**
 * Automated API tests for commit 8d0b5fdc67ee83aafc14e55c26021b323ba4f018.
 * Generated by ai-qa-platform from that commit's manual test cases.
 */
public class AutomationTest_8d0b5fdc67ee83aafc14e55c26021b323ba4f018 {

    @BeforeClass
    public void setup() {
        RestAssured.baseURI = System.getProperty("baseUri", "http://localhost:8082");
    }

    // TC-001 - Create a new offer with a valid name of maximum allowed length
    @Test
    public void createOfferWithMaxLengthName() {
        // 50 chars
        String validName = "SummerSale2024DiscountForAllCustomersBigDeal";
        String requestBody = """
            {
              "name": "%s",
              "discountAmount": 20,
              "validFrom": "%s",
              "validTo": "%s",
              "status": "ACTIVE"
            }
            """.formatted(validName, LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME), LocalDateTime.now().plusDays(7).format(DateTimeFormatter.ISO_LOCAL_DATE_TIME));
        given().contentType(ContentType.JSON).body(requestBody).when().post("/api/offers").then().statusCode(anyOf(is(200), is(201))).body("data.name", equalTo(validName));
    }

    // TC-002 - Verify offer creation fails when 'name' field exceeds the maximum allowed length of 50 characters
    @Test
    public void createOfferWithNameExceedingMaxLength() {
        // 51+ chars
        String invalidName = "This is a very long offer name that exceeds fifty characters";
        String requestBody = """
            {
              "name": "%s",
              "discountAmount": 10,
              "validFrom": "%s",
              "validTo": "%s",
              "status": "ACTIVE"
            }
            """.formatted(invalidName, LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME), LocalDateTime.now().plusDays(1).format(DateTimeFormatter.ISO_LOCAL_DATE_TIME));
        given().contentType(ContentType.JSON).body(requestBody).when().post("/api/offers").then().statusCode(400).body("message", containsString("Offer name must not exceed 50 characters"));
    }

    // 9129733-TC-008 - Verify offer creation fails when 'name' field is missing
    @Test
    public void createOfferWithMissingName() {
        String requestBody = """
            {
              "discountAmount": 10,
              "validFrom": "%s",
              "validTo": "%s",
              "status": "ACTIVE"
            }
            """.formatted(LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME), LocalDateTime.now().plusDays(1).format(DateTimeFormatter.ISO_LOCAL_DATE_TIME));
        given().contentType(ContentType.JSON).body(requestBody).when().post("/api/offers").then().statusCode(400).body("message", containsString("Offer name is required"));
    }

    // TC-003 - Verify offer creation fails when 'name' field contains only whitespace
    @Test
    public void createOfferWithWhitespaceName() {
        String requestBody = """
            {
              "name": "     ",
              "discountAmount": 10,
              "validFrom": "%s",
              "validTo": "%s",
              "status": "ACTIVE"
            }
            """.formatted(LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME), LocalDateTime.now().plusDays(1).format(DateTimeFormatter.ISO_LOCAL_DATE_TIME));
        given().contentType(ContentType.JSON).body(requestBody).when().post("/api/offers").then().statusCode(400).body("message", containsString("Offer name is required"));
    }

    private static final DateTimeFormatter FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss");

    // TC-008 - Create an offer with a name containing Unicode characters and exactly 50 characters
    @Test
    public void createOfferWithUnicodeNameExactly50Characters() {
        String validFrom = LocalDateTime.now().format(FORMATTER);
        String validTo = LocalDateTime.now().plusDays(1).format(FORMATTER);
        String requestBody = """
            {
              "name": "特价优惠2024夏季促销折扣特别优惠现在立减",
              "discountAmount": 10,
              "validFrom": "%s",
              "validTo": "%s",
              "status": "ACTIVE"
            }
            """.formatted(validFrom, validTo);
        given().contentType(ContentType.JSON).body(requestBody).when().post("/api/offers").then().statusCode(anyOf(is(200), is(201))).body("data.name", equalTo("特价优惠2024夏季促销折扣特别优惠现在立减"));
    }

    // TC-011 - Verify that offer creation accepts offer names exactly at the new maximum length limit of 50 characters
    @Test
    public void createOfferWithNameExactly50Characters() {
        String validFrom = LocalDateTime.now().format(FORMATTER);
        String validTo = LocalDateTime.now().plusDays(1).format(FORMATTER);
        String requestBody = """
            {
              "name": "ThisIsAnOfferNameThatIsExactlyFiftyCharactersLong",
              "discountAmount": 10,
              "validFrom": "%s",
              "validTo": "%s",
              "status": "ACTIVE"
            }
            """.formatted(validFrom, validTo);
        given().contentType(ContentType.JSON).body(requestBody).when().post("/api/offers").then().statusCode(anyOf(is(200), is(201))).body("data.name", equalTo("ThisIsAnOfferNameThatIsExactlyFiftyCharactersLong"));
    }

    // 9129733-TC-001 - Verify that offer creation rejects offer names exceeding the new maximum length limit of 50 characters
    @Test
    public void createOfferWithNameExceeding50CharactersShouldFail() {
        String validFrom = LocalDateTime.now().format(FORMATTER);
        String validTo = LocalDateTime.now().plusDays(1).format(FORMATTER);
        String requestBody = """
            {
              "name": "ThisIsAnExcessivelyLongOfferNameThatExceedsFiftyCharacters",
              "discountAmount": 10,
              "validFrom": "%s",
              "validTo": "%s",
              "status": "ACTIVE"
            }
            """.formatted(validFrom, validTo);
        given().contentType(ContentType.JSON).body(requestBody).when().post("/api/offers").then().statusCode(400).body("message", containsString("Offer name must not exceed 50 characters"));
    }

    // TC-009 - Update an existing offer with a name exactly 50 characters long (maximum allowed length)
    @Test
    public void updateExistingOfferWithNameExactly50Characters() {
        String validFrom = LocalDateTime.now().format(FORMATTER);
        String validTo = LocalDateTime.now().plusDays(1).format(FORMATTER);
        // Precondition: Create an offer to update
        String createBody = """
            {
              "name": "Initial Offer Name",
              "discountAmount": 10,
              "validFrom": "%s",
              "validTo": "%s",
              "status": "ACTIVE"
            }
            """.formatted(validFrom, validTo);
        Integer offerId = given().contentType(ContentType.JSON).body(createBody).when().post("/api/offers").then().statusCode(anyOf(is(200), is(201))).extract().path("data.id");
        // Update the offer with a 50-character name
        String updateBody = """
            {
              "name": "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234",
              "discountAmount": 10,
              "validFrom": "%s",
              "validTo": "%s",
              "status": "ACTIVE"
            }
            """.formatted(validFrom, validTo);
        given().contentType(ContentType.JSON).body(updateBody).when().put("/api/offers/{id}", offerId).then().statusCode(200).body("data.name", equalTo("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234"));
    }

    // TC-010 - Update an existing offer with a name exceeding 50 characters (one character over the limit)
    @Test
    public void updateExistingOfferWithNameExceeding50CharactersShouldFail() {
        String validFrom = LocalDateTime.now().format(FORMATTER);
        String validTo = LocalDateTime.now().plusDays(1).format(FORMATTER);
        // Precondition: Create an offer to update
        String createBody = """
            {
              "name": "Initial Offer Name",
              "discountAmount": 10,
              "validFrom": "%s",
              "validTo": "%s",
              "status": "ACTIVE"
            }
            """.formatted(validFrom, validTo);
        Integer offerId = given().contentType(ContentType.JSON).body(createBody).when().post("/api/offers").then().statusCode(anyOf(is(200), is(201))).extract().path("data.id");
        // Attempt to update the offer with a 51-character name
        String updateBody = """
            {
              "name": "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz12345",
              "discountAmount": 10,
              "validFrom": "%s",
              "validTo": "%s",
              "status": "ACTIVE"
            }
            """.formatted(validFrom, validTo);
        given().contentType(ContentType.JSON).body(updateBody).when().put("/api/offers/{id}", offerId).then().statusCode(400).body("message", containsString("Offer name must not exceed 50 characters"));
    }

    /**
     * Test Case ID: TC-012
     * Verify that offer creation rejects offer names with special characters or injection patterns
     * despite being under the 50-character limit.
     */
    @Test
    public void createOfferWithInjectionPatternName() {
        String validFrom = LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME);
        String validTo = LocalDateTime.now().plusDays(1).format(DateTimeFormatter.ISO_LOCAL_DATE_TIME);
        String requestBody = """
            {
              "name": "TestOffer'; DROP TABLE offers--",
              "discountAmount": 10,
              "validFrom": "%s",
              "validTo": "%s",
              "status": "ACTIVE"
            }
            """.formatted(validFrom, validTo);
        given().contentType(ContentType.JSON).body(requestBody).when().post("/api/offers").then().statusCode(anyOf(is(400), is(201))).body(anyOf(// Case 1: Rejected with error message
        containsString("name"), // Case 2: Created with literal name (no SQL execution)
        allOf(hasKey("data"), hasKey("data.name"), "data.name", equalTo("TestOffer'; DROP TABLE offers--"))));
    }

}
