package com.company.aiqa.generated;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.testng.Assert;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;

/**
 * Automated API tests for commit 6a2e08e88139fb601f367a57a5c675b3b5ab9fa1.
 * Generated by ai-qa-platform from that commit's manual test cases.
 */
public class AutomationTest_6a2e08e88139fb601f367a57a5c675b3b5ab9fa1 {

    @BeforeClass
    public void setUpClass() {
        RestAssured.baseURI = System.getProperty("baseUri", "http://localhost:8082");
    }

    // b469760-TC-001
    @Test
    public void userSuccessfullyRequestsOtpAndReceivesHeader() {
        String email = "user_%d@example.com".formatted(System.currentTimeMillis());
        given().queryParam("email", email).when().post("/api/auth/request-otp").then().statusCode(200).header("OTP", notNullValue()).header("OTP", not(emptyString())).body(containsString("OTP Sent to Your Email"));
    }

    // TC-001
    @Test
    public void userRequestsOtpWithUnregisteredEmailAddress() {
        String email = "unregistered_%d@example.com".formatted(System.currentTimeMillis());
        given().queryParam("email", email).when().post("/api/auth/request-otp").then().statusCode(200).header("OTP", notNullValue()).body(containsString("OTP Sent to Your Email"));
    }

    // TC-003
    @Test
    public void requestOtpWithMissingEmailParameter() {
        given().when().post("/api/auth/request-otp").then().statusCode(anyOf(is(400), is(422)));
    }

    // TC-004
    @Test
    public void requestOtpWithEmptyEmailParameter() {
        given().queryParam("email", "").when().post("/api/auth/request-otp").then().statusCode(anyOf(is(400), is(422)));
    }

    // TC-005
    @Test
    public void requestOtpWithMalformedEmailFormat() {
        given().queryParam("email", "invalid-email").when().post("/api/auth/request-otp").then().statusCode(anyOf(is(400), is(422)));
    }

    // TC-006
    @Test
    public void requestOtpWithEmailNotExistingInSystem() {
        given().queryParam("email", "nonexistent@example.com").when().post("/api/auth/request-otp").then().statusCode(anyOf(is(404), is(400)));
    }

    // TC-007
    @Test
    public void requestOtpWithNullEmailParameter() {
        given().when().post("/api/auth/request-otp").then().statusCode(anyOf(is(400), is(422)));
    }

    // TC-008
    @Test
    public void requestOtpWithExtremelyLongEmailAddress() {
        String longEmail = "a".repeat(250) + "@example.com";
        given().queryParam("email", longEmail).when().post("/api/auth/request-otp").then().statusCode(anyOf(is(400), is(422)));
    }

    // TC-009
    @Test
    public void requestOtpWithEmailContainingInvalidSpecialCharacters() {
        given().queryParam("email", "user@name@domain.com").when().post("/api/auth/request-otp").then().statusCode(anyOf(is(400), is(422)));
    }

    // TC-010
    @Test
    public void requestOtpWithPhoneNumberParameter() {
        given().queryParam("phoneNumber", "+1234567890").when().post("/api/auth/request-otp").then().statusCode(400);
    }

    // TC-011
    @Test
    public void requestOtpWithEmptyEmailAddress() {
        given().queryParam("email", "").when().post("/api/auth/request-otp").then().statusCode(400);
    }

    // TC-012
    @Test
    public void requestOtpWithNullEmailAddress() {
        given().when().post("/api/auth/request-otp").then().statusCode(400);
    }

    // TC-013
    @Test
    public void requestOtpWithMalformedEmailAddress() {
        given().queryParam("email", "userexample.com").when().post("/api/auth/request-otp").then().statusCode(400);
    }

    // TC-014
    @Test
    public void requestOtpWithVeryLongEmailAddress() {
        String longEmail = "userwithaverylongemailaddressover255characterslonguserwithaverylongemailaddressover255characterslonguserwithaverylongemailaddressover255characterslonguserwithaverylongemailaddressover255characterslong@example.com";
        given().queryParam("email", longEmail).when().post("/api/auth/request-otp").then().statusCode(400);
    }

    // TC-015
    @Test
    public void requestOtpWithMaxLengthEmail() {
        String email = "userwith255characterslongemailaddressuserwith255characterslongemailaddressuserwith255characterslongemailaddressuser@example.com";
        given().queryParam("email", email).when().post("/api/auth/request-otp").then().statusCode(200).header("OTP", notNullValue()).body(containsString("OTP Sent to Your Email"));
    }

    // TC-016
    @Test
    public void requestOtpDuplicateEmailInQuickSuccession() {
        String email = "user_%d@example.com".formatted(System.currentTimeMillis());
        // First request
        given().queryParam("email", email).when().post("/api/auth/request-otp").then().statusCode(200).header("OTP", notNullValue()).body(containsString("OTP Sent to Your Email"));
        // Immediate second request with the same email
        given().queryParam("email", email).when().post("/api/auth/request-otp").then().statusCode(200).header("OTP", notNullValue()).body(containsString("OTP Sent to Your Email"));
    }

    // TC-017
    @Test
    public void requestOtpWithNonExistentEmail() {
        Response response = given().queryParam("email", "nonexistentuser@example.com").when().post("/api/auth/request-otp").then().statusCode(200).header("OTP", notNullValue()).extract().response();
        Assert.assertTrue(response.asString().contains("OTP Sent to Your Email"), "Response body was: " + response.asString());
    }

    // TC-018
    @Test
    public void requestOtpWithoutProvidingEmail() {
        given().when().post("/api/auth/request-otp").then().statusCode(400);
    }

    // 67212e2-TC-005
    @Test
    public void requestOtpWithValidEmail() {
        Response response = given().queryParam("email", "validuser@example.com").when().post("/api/auth/request-otp").then().statusCode(200).header("OTP", notNullValue()).extract().response();
        Assert.assertTrue(response.asString().contains("OTP Sent to Your Email"), "Response body was: " + response.asString());
    }

}
