package com.company.aiqa.generated;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;
import org.hamcrest.Matchers;
import org.testng.annotations.AfterClass;

/**
 * Automated API tests for commit 623fc6e9ce73b237684fc466d47c310fbdf8a8ab.
 * Generated by ai-qa-platform from that commit's manual test cases.
 */
public class AutomationTest_623fc6e9ce73b237684fc466d47c310fbdf8a8ab {

    @BeforeClass
    public void setup() {
        RestAssured.baseURI = System.getProperty("baseUri", "http://localhost:8082");
    }

    // TC-001 - Successfully retrieve all service items
    @Test
    public void retrieveAllServiceItems() {
        // Precondition: At least one service item exists in the system
        String createBody = """
            {
              "name": "Oil Change_%d",
              "description": "Standard oil change service",
              "status": true
            }
            """.formatted(System.currentTimeMillis());
        given().contentType(ContentType.JSON).body(createBody).when().post("/api/items").then().statusCode(anyOf(is(200), is(201)));
        // Test case assertion
        given().when().get("/api/items").then().statusCode(200).body("", hasSize(greaterThan(0))).body("id", everyItem(notNullValue())).body("name", everyItem(notNullValue())).body("description", everyItem(notNullValue()));
    }

    // TC-002 - Successfully retrieve a service item by ID
    @Test
    public void retrieveServiceItemById() {
        // Precondition: A service item with the specified ID exists in the system
        String createBody = """
            {
              "name": "Oil Change_%d",
              "description": "Standard oil change service",
              "status": true
            }
            """.formatted(System.currentTimeMillis());
        Integer itemId = given().contentType(ContentType.JSON).body(createBody).when().post("/api/items").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Test case assertion
        given().when().get("/api/items/{id}", itemId).then().statusCode(200).body("id", equalTo(itemId)).body("name", notNullValue()).body("description", notNullValue());
    }

    // TC-003 - Successfully add a new service item
    @Test
    public void addNewServiceItem() {
        String requestBody = """
            {
              "name": "Oil Change_%d",
              "description": "Standard oil change service",
              "status": true
            }
            """.formatted(System.currentTimeMillis());
        given().contentType(ContentType.JSON).body(requestBody).when().post("/api/items").then().statusCode(anyOf(is(200), is(201))).body("id", notNullValue()).body("name", equalTo("Oil Change_%d".formatted(System.currentTimeMillis()))).body("description", equalTo("Standard oil change service"));
    }

    // TC-004 - Successfully update an existing service item
    @Test
    public void updateExistingServiceItem() {
        // Precondition: A service item with the specified ID exists in the system
        String createBody = """
            {
              "name": "Oil Change_%d",
              "description": "Standard oil change service",
              "status": true
            }
            """.formatted(System.currentTimeMillis());
        Integer itemId = given().contentType(ContentType.JSON).body(createBody).when().post("/api/items").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        String updateBody = """
            {
              "name": "Premium Oil Change_%d",
              "description": "Premium oil change service with synthetic oil",
              "status": true
            }
            """.formatted(System.currentTimeMillis());
        // Test case assertion
        given().contentType(ContentType.JSON).body(updateBody).when().put("/api/items/{id}", itemId).then().statusCode(200).body("id", equalTo(itemId)).body("name", equalTo("Premium Oil Change_%d".formatted(System.currentTimeMillis()))).body("description", equalTo("Premium oil change service with synthetic oil"));
    }

    // 4ddea38-TC-003 - Successfully delete an existing service item
    @Test
    public void deleteExistingServiceItem() {
        // Precondition: A service item with the specified ID exists in the system
        String createBody = """
            {
              "name": "Oil Change_%d",
              "description": "Standard oil change service",
              "status": true
            }
            """.formatted(System.currentTimeMillis());
        Integer itemId = given().contentType(ContentType.JSON).body(createBody).when().post("/api/items").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Test case assertion
        given().when().delete("/api/items/{id}", itemId).then().statusCode(204);
    }

    // Test Case ID: d159982-TC-003
    @Test
    public void successfullyProcessPaymentForCompletedAppointment() {
        // Precondition: Create area
        String areaBody = """
            {
              "name": "Area_%d"
            }
            """.formatted(System.currentTimeMillis());
        Integer areaId = given().contentType(ContentType.JSON).body(areaBody).when().post("/api/areas").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Precondition: Create shop
        String shopBody = """
            {
              "shopName": "Shop_%d",
              "shopPhone": "1234567890",
              "geoLocation": "0,0",
              "ownerName": "Owner",
              "username": "owner_%d",
              "email": "owner_%d@example.com",
              "address": "123 Street",
              "areaId": %d,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), System.currentTimeMillis(), System.currentTimeMillis(), areaId);
        Integer shopId = given().contentType(ContentType.JSON).body(shopBody).when().post("/api/areas/{areaId}/shops", areaId).then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Precondition: Create item
        String itemBody = """
            {
              "name": "Item_%d",
              "description": "Test item",
              "status": true
            }
            """.formatted(System.currentTimeMillis());
        Integer itemId = given().contentType(ContentType.JSON).body(itemBody).when().post("/api/items").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Precondition: Create service profile
        String profileBody = """
            {
              "price": 100,
              "duration": 30,
              "serviceName": "Service_%d",
              "itemId": %d,
              "shopId": %d,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), itemId, shopId);
        Integer profileId = given().contentType(ContentType.JSON).body(profileBody).when().post("/api/shops/{shopId}/profiles", shopId).then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Precondition: Create worker
        String workerBody = """
            {
              "name": "Worker_%d",
              "phone": "9876543210",
              "address": "456 Avenue",
              "shopId": %d,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), shopId);
        Integer workerId = given().contentType(ContentType.JSON).body(workerBody).when().post("/api/shops/{shopId}/workers", shopId).then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Precondition: Create appointment with COMPLETE status
        String appointmentBody = """
            {
              "workerId": %d,
              "serviceProfileIds": [%d],
              "customerName": "Customer_%d",
              "customerPhone": "5551234567",
              "date": "2023-12-31",
              "slot": "09:00-10:00"
            }
            """.formatted(workerId, profileId, System.currentTimeMillis());
        Integer appointmentId = given().contentType(ContentType.JSON).body(appointmentBody).when().post("/api/shops/{shopId}/appointments", shopId).then().statusCode(anyOf(is(200), is(201))).extract().path("data.id");
        // Update appointment to COMPLETE status
        given().when().put("/api/shops/{shopId}/appointments/{id}?status=COMPLETE", shopId, appointmentId).then().statusCode(200);
        // Test: Process payment
        given().queryParam("appointmentId", appointmentId).when().post("/api/payments").then().statusCode(200).body("appointmentId", equalTo(appointmentId)).body("paymentIntentId", notNullValue()).body("amount", greaterThan(0)).body("paymentStatus", equalTo("PAID")).body("dueAmount", equalTo(0));
    }

    // Test Case ID: TC-005
    @Test
    public void failToProcessPaymentForIncompleteAppointment() {
        // Precondition: Create area
        String areaBody = """
            {
              "name": "Area_%d"
            }
            """.formatted(System.currentTimeMillis());
        Integer areaId = given().contentType(ContentType.JSON).body(areaBody).when().post("/api/areas").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Precondition: Create shop
        String shopBody = """
            {
              "shopName": "Shop_%d",
              "shopPhone": "1234567890",
              "geoLocation": "0,0",
              "ownerName": "Owner",
              "username": "owner_%d",
              "email": "owner_%d@example.com",
              "address": "123 Street",
              "areaId": %d,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), System.currentTimeMillis(), System.currentTimeMillis(), areaId);
        Integer shopId = given().contentType(ContentType.JSON).body(shopBody).when().post("/api/areas/{areaId}/shops", areaId).then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Precondition: Create item
        String itemBody = """
            {
              "name": "Item_%d",
              "description": "Test item",
              "status": true
            }
            """.formatted(System.currentTimeMillis());
        Integer itemId = given().contentType(ContentType.JSON).body(itemBody).when().post("/api/items").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Precondition: Create service profile
        String profileBody = """
            {
              "price": 100,
              "duration": 30,
              "serviceName": "Service_%d",
              "itemId": %d,
              "shopId": %d,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), itemId, shopId);
        Integer profileId = given().contentType(ContentType.JSON).body(profileBody).when().post("/api/shops/{shopId}/profiles", shopId).then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Precondition: Create worker
        String workerBody = """
            {
              "name": "Worker_%d",
              "phone": "9876543210",
              "address": "456 Avenue",
              "shopId": %d,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), shopId);
        Integer workerId = given().contentType(ContentType.JSON).body(workerBody).when().post("/api/shops/{shopId}/workers", shopId).then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Precondition: Create appointment with PENDING status
        String appointmentBody = """
            {
              "workerId": %d,
              "serviceProfileIds": [%d],
              "customerName": "Customer_%d",
              "customerPhone": "5551234567",
              "date": "2023-12-31",
              "slot": "09:00-10:00"
            }
            """.formatted(workerId, profileId, System.currentTimeMillis());
        Integer appointmentId = given().contentType(ContentType.JSON).body(appointmentBody).when().post("/api/shops/{shopId}/appointments", shopId).then().statusCode(anyOf(is(200), is(201))).extract().path("data.id");
        // Test: Attempt to process payment for incomplete appointment
        given().queryParam("appointmentId", appointmentId).when().post("/api/payments").then().statusCode(anyOf(is(400), is(500))).body(containsString("Service not completed yet"));
    }

    // Test Case ID: 43776ad-TC-004
    @Test
    public void successfullyMarkCashPaymentAsReceived() {
        // Precondition: Create area
        String areaBody = """
            {
              "name": "Area_%d"
            }
            """.formatted(System.currentTimeMillis());
        Integer areaId = given().contentType(ContentType.JSON).body(areaBody).when().post("/api/areas").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Precondition: Create shop
        String shopBody = """
            {
              "shopName": "Shop_%d",
              "shopPhone": "1234567890",
              "geoLocation": "0,0",
              "ownerName": "Owner",
              "username": "owner_%d",
              "email": "owner_%d@example.com",
              "address": "123 Street",
              "areaId": %d,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), System.currentTimeMillis(), System.currentTimeMillis(), areaId);
        Integer shopId = given().contentType(ContentType.JSON).body(shopBody).when().post("/api/areas/{areaId}/shops", areaId).then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Precondition: Create item
        String itemBody = """
            {
              "name": "Item_%d",
              "description": "Test item",
              "status": true
            }
            """.formatted(System.currentTimeMillis());
        Integer itemId = given().contentType(ContentType.JSON).body(itemBody).when().post("/api/items").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Precondition: Create service profile
        String profileBody = """
            {
              "price": 100,
              "duration": 30,
              "serviceName": "Service_%d",
              "itemId": %d,
              "shopId": %d,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), itemId, shopId);
        Integer profileId = given().contentType(ContentType.JSON).body(profileBody).when().post("/api/shops/{shopId}/profiles", shopId).then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Precondition: Create worker
        String workerBody = """
            {
              "name": "Worker_%d",
              "phone": "9876543210",
              "address": "456 Avenue",
              "shopId": %d,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), shopId);
        Integer workerId = given().contentType(ContentType.JSON).body(workerBody).when().post("/api/shops/{shopId}/workers", shopId).then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Precondition: Create appointment with COMPLETE status
        String appointmentBody = """
            {
              "workerId": %d,
              "serviceProfileIds": [%d],
              "customerName": "Customer_%d",
              "customerPhone": "5551234567",
              "date": "2023-12-31",
              "slot": "09:00-10:00"
            }
            """.formatted(workerId, profileId, System.currentTimeMillis());
        Integer appointmentId = given().contentType(ContentType.JSON).body(appointmentBody).when().post("/api/shops/{shopId}/appointments", shopId).then().statusCode(anyOf(is(200), is(201))).extract().path("data.id");
        // Update appointment to COMPLETE status
        given().when().put("/api/shops/{shopId}/appointments/{id}?status=COMPLETE", shopId, appointmentId).then().statusCode(200);
        // Test: Mark cash payment as received
        given().when().put("/api/shops/{shopId}/appointments/cashPayment/{id}", shopId, appointmentId).then().statusCode(200).body("cashReceived", equalTo(100)).body("dueAmount", equalTo(0)).body("paymentStatus", equalTo("PAID"));
    }

    // Test Case ID: TC-006
    @Test
    public void attemptToDeleteNonExistentServiceItem() {
        // Test: Delete non-existent item
        given().when().delete("/api/items/99999").then().statusCode(404);
    }

    /**
     * Test Case ID: TC-007
     * Attempt to update a service item with a non-existent ID
     */
    @Test
    public void updateNonExistentServiceItem() {
        String requestBody = """
            {
              "name": "Oil Change",
              "description": "Standard oil change service",
              "status": true
            }
            """;
        given().contentType(ContentType.JSON).body(requestBody).when().put("/api/items/99999").then().statusCode(404).body(containsString("not found"));
    }

    /**
     * Test Case ID: TC-008
     * Attempt to create a service item with missing required fields
     */
    @Test
    public void createServiceItemWithMissingRequiredFields() {
        String requestBody = """
            {
              "description": "Standard oil change service"
            }
            """;
        given().contentType(ContentType.JSON).body(requestBody).when().post("/api/items").then().statusCode(400).body(containsString("name"), containsString("required"));
    }

    /**
     * Test Case ID: TC-009
     * Attempt to retrieve a service item by malformed ID
     */
    @Test
    public void retrieveServiceItemByMalformedId() {
        given().when().get("/api/items/abc").then().statusCode(400).body(containsString("valid number"));
    }

    /**
     * Test Case ID: d159982-TC-014
     * Attempt to process payment for an appointment with incomplete service status
     */
    @Test
    public void processPaymentForIncompleteAppointment() {
        // Precondition: Create area
        Integer areaId = given().contentType(ContentType.JSON).body("""
            {
              "name": "Area_%d"
            }
            """.formatted(System.currentTimeMillis())).when().post("/api/areas").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Precondition: Create shop
        Integer shopId = given().contentType(ContentType.JSON).body("""
            {
              "shopName": "Shop_%d",
              "shopPhone": "1234567890",
              "geoLocation": "0,0",
              "ownerName": "Owner",
              "username": "owner_%d",
              "email": "owner_%d@example.com",
              "address": "123 Main St",
              "areaId": %d,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), System.currentTimeMillis(), System.currentTimeMillis(), areaId)).when().post("/api/areas/{areaId}/shops", areaId).then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Precondition: Create item
        Integer itemId = given().contentType(ContentType.JSON).body("""
            {
              "name": "Service_%d",
              "description": "Test service",
              "status": true
            }
            """.formatted(System.currentTimeMillis())).when().post("/api/items").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Precondition: Create service profile
        Integer profileId = given().contentType(ContentType.JSON).body("""
            {
              "price": 100,
              "duration": 60,
              "serviceName": "Test Service",
              "itemId": %d,
              "shopId": %d,
              "status": true
            }
            """.formatted(itemId, shopId)).when().post("/api/shops/{shopId}/profiles", shopId).then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Precondition: Create worker
        Integer workerId = given().contentType(ContentType.JSON).body("""
            {
              "name": "Worker_%d",
              "phone": "1234567890",
              "address": "123 Worker St",
              "shopId": %d,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), shopId)).when().post("/api/shops/{shopId}/workers", shopId).then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Precondition: Create appointment with PENDING status
        Integer appointmentId = given().contentType(ContentType.JSON).body("""
            {
              "workerId": %d,
              "serviceProfileIds": [%d],
              "customerName": "Customer_%d",
              "customerPhone": "1234567890",
              "date": "2025-01-01",
              "slot": "09:00-10:00"
            }
            """.formatted(workerId, profileId, System.currentTimeMillis())).when().post("/api/shops/{shopId}/appointments", shopId).then().statusCode(anyOf(is(200), is(201))).extract().path("data.id");
        // Test: Attempt to process payment for incomplete appointment
        given().queryParam("appointmentId", appointmentId).when().post("/api/payments").then().statusCode(400).body(containsString("not completed"));
    }

    // TC-014 - Attempt to process payment for a canceled appointment
    @Test
    public void attemptPaymentForCanceledAppointment() {
        // Precondition: Create area, shop, worker, service profile, and appointment with CANCELED status
        String areaBody = """
            {
              "name": "Area_%d"
            }
            """.formatted(System.currentTimeMillis());
        Integer areaId = given().contentType(ContentType.JSON).body(areaBody).when().post("/api/areas").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        String shopBody = """
            {
              "shopName": "Shop_%d",
              "shopPhone": "1234567890",
              "geoLocation": "0,0",
              "ownerName": "Owner",
              "username": "owner_%d",
              "email": "owner_%d@example.com",
              "address": "123 Street",
              "areaId": %d,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), System.currentTimeMillis(), System.currentTimeMillis(), areaId);
        Integer shopId = given().contentType(ContentType.JSON).body(shopBody).when().post("/api/areas/{areaId}/shops", areaId).then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        String workerBody = """
            {
              "name": "Worker_%d",
              "phone": "9876543210",
              "address": "456 Avenue",
              "shopId": %d,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), shopId);
        Integer workerId = given().contentType(ContentType.JSON).body(workerBody).when().post("/api/shops/{shopId}/workers", shopId).then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        String itemBody = """
            {
              "name": "Item_%d",
              "description": "Test item",
              "status": true
            }
            """.formatted(System.currentTimeMillis());
        Integer itemId = given().contentType(ContentType.JSON).body(itemBody).when().post("/api/items").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        String profileBody = """
            {
              "price": 100,
              "duration": 30,
              "serviceName": "Service_%d",
              "itemId": %d,
              "shopId": %d,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), itemId, shopId);
        Integer profileId = given().contentType(ContentType.JSON).body(profileBody).when().post("/api/shops/{shopId}/profiles", shopId).then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        String appointmentBody = """
            {
              "workerId": %d,
              "serviceProfileIds": [%d],
              "customerName": "Customer_%d",
              "customerPhone": "5551234567",
              "date": "2023-12-31",
              "slot": "09:00"
            }
            """.formatted(workerId, profileId, System.currentTimeMillis());
        Integer appointmentId = given().contentType(ContentType.JSON).body(appointmentBody).when().post("/api/shops/{shopId}/appointments", shopId).then().statusCode(anyOf(is(200), is(201))).extract().path("data.id");
        // Cancel the appointment
        given().when().put("/api/shops/{shopId}/appointments/cancel/{id}", shopId, appointmentId).then().statusCode(200);
        // Attempt payment for canceled appointment
        given().queryParam("appointmentId", appointmentId).when().post("/api/payments").then().statusCode(400).body("message", containsString("payment cannot be done for a canceled appointment"));
    }

    // TC-011 - Attempt to process payment for an already paid appointment
    @Test
    public void attemptPaymentForAlreadyPaidAppointment() {
        // Precondition: Create area, shop, worker, service profile, and appointment with PAID status
        String areaBody = """
            {
              "name": "Area_%d"
            }
            """.formatted(System.currentTimeMillis());
        Integer areaId = given().contentType(ContentType.JSON).body(areaBody).when().post("/api/areas").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        String shopBody = """
            {
              "shopName": "Shop_%d",
              "shopPhone": "1234567890",
              "geoLocation": "0,0",
              "ownerName": "Owner",
              "username": "owner_%d",
              "email": "owner_%d@example.com",
              "address": "123 Street",
              "areaId": %d,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), System.currentTimeMillis(), System.currentTimeMillis(), areaId);
        Integer shopId = given().contentType(ContentType.JSON).body(shopBody).when().post("/api/areas/{areaId}/shops", areaId).then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        String workerBody = """
            {
              "name": "Worker_%d",
              "phone": "9876543210",
              "address": "456 Avenue",
              "shopId": %d,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), shopId);
        Integer workerId = given().contentType(ContentType.JSON).body(workerBody).when().post("/api/shops/{shopId}/workers", shopId).then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        String itemBody = """
            {
              "name": "Item_%d",
              "description": "Test item",
              "status": true
            }
            """.formatted(System.currentTimeMillis());
        Integer itemId = given().contentType(ContentType.JSON).body(itemBody).when().post("/api/items").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        String profileBody = """
            {
              "price": 100,
              "duration": 30,
              "serviceName": "Service_%d",
              "itemId": %d,
              "shopId": %d,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), itemId, shopId);
        Integer profileId = given().contentType(ContentType.JSON).body(profileBody).when().post("/api/shops/{shopId}/profiles", shopId).then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        String appointmentBody = """
            {
              "workerId": %d,
              "serviceProfileIds": [%d],
              "customerName": "Customer_%d",
              "customerPhone": "5551234567",
              "date": "2023-12-31",
              "slot": "09:00"
            }
            """.formatted(workerId, profileId, System.currentTimeMillis());
        Integer appointmentId = given().contentType(ContentType.JSON).body(appointmentBody).when().post("/api/shops/{shopId}/appointments", shopId).then().statusCode(anyOf(is(200), is(201))).extract().path("data.id");
        // Mark appointment as COMPLETE and PAID via cash payment
        given().when().put("/api/shops/{shopId}/appointments/{id}?status=COMPLETE", shopId, appointmentId).then().statusCode(200);
        given().when().put("/api/shops/{shopId}/appointments/cashPayment/{id}", shopId, appointmentId).then().statusCode(200);
        // Attempt payment for already paid appointment
        given().queryParam("appointmentId", appointmentId).when().post("/api/payments").then().statusCode(400).body("message", containsString("payment has already been done"));
    }

    /**
     * Test Case ID: TC-015
     */
    @Test
    public void addNewItemWithMaximumAllowedNameLength() {
        String requestBody = """
            {
              "name": "%s",
              "description": "Test item",
              "status": true
            }
            """.formatted("a".repeat(255));
        given().contentType(ContentType.JSON).body(requestBody).when().post("/api/items").then().statusCode(201).body("name", equalTo("a".repeat(255))).body("description", equalTo("Test item"));
    }

    /**
     * Test Case ID: TC-016
     */
    @Test
    public void addNewItemWithNameExceedingMaximumAllowedLength() {
        String requestBody = """
            {
              "name": "%s",
              "description": "Test item",
              "status": true
            }
            """.formatted("a".repeat(256));
        given().contentType(ContentType.JSON).body(requestBody).when().post("/api/items").then().statusCode(400).body("message", containsString("exceeds the maximum length"));
    }

    /**
     * Test Case ID: TC-017
     */
    @Test
    public void updateExistingItemWithEmptyName() {
        // Precondition: create an item
        String createBody = """
            {
              "name": "Original Item",
              "description": "Original description",
              "status": true
            }
            """;
        Integer itemId = given().contentType(ContentType.JSON).body(createBody).when().post("/api/items").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Test: update with empty name
        String updateBody = """
            {
              "name": "",
              "description": "Updated test item",
              "status": true
            }
            """;
        given().contentType(ContentType.JSON).body(updateBody).when().put("/api/items/{id}", itemId).then().statusCode(400).body("message", containsString("cannot be empty"));
    }

    /**
     * Test Case ID: TC-018
     */
    @Test
    public void deleteNonExistentItem() {
        given().contentType(ContentType.JSON).when().delete("/api/items/{id}", 99999).then().statusCode(404).body("message", containsString("not found"));
    }

    private Integer areaId;

    private Integer shopId;

    private Integer workerId;

    private Integer serviceProfileId;

    private Integer itemId;

    private Integer appointmentId;

    @AfterClass
    public void cleanup() {
        // Cleanup Appointment
        if (appointmentId != null) {
            given().contentType(ContentType.JSON).when().put("/api/shops/{shopId}/appointments/cancel/{id}", shopId, appointmentId).then().statusCode(anyOf(is(200), is(204), is(404)));
        }
        // Cleanup Service Profile
        if (serviceProfileId != null) {
            given().contentType(ContentType.JSON).when().delete("/api/shops/{shopId}/profiles/{id}", shopId, serviceProfileId).then().statusCode(anyOf(is(200), is(204), is(404)));
        }
        // Cleanup Worker
        if (workerId != null) {
            given().contentType(ContentType.JSON).when().delete("/api/shops/{shopId}/workers/{id}", shopId, workerId).then().statusCode(anyOf(is(200), is(204), is(404)));
        }
        // Cleanup Item
        if (itemId != null) {
            given().contentType(ContentType.JSON).when().delete("/api/items/{id}", itemId).then().statusCode(anyOf(is(200), is(204), is(404)));
        }
        // Cleanup Shop
        if (shopId != null) {
            given().contentType(ContentType.JSON).when().delete("/api/areas/{areaId}/shops/{id}", areaId, shopId).then().statusCode(anyOf(is(200), is(204), is(404)));
        }
        // Cleanup Area
        if (areaId != null) {
            given().contentType(ContentType.JSON).when().delete("/api/areas/{id}", areaId).then().statusCode(anyOf(is(200), is(204), is(404)));
        }
    }

    /**
     * Test Case ID: TC-019
     */
    @Test
    public void createPaymentForAppointmentWithZeroTotalAmount() {
        given().queryParam("appointmentId", appointmentId).when().post("/api/payments").then().statusCode(400).body("message", containsString("cannot be processed for zero amount"));
    }

    // TC-020 - Create payment for an appointment with very large total amount
    @Test
    public void createPaymentForAppointmentWithLargeAmount() {
        // Precondition: Create an area, shop, worker, service profile, and appointment
        String areaBody = """
            {
              "name": "Area_%d"
            }
            """.formatted(System.currentTimeMillis());
        Integer areaId = given().contentType(ContentType.JSON).body(areaBody).when().post("/api/areas").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        String shopBody = """
            {
              "shopName": "Shop_%d",
              "shopPhone": "1234567890",
              "geoLocation": "0,0",
              "ownerName": "Owner",
              "username": "owner_%d",
              "email": "owner_%d@example.com",
              "address": "123 Main St",
              "areaId": %d,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), System.currentTimeMillis(), System.currentTimeMillis(), areaId);
        Integer shopId = given().contentType(ContentType.JSON).body(shopBody).when().post("/api/areas/{areaId}/shops", areaId).then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        String workerBody = """
            {
              "name": "Worker_%d",
              "phone": "9876543210",
              "address": "456 Worker Ave",
              "shopId": %d,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), shopId);
        Integer workerId = given().contentType(ContentType.JSON).body(workerBody).when().post("/api/shops/{shopId}/workers", shopId).then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        String itemBody = """
            {
              "name": "Item_%d",
              "description": "Test Item",
              "status": true
            }
            """.formatted(System.currentTimeMillis());
        Integer itemId = given().contentType(ContentType.JSON).body(itemBody).when().post("/api/items").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        String profileBody = """
            {
              "price": 1000000,
              "duration": 60,
              "serviceName": "Premium Service",
              "itemId": %d,
              "shopId": %d,
              "status": true
            }
            """.formatted(itemId, shopId);
        Integer profileId = given().contentType(ContentType.JSON).body(profileBody).when().post("/api/shops/{shopId}/profiles", shopId).then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        String appointmentBody = """
            {
              "workerId": %d,
              "serviceProfileIds": [%d],
              "customerName": "Customer_%d",
              "customerPhone": "5551234567",
              "date": "2025-12-31",
              "slot": "09:00-10:00"
            }
            """.formatted(workerId, profileId, System.currentTimeMillis());
        Integer appointmentId = given().contentType(ContentType.JSON).body(appointmentBody).when().post("/api/shops/{shopId}/appointments", shopId).then().statusCode(anyOf(is(200), is(201))).extract().path("data.id");
        // Test: Create payment for the appointment
        given().queryParam("appointmentId", appointmentId).when().post("/api/payments").then().statusCode(200).body("amount", equalTo(1000000));
    }

    // TC-021 - Create payment for a non-existent appointment
    @Test
    public void createPaymentForNonExistentAppointment() {
        given().queryParam("appointmentId", 99999).when().post("/api/payments").then().statusCode(404).body(containsString("not found"));
    }

    // TC-023 - Verify deletion of non-existent item returns appropriate status
    @Test
    public void deleteNonExistentItem2() {
        given().when().delete("/api/items/999").then().statusCode(404);
    }

    // TC-024 - Verify successful deletion of an item returns appropriate status
    @Test
    public void deleteExistingItem() {
        // Precondition: Create an item
        String itemBody = """
            {
              "name": "Item_%d",
              "description": "Test Item",
              "status": true
            }
            """.formatted(System.currentTimeMillis());
        Integer itemId = given().contentType(ContentType.JSON).body(itemBody).when().post("/api/items").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Test: Delete the item
        given().when().delete("/api/items/{id}", itemId).then().statusCode(204);
    }

    // TC-025 - Verify payment cannot be processed for an incomplete appointment
    @Test
    public void verifyPaymentCannotBeProcessedForIncompleteAppointment() {
        // Precondition: Create area, shop, worker, service profile, and appointment with status PENDING
        Integer areaId = given().contentType(ContentType.JSON).body("""
            {
              "name": "Area_%d"
            }
            """.formatted(System.currentTimeMillis())).when().post("/api/areas").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        Integer shopId = given().contentType(ContentType.JSON).body("""
            {
              "shopName": "Shop_%d",
              "shopPhone": "1234567890",
              "geoLocation": "0,0",
              "ownerName": "Owner",
              "username": "owner_%d",
              "email": "owner_%d@example.com",
              "address": "123 Street",
              "areaId": %d,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), System.currentTimeMillis(), System.currentTimeMillis(), areaId)).when().post("/api/areas/{areaId}/shops", areaId).then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        Integer workerId = given().contentType(ContentType.JSON).body("""
            {
              "name": "Worker_%d",
              "phone": "9876543210",
              "address": "456 Avenue",
              "shopId": %d,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), shopId)).when().post("/api/shops/{shopId}/workers", shopId).then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        Integer itemId = given().contentType(ContentType.JSON).body("""
            {
              "name": "Item_%d",
              "description": "Test Item",
              "status": true
            }
            """.formatted(System.currentTimeMillis())).when().post("/api/items").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        Integer profileId = given().contentType(ContentType.JSON).body("""
            {
              "price": 100,
              "duration": 30,
              "serviceName": "Test Service",
              "itemId": %d,
              "shopId": %d,
              "status": true
            }
            """.formatted(itemId, shopId)).when().post("/api/shops/{shopId}/profiles", shopId).then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        Integer appointmentId = given().contentType(ContentType.JSON).body("""
            {
              "workerId": %d,
              "serviceProfileIds": [%d],
              "customerName": "Customer",
              "customerPhone": "5551234567",
              "date": "2025-12-31",
              "slot": "09:00-10:00"
            }
            """.formatted(workerId, profileId)).when().post("/api/shops/{shopId}/appointments", shopId).then().statusCode(anyOf(is(200), is(201))).extract().path("data.id");
        // Update appointment status to PENDING (assuming status query param is used)
        given().queryParam("status", "PENDING").when().put("/api/shops/{shopId}/appointments/{id}", shopId, appointmentId).then().statusCode(200);
        // Test: Attempt payment for incomplete appointment
        given().queryParam("appointmentId", appointmentId).when().post("/api/payments").then().statusCode(400).body(containsString("Service not completed yet"));
    }

    // TC-026 - Verify payment status is set to PAID after cash payment for completed appointment
    @Test
    public void verifyPaymentStatusSetToPaidAfterCashPayment() {
        // Precondition: Create area, shop, worker, service profile, and appointment with status COMPLETE
        Integer areaId = given().contentType(ContentType.JSON).body("""
            {
              "name": "Area_%d"
            }
            """.formatted(System.currentTimeMillis())).when().post("/api/areas").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        Integer shopId = given().contentType(ContentType.JSON).body("""
            {
              "shopName": "Shop_%d",
              "shopPhone": "1234567890",
              "geoLocation": "0,0",
              "ownerName": "Owner",
              "username": "owner_%d",
              "email": "owner_%d@example.com",
              "address": "123 Street",
              "areaId": %d,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), System.currentTimeMillis(), System.currentTimeMillis(), areaId)).when().post("/api/areas/{areaId}/shops", areaId).then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        Integer workerId = given().contentType(ContentType.JSON).body("""
            {
              "name": "Worker_%d",
              "phone": "9876543210",
              "address": "456 Avenue",
              "shopId": %d,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), shopId)).when().post("/api/shops/{shopId}/workers", shopId).then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        Integer itemId = given().contentType(ContentType.JSON).body("""
            {
              "name": "Item_%d",
              "description": "Test Item",
              "status": true
            }
            """.formatted(System.currentTimeMillis())).when().post("/api/items").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        Integer profileId = given().contentType(ContentType.JSON).body("""
            {
              "price": 100,
              "duration": 30,
              "serviceName": "Test Service",
              "itemId": %d,
              "shopId": %d,
              "status": true
            }
            """.formatted(itemId, shopId)).when().post("/api/shops/{shopId}/profiles", shopId).then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        Integer appointmentId = given().contentType(ContentType.JSON).body("""
            {
              "workerId": %d,
              "serviceProfileIds": [%d],
              "customerName": "Customer",
              "customerPhone": "5551234567",
              "date": "2025-12-31",
              "slot": "09:00-10:00"
            }
            """.formatted(workerId, profileId)).when().post("/api/shops/{shopId}/appointments", shopId).then().statusCode(anyOf(is(200), is(201))).extract().path("data.id");
        // Update appointment status to COMPLETE
        given().queryParam("status", "COMPLETE").when().put("/api/shops/{shopId}/appointments/{id}", shopId, appointmentId).then().statusCode(200);
        // Test: Process cash payment
        given().when().put("/api/shops/{shopId}/appointments/cashPayment/{id}", shopId, appointmentId).then().statusCode(200).body("paymentStatus", equalTo("PAID")).body("dueAmount", equalTo(0));
    }

    // TC-027 - Verify item search handles special characters in name parameter
    @Test
    public void verifyItemSearchHandlesSpecialCharacters() {
        given().queryParam("name", "<script>alert(1)</script>").when().get("/api/items/search").then().statusCode(anyOf(is(400), is(200))).body(anyOf(nullValue(), empty()));
    }

    // TC-028 - Verify item search handles SQL injection in name parameter
    @Test
    public void verifyItemSearchHandlesSqlInjection() {
        given().queryParam("name", "' OR '1'='1").when().get("/api/items/search").then().statusCode(anyOf(is(400), is(200))).body(anyOf(nullValue(), empty()));
    }

}
