package com.company.aiqa.generated;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import org.testng.Assert;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import java.time.LocalDate;
import java.util.List;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;
import java.time.LocalTime;

/**
 * Automated API tests for commit 66188563dcba8d3b1a057244f31893db33e0a5a4.
 * Generated by ai-qa-platform from that commit's manual test cases.
 */
public class AutomationTest_66188563dcba8d3b1a057244f31893db33e0a5a4 {

    @BeforeClass
    public void setup() {
        RestAssured.baseURI = System.getProperty("baseUri", "http://localhost:8080");
    }

    // Test Case ID: d750aff-TC-001
    @Test
    public void successfullyAddMultipleHolidaysForShop() {
        // Precondition: Create a shop first
        String shopBody = """
            {
              "shopName": "Shop_%d",
              "shopPhone": "1234567890",
              "geoLocation": "0,0",
              "ownerName": "Owner",
              "username": "owner_%d",
              "email": "owner_%d@example.com",
              "address": "123 Main St",
              "areaId": 1,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), System.currentTimeMillis(), System.currentTimeMillis());
        Long shopId = given().contentType(ContentType.JSON).body(shopBody).when().post("/api/areas/1/shops").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Test case: Add multiple holidays
        String holidaysBody = """
            [
              {
                "shopId": %d,
                "holidayDate": "2024-12-25",
                "reason": "Christmas Day"
              },
              {
                "shopId": %d,
                "holidayDate": "2024-12-26",
                "reason": "Boxing Day"
              }
            ]
            """.formatted(shopId, shopId);
        given().contentType(ContentType.JSON).body(holidaysBody).when().post("/api/shop-holidays/add?shopId={shopId}", shopId).then().statusCode(200).body(containsString("All holidays added successfully"));
        // Verify holidays were added
        given().when().get("/api/shop-holidays/{shopId}?page=0&limit=10", shopId).then().statusCode(200).body("data.content.holidayDate", hasItems("2024-12-25", "2024-12-26")).body("data.content.reason", hasItems("Christmas Day", "Boxing Day"));
    }

    // Test Case ID: d750aff-TC-002
    @Test
    public void failToAddDuplicateHolidaysForSameShopAndDates() {
        // Precondition: Create a shop first
        String shopBody = """
            {
              "shopName": "Shop_%d",
              "shopPhone": "1234567890",
              "geoLocation": "0,0",
              "ownerName": "Owner",
              "username": "owner_%d",
              "email": "owner_%d@example.com",
              "address": "123 Main St",
              "areaId": 1,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), System.currentTimeMillis(), System.currentTimeMillis());
        Long shopId = given().contentType(ContentType.JSON).body(shopBody).when().post("/api/areas/1/shops").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Precondition: Add a holiday for 2024-12-25
        String firstHolidayBody = """
            [
              {
                "shopId": %d,
                "holidayDate": "2024-12-25",
                "reason": "Christmas Day"
              }
            ]
            """.formatted(shopId);
        given().contentType(ContentType.JSON).body(firstHolidayBody).when().post("/api/shop-holidays/add?shopId={shopId}", shopId).then().statusCode(200);
        // Test case: Try to add duplicate holiday for 2024-12-25
        String duplicateHolidaysBody = """
            [
              {
                "shopId": %d,
                "holidayDate": "2024-12-25",
                "reason": "Christmas Holiday"
              },
              {
                "shopId": %d,
                "holidayDate": "2024-12-26",
                "reason": "Boxing Day"
              }
            ]
            """.formatted(shopId, shopId);
        String responseBody = given().contentType(ContentType.JSON).body(duplicateHolidaysBody).when().post("/api/shop-holidays/add?shopId={shopId}", shopId).then().statusCode(200).extract().asString();
        Assert.assertTrue(responseBody.contains("Some holidays were already declared and were skipped"), "Expected the response to indicate skipped holidays. Body was: " + responseBody);
        // Verify only 2024-12-26 was added
        given().when().get("/api/shop-holidays/{shopId}?page=0&limit=10", shopId).then().statusCode(200).body("data.content.holidayDate", hasItem("2024-12-26")).body("data.content.holidayDate", // Original holiday should still exist
        not(hasItem("2024-12-25")));
    }

    // Test Case ID: 3067f8e-TC-001
    @Test
    public void failToUpdateShopHolidayToDateThatAlreadyHasHoliday() {
        // Precondition: Create a shop first
        String shopBody = """
            {
              "shopName": "Shop_%d",
              "shopPhone": "1234567890",
              "geoLocation": "0,0",
              "ownerName": "Owner",
              "username": "owner_%d",
              "email": "owner_%d@example.com",
              "address": "123 Main St",
              "areaId": 1,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), System.currentTimeMillis(), System.currentTimeMillis());
        Long shopId = given().contentType(ContentType.JSON).body(shopBody).when().post("/api/areas/1/shops").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Precondition: Add holidays for 2024-12-25 and 2024-12-31
        String holidaysBody = """
            [
              {
                "shopId": %d,
                "holidayDate": "2024-12-25",
                "reason": "Christmas Day"
              },
              {
                "shopId": %d,
                "holidayDate": "2024-12-31",
                "reason": "New Year's Eve"
              }
            ]
            """.formatted(shopId, shopId);
        given().contentType(ContentType.JSON).body(holidaysBody).when().post("/api/shop-holidays/add?shopId={shopId}", shopId).then().statusCode(200);
        // Get the holiday ID for 2024-12-25
        Long holidayId = given().when().get("/api/shop-holidays/{shopId}?page=0&limit=10", shopId).then().statusCode(200).extract().path("data.content.find { it.holidayDate == '2024-12-25' }.id");
        // Test case: Try to update 2024-12-25 holiday to 2024-12-31
        String updateBody = """
            {
              "id": %d,
              "shopId": %d,
              "holidayDate": "2024-12-31",
              "reason": "Christmas Day"
            }
            """.formatted(holidayId, shopId);
        String responseBody = given().contentType(ContentType.JSON).body(updateBody).when().put("/api/shop-holidays/{holidayId}", holidayId).then().statusCode(anyOf(is(400), is(409))).extract().asString();
        Assert.assertTrue(responseBody.toLowerCase().contains("already has a holiday"), "Expected the error to mention duplicate holiday. Body was: " + responseBody);
        // Verify the holiday date remains unchanged
        given().when().get("/api/shop-holidays/{shopId}?page=0&limit=10", shopId).then().statusCode(200).body("data.content.find { it.id == %d }.holidayDate".formatted(holidayId), equalTo("2024-12-25"));
    }

    // Test Case ID: d750aff-TC-004
    @Test
    public void successfullyConfigureNewSlotForShop() {
        // Precondition: Create a shop first
        String shopBody = """
            {
              "shopName": "Shop_%d",
              "shopPhone": "1234567890",
              "geoLocation": "0,0",
              "ownerName": "Owner",
              "username": "owner_%d",
              "email": "owner_%d@example.com",
              "address": "123 Main St",
              "areaId": 1,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), System.currentTimeMillis(), System.currentTimeMillis());
        Long shopId = given().contentType(ContentType.JSON).body(shopBody).when().post("/api/areas/1/shops").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Test case: Add a new EVENING slot
        String slotBody = """
            {
              "shopId": %d,
              "startTime": "17:00:00",
              "endTime": "20:00:00",
              "slotType": "EVENING",
              "isActive": true
            }
            """.formatted(shopId);
        given().contentType(ContentType.JSON).body(slotBody).when().post("/api/slots/set?shopId={shopId}", shopId).then().statusCode(200).body(containsString("Slot configuration saved"));
        // Verify the slot appears in the list
        given().when().get("/api/slots/{shopId}?page=0&limit=10", shopId).then().statusCode(200).body("data.content.find { it.slotType == 'EVENING' }.startTime", equalTo("17:00:00")).body("data.content.find { it.slotType == 'EVENING' }.endTime", equalTo("20:00:00")).body("data.content.find { it.slotType == 'EVENING' }.isActive", equalTo(true));
    }

    // Test Case ID: 01b5363-TC-002
    @Test
    public void failToConfigureNewSlotDueToDuplicateSlotType() {
        // Precondition: Create a shop first
        String shopBody = """
            {
              "shopName": "Shop_%d",
              "shopPhone": "1234567890",
              "geoLocation": "0,0",
              "ownerName": "Owner",
              "username": "owner_%d",
              "email": "owner_%d@example.com",
              "address": "123 Main St",
              "areaId": 1,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), System.currentTimeMillis(), System.currentTimeMillis());
        Long shopId = given().contentType(ContentType.JSON).body(shopBody).when().post("/api/areas/1/shops").then().statusCode(anyOf(is(200), is(201))).extract().path("id");
        // Precondition: Add a MORNING slot first
        String firstSlotBody = """
            {
              "shopId": %d,
              "startTime": "09:00:00",
              "endTime": "12:00:00",
              "slotType": "MORNING",
              "isActive": true
            }
            """.formatted(shopId);
        given().contentType(ContentType.JSON).body(firstSlotBody).when().post("/api/slots/set?shopId={shopId}", shopId).then().statusCode(200);
        // Test case: Try to add another MORNING slot
        String duplicateSlotBody = """
            {
              "shopId": %d,
              "startTime": "09:00:00",
              "endTime": "12:00:00",
              "slotType": "MORNING",
              "isActive": true
            }
            """.formatted(shopId);
        String responseBody = given().contentType(ContentType.JSON).body(duplicateSlotBody).when().post("/api/slots/set?shopId={shopId}", shopId).then().statusCode(anyOf(is(400), is(409))).extract().asString();
        Assert.assertTrue(responseBody.toLowerCase().contains("already exists"), "Expected the error to mention duplicate slot type. Body was: " + responseBody);
    }

}
