package com.company.aiqa.generated;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.AfterClass;
import org.testng.annotations.Test;
import java.time.LocalDate;
import java.util.List;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;
import java.time.LocalTime;

/**
 * Automated API tests for commit 66188563dcba8d3b1a057244f31893db33e0a5a4.
 * Generated by ai-qa-platform from that commit's manual test cases.
 */
public class AutomationTest_66188563dcba8d3b1a057244f31893db33e0a5a4 {

    private Long areaId;

    private Long shopId;

    private List<Long> holidayIds;

    @BeforeClass
    public void setup() {
        RestAssured.baseURI = System.getProperty("baseUri", "http://localhost:8082");
        // Create an area
        String areaBody = """
            {
              "name": "Area_%d"
            }
            """.formatted(System.currentTimeMillis());
        areaId = given().contentType(ContentType.JSON).body(areaBody).when().post("/api/areas").then().statusCode(anyOf(is(200), is(201))).extract().path("data.id");
        // Create a shop
        String shopBody = """
            {
              "shopName": "Shop_%d",
              "shopPhone": "1234567890",
              "geoLocation": "0,0",
              "ownerName": "Owner",
              "username": "owner_%d",
              "email": "owner_%d@example.com",
              "address": "123 Street",
              "areaId": %d,
              "status": true
            }
            """.formatted(System.currentTimeMillis(), System.currentTimeMillis(), System.currentTimeMillis(), areaId);
        shopId = given().contentType(ContentType.JSON).body(shopBody).when().post("/api/areas/{areaId}/shops", areaId).then().statusCode(200).extract().path("id");
    }

    @AfterClass
    public void cleanup() {
        if (holidayIds != null) {
            for (Long holidayId : holidayIds) {
                given().when().delete("/api/shop-holidays/{holidayId}", holidayId).then().statusCode(anyOf(is(200), is(204), is(404)));
            }
        }
        given().when().delete("/api/areas/{areaId}/shops/{id}", areaId, shopId).then().statusCode(anyOf(is(200), is(204), is(404)));
        given().when().delete("/api/areas/{id}", areaId).then().statusCode(anyOf(is(200), is(204), is(404)));
    }

    /**
     * Test Case ID: d750aff-TC-001
     */
    @Test
    public void successfullyAddMultipleHolidaysForShop() {
        String requestBody = """
            [
              {
                "shopId": %d,
                "holidayDate": "2024-12-25",
                "reason": "Christmas Day"
              },
              {
                "shopId": %d,
                "holidayDate": "2024-12-26",
                "reason": "Boxing Day"
              }
            ]
            """.formatted(shopId, shopId);
        given().contentType(ContentType.JSON).body(requestBody).queryParam("shopId", shopId).when().post("/api/shop-holidays/add").then().statusCode(200).body("message", containsString("All holidays added successfully"));
        // Verify holidays are in the list
        given().queryParam("page", 0).queryParam("limit", 10).when().get("/api/shop-holidays/{shopId}", shopId).then().statusCode(200).body("data.content.holidayDate", hasItems("2024-12-25", "2024-12-26"));
    }

    /**
     * Test Case ID: d750aff-TC-002
     */
    @Test
    public void failToAddDuplicateHolidaysForSameShopAndDates() {
        // First, add a holiday for 2024-12-25
        String firstHoliday = """
            [
              {
                "shopId": %d,
                "holidayDate": "2024-12-25",
                "reason": "Christmas Day"
              }
            ]
            """.formatted(shopId);
        given().contentType(ContentType.JSON).body(firstHoliday).queryParam("shopId", shopId).when().post("/api/shop-holidays/add").then().statusCode(200);
        // Now try to add holidays including the duplicate
        String requestBody = """
            [
              {
                "shopId": %d,
                "holidayDate": "2024-12-25",
                "reason": "Christmas Holiday"
              },
              {
                "shopId": %d,
                "holidayDate": "2024-12-26",
                "reason": "Boxing Day"
              }
            ]
            """.formatted(shopId, shopId);
        given().contentType(ContentType.JSON).body(requestBody).queryParam("shopId", shopId).when().post("/api/shop-holidays/add").then().statusCode(200).body("message", containsString("Some holidays were already declared and were skipped: [2024-12-25]"));
        // Verify only 2024-12-26 is added
        given().queryParam("page", 0).queryParam("limit", 10).when().get("/api/shop-holidays/{shopId}", shopId).then().statusCode(200).body("data.content.holidayDate", hasItem("2024-12-26")).body("data.content.holidayDate", // Original should still be there, but not duplicated
        not(hasItem("2024-12-25")));
    }

    /**
     * Test Case ID: 3067f8e-TC-001
     */
    @Test
    public void failToUpdateShopHolidayToDateWithExistingHoliday() {
        // First, add two holidays
        String holidays = """
            [
              {
                "shopId": %d,
                "holidayDate": "2024-12-25",
                "reason": "Christmas Day"
              },
              {
                "shopId": %d,
                "holidayDate": "2024-12-31",
                "reason": "New Year's Eve"
              }
            ]
            """.formatted(shopId, shopId);
        holidayIds = given().contentType(ContentType.JSON).body(holidays).queryParam("shopId", shopId).when().post("/api/shop-holidays/add").then().statusCode(200).extract().path(// Assuming response contains IDs
        "data.id");
        // Extract the ID of the 2024-12-25 holiday
        Long holidayId25 = given().queryParam("page", 0).queryParam("limit", 10).when().get("/api/shop-holidays/{shopId}", shopId).then().statusCode(200).extract().path("data.content.find { it.holidayDate == '2024-12-25' }.id");
        // Try to update 2024-12-25 to 2024-12-31
        String updateBody = """
            {
              "id": %d,
              "shopId": %d,
              "holidayDate": "2024-12-31",
              "reason": "Christmas Day"
            }
            """.formatted(holidayId25, shopId);
        given().contentType(ContentType.JSON).body(updateBody).when().put("/api/shop-holidays/{holidayId}", holidayId25).then().statusCode(400).body("message", containsString("Shop already has a holiday on 2024-12-31"));
        // Verify the holiday date remains unchanged
        given().when().get("/api/shop-holidays/{shopId}?page=0&limit=10", shopId).then().statusCode(200).body("data.content.find { it.id == %d }.holidayDate", equalTo("2024-12-25"));
    }

    private Long slotId;

    @AfterClass
    public void cleanup2() {
        if (slotId != null) {
            given().when().put("/api/slots/deactivate/{slotId}", slotId).then().statusCode(anyOf(is(200), is(404)));
        }
        given().when().delete("/api/areas/{areaId}/shops/{id}", areaId, shopId).then().statusCode(anyOf(is(200), is(204), is(404)));
        given().when().delete("/api/areas/{id}", areaId).then().statusCode(anyOf(is(200), is(204), is(404)));
    }

    /**
     * Test Case ID: d750aff-TC-004
     */
    @Test
    public void successfullyConfigureNewSlotForShop() {
        String requestBody = """
            {
              "shopId": %d,
              "startTime": "17:00:00",
              "endTime": "20:00:00",
              "slotType": "EVENING",
              "isActive": true
            }
            """.formatted(shopId);
        given().contentType(ContentType.JSON).body(requestBody).queryParam("shopId", shopId).when().post("/api/slots/set").then().statusCode(200).body("message", containsString("Slot configuration saved"));
        // Verify the slot appears in the list
        slotId = given().queryParam("page", 0).queryParam("limit", 10).when().get("/api/slots/{shopId}", shopId).then().statusCode(200).body("data.content.find { it.slotType == 'EVENING' }.startTime", equalTo("17:00:00")).body("data.content.find { it.slotType == 'EVENING' }.endTime", equalTo("20:00:00")).body("data.content.find { it.slotType == 'EVENING' }.isActive", equalTo(true)).extract().path("data.content.find { it.slotType == 'EVENING' }.id");
    }

    /**
     * Test Case ID: 01b5363-TC-002
     */
    @Test
    public void failToConfigureNewSlotDueToDuplicateSlotType() {
        // First, create a MORNING slot
        String morningSlot = """
            {
              "shopId": %d,
              "startTime": "09:00:00",
              "endTime": "12:00:00",
              "slotType": "MORNING",
              "isActive": true
            }
            """.formatted(shopId);
        given().contentType(ContentType.JSON).body(morningSlot).queryParam("shopId", shopId).when().post("/api/slots/set").then().statusCode(200);
        // Now try to create another MORNING slot
        String requestBody = """
            {
              "shopId": %d,
              "startTime": "09:00:00",
              "endTime": "12:00:00",
              "slotType": "MORNING",
              "isActive": true
            }
            """.formatted(shopId);
        given().contentType(ContentType.JSON).body(requestBody).queryParam("shopId", shopId).when().post("/api/slots/set").then().statusCode(400).body("message", containsString("A slot with type MORNING already exists for this shop"));
    }

}
